// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion from generated wire types to the idiomatic response
// structs. Deref helpers turn optional wire pointers into plain
// values so customers never nil-check a primitive.

package authv1

import spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}
func derefBool(p *bool) bool {
	if p == nil {
		return false
	}
	return *p
}
func derefInt32(p *int32) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefInt64(p *int64) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefF32(p *float32) float64 {
	if p == nil {
		return 0
	}
	return float64(*p)
}
func derefF64(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p
}

func convertGrantTokenOutput(in *spectypes.GrantTokenOutput) *GrantTokenOutput {
	if in == nil {
		return nil
	}
	out := &GrantTokenOutput{}
	out.AccessToken = derefStr(in.Access_token)
	out.ExpiresIn = derefInt32(in.Expires_in)
	return out
}
