// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generated wire tests, one per operation. An in-process httptest
// server captures the request; each verifies HTTP method, path
// prefix, and Token auth. Regenerated with the client; the
// hand-authored behavioral *_test.go beside it are preserved.

package authv1

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestWireGen_GrantToken(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GrantToken(context.Background(), nil, nil)
	if gotMethod != "POST" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/auth/grant") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}
