// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing live (WebSocket) client, generated by
// spec-codegen-go's model-driven streaming facade emitter.
// Recv returns an idiomatic Event (see events.go).

package livev1

import (
	"context"
	"errors"
	"fmt"
	wstransport "github.com/deepgram/spec-mock-go-sdk/api/transport/websocket"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
	nethttp "net/http"
	"net/url"
	"os"
	"reflect"
	"strconv"
	"time"
)

const DefaultBaseURL = "wss://api.deepgram.com"
const streamPath = "/v1/listen"

type LiveTranscriptionOptions struct {
	Channels              int        `json:"channels,omitempty" schema:"channels,omitempty"`
	Diarize               bool       `json:"diarize,omitempty" schema:"diarize,omitempty"`
	DiarizeVersion        string     `json:"diarize_version,omitempty" schema:"diarize_version,omitempty"`
	Encoding              string     `json:"encoding,omitempty" schema:"encoding,omitempty"`
	Endpointing           int        `json:"endpointing,omitempty" schema:"endpointing,omitempty"`
	InterimResults        bool       `json:"interim_results,omitempty" schema:"interim_results,omitempty"`
	Keyterm               []string   `json:"keyterm,omitempty" schema:"keyterm,omitempty"`
	Keywords              []string   `json:"keywords,omitempty" schema:"keywords,omitempty"`
	Language              string     `json:"language,omitempty" schema:"language,omitempty"`
	LogData               bool       `json:"log_data,omitempty" schema:"log_data,omitempty"`
	MipOptOut             bool       `json:"mip_opt_out,omitempty" schema:"mip_opt_out,omitempty"`
	Model                 string     `json:"model,omitempty" schema:"model,omitempty"`
	Multichannel          bool       `json:"multichannel,omitempty" schema:"multichannel,omitempty"`
	ProfanityFilter       bool       `json:"profanity_filter,omitempty" schema:"profanity_filter,omitempty"`
	Punctuate             bool       `json:"punctuate,omitempty" schema:"punctuate,omitempty"`
	Redact                []string   `json:"redact,omitempty" schema:"redact,omitempty"`
	SampleRate            int        `json:"sample_rate,omitempty" schema:"sample_rate,omitempty"`
	Search                []string   `json:"search,omitempty" schema:"search,omitempty"`
	SmartFormat           bool       `json:"smart_format,omitempty" schema:"smart_format,omitempty"`
	Tag                   []string   `json:"tag,omitempty" schema:"tag,omitempty"`
	UtteranceEndMs        int        `json:"utterance_end_ms,omitempty" schema:"utterance_end_ms,omitempty"`
	VadEvents             bool       `json:"vad_events,omitempty" schema:"vad_events,omitempty"`
	VadTurnoff            int        `json:"vad_turnoff,omitempty" schema:"vad_turnoff,omitempty"`
	Version               string     `json:"version,omitempty" schema:"version,omitempty"`
	AdditionalQueryParams url.Values `json:"-" schema:"-"`
}

type Client struct {
	apiKey, accessToken, baseURL string
	transport                    liveTransport
	config                       *Config
}
type Option func(*Client)

// wireStream is the transport-agnostic session surface; both the
// WebSocket and SageMaker bindings satisfy it.
type wireStream interface {
	Send(spectypes.ClientStream) error
	Recv() (spectypes.ServerStream, error)
	Close() error
}
type liveTransport interface {
	connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error)
}

func New(opts ...Option) *Client {
	c := &Client{apiKey: os.Getenv("DEEPGRAM_API_KEY"), accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"), baseURL: DefaultBaseURL}
	WithWebSocketTransport()(c)
	for _, opt := range opts {
		opt(c)
	}
	return c
}
func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}
func WithAPIKey(apiKey string) Option { return func(c *Client) { c.apiKey = apiKey } }
func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}
func WithBaseURL(baseURL string) Option { return func(c *Client) { c.baseURL = baseURL } }
func WithConfig(cfg *Config) Option     { return func(c *Client) { c.config = cfg } }
func (c *Client) Connect(ctx context.Context, opts *LiveTranscriptionOptions) (*Stream, error) {
	if c.transport == nil {
		WithWebSocketTransport()(c)
	}
	w, err := c.transport.connect(ctx, c, opts)
	if err != nil {
		return nil, err
	}
	stream := &Stream{transport: w}
	stream.applyConfigSendDefaults(c.config)
	return stream, nil
}

type webSocketBinding struct{}

// WithWebSocketTransport selects the default cloud WebSocket
// transport (api.deepgram.com). It is set by New; pass a
// WithSageMaker... option to override.
func WithWebSocketTransport() Option { return func(c *Client) { c.transport = webSocketBinding{} } }

func (webSocketBinding) connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error) {
	headers, err := c.authHeaders()
	if err != nil {
		return nil, err
	}
	query := liveOptionsToQuery(opts).Encode()
	dialURL := c.baseURL + streamPath
	if query != "" {
		dialURL += "?" + query
	}
	return wstransport.OpenStream[spectypes.ClientStream, spectypes.ServerStream](ctx, dialURL, headers, spectypes.MarshalClientStream, spectypes.UnmarshalServerStream)
}

func (c *Client) authHeaders() (nethttp.Header, error) {
	h := nethttp.Header{}
	switch {
	case c.accessToken != "":
		h.Set("Authorization", "Bearer "+c.accessToken)
	case c.apiKey != "":
		h.Set("Authorization", "Token "+c.apiKey)
	default:
		return nil, errors.New("listen live: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return h, nil
}

type Stream struct {
	transport    wireStream
	maxFrameSize int
	sendTimeout  time.Duration
}

func (s *Stream) SendAudio(data []byte) error {
	if s.maxFrameSize > 0 && len(data) > s.maxFrameSize {
		return fmt.Errorf("%w: %d > %d", ErrFrameTooLarge, len(data), s.maxFrameSize)
	}
	return s.transport.Send(&spectypes.ClientStreamMemberAudio{Value: spectypes.AudioFrame{Data: data}})
}
func (s *Stream) CloseStream() error {
	return s.transport.Send(&spectypes.ClientStreamMemberCloseStream{Value: spectypes.CloseStream{}})
}
func (s *Stream) SendConfigure(v spectypes.Configure) error {
	return s.transport.Send(&spectypes.ClientStreamMemberConfigure{Value: v})
}
func (s *Stream) Sync(id int64) error {
	v := id
	return s.transport.Send(&spectypes.ClientStreamMemberSync{Value: spectypes.ClientSync{Id: &v}})
}
func (s *Stream) KeepAlive() error {
	return s.transport.Send(&spectypes.ClientStreamMemberKeepAlive{Value: spectypes.KeepAlive{}})
}
func (s *Stream) Finalize(channel int) error {
	v := int32(channel)
	return s.transport.Send(&spectypes.ClientStreamMemberFinalize{Value: spectypes.Finalize{Channel: &v}})
}

// Recv returns the next server message as an idiomatic Event;
// type-switch on the *<Name>Event variants defined in events.go.
func (s *Stream) Recv() (Event, error) {
	msg, err := s.transport.Recv()
	if err != nil {
		return nil, err
	}
	return fromServerStream(msg), nil
}
func (s *Stream) Close() error { return s.transport.Close() }

func liveOptionsToQuery(o *LiveTranscriptionOptions) url.Values {
	q := optionsStructToQuery(o)
	if o != nil {
		for k, vs := range o.AdditionalQueryParams {
			q.Del(k)
			for _, v := range vs {
				q.Add(k, v)
			}
		}
	}
	return q
}
func optionsStructToQuery(opts any) url.Values {
	q := url.Values{}
	if opts == nil {
		return q
	}
	v := reflect.ValueOf(opts)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := t.Field(i)
		name := field.Tag.Get("schema")
		if name == "" || name == "-" {
			continue
		}
		if comma := stringsIndexByte(name, ','); comma >= 0 {
			name = name[:comma]
		}
		fv := v.Field(i)
		if isZeroQueryField(fv) {
			continue
		}
		addQueryField(q, name, fv)
	}
	return q
}
func stringsIndexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
func isZeroQueryField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map, reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}
func addQueryField(q url.Values, name string, v reflect.Value) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.Slice {
		for i := 0; i < v.Len(); i++ {
			addQueryField(q, name, v.Index(i))
		}
		return
	}
	switch v.Kind() {
	case reflect.String:
		q.Add(name, v.String())
	case reflect.Bool:
		q.Add(name, strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		q.Add(name, strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		q.Add(name, strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		q.Add(name, strconv.FormatFloat(v.Float(), 'g', -1, 64))
	}
}
