// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing live transcription package generated from the
// ListenLive operation. Implementation files in this directory are
// regenerated by spec-codegen-go; safety-net tests remain
// hand-authored beside them in spec-mock-go-sdk.

package livev1

import (
	"context"
	"errors"
	"fmt"
	nethttp "net/http"
	"os"
	"time"

	wstransport "github.com/deepgram/spec-mock-go-sdk/api/transport/websocket"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

const DefaultBaseURL = "wss://api.deepgram.com"
const streamPath = "/v1/listen"

type Client struct {
	apiKey, accessToken, baseURL string
	config                       *Config
	transport                    liveTransport
}
type Option func(*Client)

type wireStream interface {
	Send(spectypes.ClientStream) error
	Recv() (spectypes.ServerStream, error)
	Close() error
}
type liveTransport interface {
	connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error)
}

func New(opts ...Option) *Client {
	c := &Client{apiKey: os.Getenv("DEEPGRAM_API_KEY"), accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"), baseURL: DefaultBaseURL}
	WithWebSocketTransport()(c)
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}
func WithAPIKey(apiKey string) Option { return func(c *Client) { c.apiKey = apiKey } }
func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}
func WithBaseURL(baseURL string) Option { return func(c *Client) { c.baseURL = baseURL } }
func WithConfig(cfg *Config) Option     { return func(c *Client) { c.config = cfg } }

func (c *Client) WithBaseURL(baseURL string) *Client { out := *c; out.baseURL = baseURL; return &out }
func (c *Client) WithConfig(cfg *Config) *Client     { out := *c; out.config = cfg; return &out }

func (c *Client) Connect(ctx context.Context, opts *LiveTranscriptionOptions) (*Stream, error) {
	if c.transport == nil {
		WithWebSocketTransport()(c)
	}
	transport, err := c.transport.connect(ctx, c, opts)
	if err != nil {
		return nil, err
	}
	stream := &Stream{transport: transport}
	stream.applyConfigSendDefaults(c.config)
	return stream, nil
}

type webSocketBinding struct{}

func WithWebSocketTransport() Option { return func(c *Client) { c.transport = webSocketBinding{} } }

func (webSocketBinding) connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error) {
	headers, err := c.authHeaders()
	if err != nil {
		return nil, err
	}
	query := liveOptionsToQuery(opts).Encode()
	dialURL := c.baseURL + streamPath
	if query != "" {
		dialURL += "?" + query
	}
	return wstransport.OpenStream[spectypes.ClientStream, spectypes.ServerStream](ctx, dialURL, headers, spectypes.MarshalClientStream, spectypes.UnmarshalServerStream)
}

func (c *Client) authHeaders() (nethttp.Header, error) {
	h := nethttp.Header{}
	switch {
	case c.accessToken != "":
		h.Set("Authorization", "Bearer "+c.accessToken)
	case c.apiKey != "":
		h.Set("Authorization", "Token "+c.apiKey)
	default:
		return nil, errors.New("listen live: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return h, nil
}

type Stream struct {
	transport    wireStream
	maxFrameSize int
	sendTimeout  time.Duration
}

func (s *Stream) SendAudio(data []byte) error {
	if s.maxFrameSize > 0 && len(data) > s.maxFrameSize {
		return fmt.Errorf("%w: %d > %d", ErrFrameTooLarge, len(data), s.maxFrameSize)
	}
	return s.transport.Send(&spectypes.ClientStreamMemberAudio{Value: spectypes.AudioFrame{Data: data}})
}
func (s *Stream) CloseStream() error {
	return s.transport.Send(&spectypes.ClientStreamMemberCloseStream{Value: spectypes.CloseStream{}})
}
func (s *Stream) Finalize(channel int) error {
	v := spectypes.Finalize{}
	if channel >= 0 {
		c := int32(channel)
		v.Channel = &c
	}
	return s.transport.Send(&spectypes.ClientStreamMemberFinalize{Value: v})
}
func (s *Stream) KeepAlive() error {
	return s.transport.Send(&spectypes.ClientStreamMemberKeepAlive{Value: spectypes.KeepAlive{}})
}
func (s *Stream) Sync(id int64) error {
	return s.transport.Send(&spectypes.ClientStreamMemberSync{Value: spectypes.ClientSync{Id: &id}})
}
func (s *Stream) Recv() (Event, error) {
	msg, err := s.transport.Recv()
	if err != nil {
		return nil, err
	}
	return fromServerStream(msg), nil
}
func (s *Stream) Close() error { return s.transport.Close() }
