// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion helpers between live transcription options/events and
// generated api/types wire shapes.

package livev1

import (
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
	"net/url"
	"strconv"
)

func optionsToStreamInput(o *LiveTranscriptionOptions) *spectypes.StreamInput {
	in := &spectypes.StreamInput{}
	if o == nil {
		return in
	}
	if o.Channels != 0 {
		v := int32(o.Channels)
		in.Channels = &v
	}
	if o.Diarize {
		v := o.Diarize
		in.Diarize = &v
	}
	if o.DiarizeVersion != "" {
		v := o.DiarizeVersion
		in.DiarizeVersion = &v
	}
	if o.Encoding != "" {
		v := o.Encoding
		in.Encoding = &v
	}
	if o.Endpointing != 0 {
		v := int32(o.Endpointing)
		in.Endpointing = &v
	}
	if o.InterimResults {
		v := o.InterimResults
		in.InterimResults = &v
	}
	if len(o.Keyterm) > 0 {
		in.Keyterm = o.Keyterm
	}
	if len(o.Keywords) > 0 {
		in.Keywords = o.Keywords
	}
	if o.Language != "" {
		v := o.Language
		in.Language = &v
	}
	if o.LogData {
		v := o.LogData
		in.LogData = &v
	}
	if o.MipOptOut {
		v := o.MipOptOut
		in.MipOptOut = &v
	}
	if o.Model != "" {
		v := o.Model
		in.Model = &v
	}
	if o.Multichannel {
		v := o.Multichannel
		in.Multichannel = &v
	}
	if o.ProfanityFilter {
		v := o.ProfanityFilter
		in.ProfanityFilter = &v
	}
	if o.Punctuate {
		v := o.Punctuate
		in.Punctuate = &v
	}
	if len(o.Redact) > 0 {
		in.Redact = o.Redact
	}
	if o.SampleRate != 0 {
		v := int32(o.SampleRate)
		in.SampleRate = &v
	}
	if len(o.Search) > 0 {
		in.Search = o.Search
	}
	if o.SmartFormat {
		v := o.SmartFormat
		in.SmartFormat = &v
	}
	if len(o.Tag) > 0 {
		in.Tag = o.Tag
	}
	if o.UtteranceEndMs != 0 {
		v := int32(o.UtteranceEndMs)
		in.UtteranceEndMs = &v
	}
	if o.VadEvents {
		v := o.VadEvents
		in.VadEvents = &v
	}
	if o.VadTurnoff != 0 {
		v := int32(o.VadTurnoff)
		in.VadTurnoff = &v
	}
	if o.Version != "" {
		v := o.Version
		in.Version = &v
	}
	return in
}
func streamInputQueryString(in *spectypes.StreamInput) string {
	q := url.Values{}
	if in.Channels != nil {
		q.Set("channels", strconv.FormatInt(int64(*in.Channels), 10))
	}
	if in.Model != nil {
		q.Set("model", *in.Model)
	}
	if in.Encoding != nil {
		q.Set("encoding", *in.Encoding)
	}
	if in.SampleRate != nil {
		q.Set("sample_rate", strconv.FormatInt(int64(*in.SampleRate), 10))
	}
	if in.InterimResults != nil {
		q.Set("interim_results", strconv.FormatBool(*in.InterimResults))
	}
	for _, v := range in.Keyterm {
		q.Add("keyterm", v)
	}
	for _, v := range in.Keywords {
		q.Add("keywords", v)
	}
	return q.Encode()
}
func fromServerStream(msg spectypes.ServerStream) Event {
	switch m := msg.(type) {
	case *spectypes.ServerStreamMemberResults:
		return &ResultsEvent{}
	case *spectypes.ServerStreamMemberMetadata:
		return &MetadataEvent{}
	case *spectypes.ServerStreamMemberSpeechStarted:
		return &SpeechStartedEvent{}
	case *spectypes.ServerStreamMemberUtteranceEnd:
		return &UtteranceEndEvent{}
	case *spectypes.ServerStreamMemberError:
		return &ErrorEvent{}
	case *spectypes.ServerStreamMemberSync:
		return &SyncEvent{}
	default:
		_ = m
		return nil
	}
}
