// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Client-side live stream resilience knobs. These are SDK-only and
// are not part of the Smithy wire surface.

package livev1

import (
	"context"
	"errors"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
	"time"
)

type Config struct {
	MaxFrameSizeBytes int
	SendTimeout       time.Duration
	ReconnectPolicy   *ReconnectPolicy
}
type ReconnectPolicy struct {
	MaxAttempts    int
	InitialBackoff time.Duration
	MaxBackoff     time.Duration
}
type ReconnectEvent struct {
	Attempts        int
	BackoffApplied  time.Duration
	UnderlyingError error
}

func (*ReconnectEvent) isEvent() {}

var ErrFrameTooLarge = errors.New("listen live: audio frame exceeds Config.MaxFrameSizeBytes")
var ErrSendTimeout = errors.New("listen live: SendAudio exceeded Config.SendTimeout")

func (s *Stream) SendAudioContext(ctx context.Context, data []byte) error {
	if ctx == nil {
		return s.transport.Send(&spectypes.ClientStreamMemberAudio{Value: spectypes.AudioFrame{Data: data}})
	}
	done := make(chan error, 1)
	go func() {
		done <- s.transport.Send(&spectypes.ClientStreamMemberAudio{Value: spectypes.AudioFrame{Data: data}})
	}()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <-done:
		return err
	}
}
func (s *Stream) applyConfigSendDefaults(cfg *Config) {
	if cfg == nil {
		return
	}
	s.maxFrameSize = cfg.MaxFrameSizeBytes
	s.sendTimeout = cfg.SendTimeout
}
