// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker bidirectional transport binding for live
// transcription. The runtime wraps the AWS HTTP/2 SageMaker
// runtime client and preserves the shared Stream surface.

package livev1

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/sagemakerruntimehttp2"
	sm "github.com/deepgram/spec-mock-go-sdk/api/transport/sagemaker"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

type sageMakerBidiBinding struct {
	client             *sagemakerruntimehttp2.Client
	endpointName       string
	targetVariant      string
	targetModel        string
	inferenceID        string
	enableExplanations string
}
type SageMakerOption func(*sageMakerBidiBinding)

func WithSageMakerBidiTransport(client *sagemakerruntimehttp2.Client, endpointName string, opts ...SageMakerOption) Option {
	return func(c *Client) {
		b := sageMakerBidiBinding{client: client, endpointName: endpointName}
		for _, o := range opts {
			o(&b)
		}
		c.transport = b
	}
}
func WithTargetVariant(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.targetVariant = v }
}
func WithTargetModel(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.targetModel = v }
}
func WithInferenceID(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.inferenceID = v }
}
func WithEnableExplanations(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.enableExplanations = v }
}
func (t sageMakerBidiBinding) connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error) {
	_ = c
	_ = t.targetVariant
	_ = t.targetModel
	_ = t.inferenceID
	_ = t.enableExplanations
	query := liveOptionsToQuery(opts).Encode()
	return sm.OpenStream(ctx, t.client, t.endpointName, "v1/listen", query, spectypes.MarshalClientStream, spectypes.UnmarshalServerStream)
}
