// Code generated by spec-codegen-go. DO NOT EDIT.
//
// WebRTC transport binding for this live product. The config type
// and its defaults are modeled (see @supportsTransports webrtc);
// the signaling handshake runtime remains a stub until Deepgram
// publishes a WebRTC endpoint (ADR-0004 "future deployment modes").

package livev1

import (
	"context"

	wrtc "github.com/deepgram/spec-mock-go-sdk/api/transport/webrtc"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

// WebRTCTransportConfig is the modeled WebRTC transport contract:
// the SDP signaling endpoint, ICE servers, and the SCTP data channel
// that carries the same ClientStream/ServerStream framing as WSS.
type WebRTCTransportConfig = wrtc.Config

// DefaultWebRTCTransportConfig returns the spec-modeled defaults
// (@supportsTransports webrtc config). SignalingURL is caller-supplied.
func DefaultWebRTCTransportConfig() WebRTCTransportConfig {
	return wrtc.Config{
		SignalingURL:      "",
		SignalingProtocol: "deepgram-webrtc-v1",
		ICEServers: []wrtc.ICEServer{
			{URLs: []string{"stun:stun.l.google.com:19302"}},
		},
		DataChannel: wrtc.DataChannelConfig{Label: "deepgram-listen", Ordered: true},
	}
}

type webRTCBinding struct{ config WebRTCTransportConfig }

// WithWebRTCTransport routes the stream over WebRTC. Start from
// DefaultWebRTCTransportConfig() and set SignalingURL.
func WithWebRTCTransport(config WebRTCTransportConfig) Option {
	return func(c *Client) { c.transport = webRTCBinding{config: config} }
}
func (t webRTCBinding) connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error) {
	_ = c
	_ = opts
	return wrtc.OpenStream[spectypes.ClientStream, spectypes.ServerStream](ctx, t.config, spectypes.MarshalClientStream, spectypes.UnmarshalServerStream)
}
