// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker bidirectional transport binding for live
// transcription. The runtime is a compile-time stub today;
// AdditionalQueryParams will map to CustomAttributes once the
// AWS API exposes that path.

package livev1

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
	sm "github.com/deepgram/spec-mock-go-sdk/api/transport/sagemaker"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

type sageMakerBidiBinding struct {
	client       *sagemakerruntime.Client
	endpointName string
}

func WithSageMakerBidiTransport(client *sagemakerruntime.Client, endpointName string) Option {
	return func(c *Client) { c.transport = sageMakerBidiBinding{client: client, endpointName: endpointName} }
}
func (t sageMakerBidiBinding) connect(ctx context.Context, c *Client, opts *LiveTranscriptionOptions) (wireStream, error) {
	_ = c
	_ = opts
	_ = t.client
	return sm.OpenStream[spectypes.ClientStream, spectypes.ServerStream](ctx, t.endpointName, spectypes.MarshalClientStream, spectypes.UnmarshalServerStream)
}
