// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generated wire-test helpers shared by hand-authored package
// tests. This file marks the boundary: implementation helpers are
// generated, while *_test.go files remain human-maintained.

package livev1
