// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing REST client, generated by spec-codegen-go's
// model-driven REST facade emitter.

package readv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	nethttp "net/http"
	"net/url"
	"os"
	"strings"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

const DefaultBaseURL = "https://api.deepgram.com"

type ReadResponse = spectypes.AnalyzeOutput

type Client struct {
	apiKey, accessToken, baseURL string
	httpClient                   *nethttp.Client
}
type Option func(*Client)

func New(opts ...Option) *Client {
	c := &Client{apiKey: os.Getenv("DEEPGRAM_API_KEY"), accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"), baseURL: DefaultBaseURL, httpClient: nethttp.DefaultClient}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}
func WithAPIKey(apiKey string) Option { return func(c *Client) { c.apiKey = apiKey } }
func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}
func WithBaseURL(baseURL string) Option            { return func(c *Client) { c.baseURL = baseURL } }
func WithHTTPClient(client *nethttp.Client) Option { return func(c *Client) { c.httpClient = client } }

func (c *Client) FromText(ctx context.Context, text string, opts *ReadOptions) (*ReadResponse, error) {
	return c.invoke(ctx, opts, "text/plain", strings.NewReader(text))
}

func (c *Client) FromURL(ctx context.Context, textURL string, opts *ReadOptions) (*ReadResponse, error) {
	body, err := json.Marshal(map[string]string{"url": textURL})
	if err != nil {
		return nil, err
	}
	return c.invoke(ctx, opts, "application/json", bytes.NewReader(body))
}

func (c *Client) invoke(ctx context.Context, opts *ReadOptions, contentType string, body io.Reader) (*ReadResponse, error) {
	input := optionsToAnalyzeInput(opts)
	var additional url.Values
	if opts != nil {
		additional = opts.AdditionalQueryParams
	}
	return httptransport.Invoke[spectypes.AnalyzeInput, spectypes.AnalyzeOutput](ctx, c.httpClient, c.baseURL, spectypes.AnalyzeRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, body, additional)
}

type restAuthenticator struct{ apiKey, accessToken, contentType string }

func (a *restAuthenticator) Apply(r *nethttp.Request) error {
	if a.contentType != "" {
		r.Header.Set("Content-Type", a.contentType)
	}
	switch {
	case a.accessToken != "":
		r.Header.Set("Authorization", "Bearer "+a.accessToken)
	case a.apiKey != "":
		r.Header.Set("Authorization", "Token "+a.apiKey)
	default:
		return errors.New("read: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return nil
}
