// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion from generated wire types to the idiomatic response
// structs. Deref helpers turn optional wire pointers into plain
// values so customers never nil-check a primitive.

package readv1

import spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}
func derefBool(p *bool) bool {
	if p == nil {
		return false
	}
	return *p
}
func derefInt32(p *int32) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefInt64(p *int64) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefF32(p *float32) float64 {
	if p == nil {
		return 0
	}
	return float64(*p)
}
func derefF64(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p
}

func convertAnalyzeOutput(in *spectypes.AnalyzeOutput) *AnalyzeOutput {
	if in == nil {
		return nil
	}
	out := &AnalyzeOutput{}
	out.Metadata = convertReadMetadata(in.Metadata)
	out.RequestID = derefStr(in.RequestId)
	out.Results = convertReadResults(in.Results)
	return out
}

func convertIntent(in *spectypes.Intent) *Intent {
	if in == nil {
		return nil
	}
	out := &Intent{}
	out.ConfidenceScore = derefF32(in.ConfidenceScore)
	out.Intent = derefStr(in.Intent)
	return out
}

func convertIntentSegment(in *spectypes.IntentSegment) *IntentSegment {
	if in == nil {
		return nil
	}
	out := &IntentSegment{}
	out.EndWord = derefInt32(in.EndWord)
	if in.Intents != nil {
		out.Intents = make([]Intent, 0, len(in.Intents))
		for i := range in.Intents {
			if c := convertIntent(&in.Intents[i]); c != nil {
				out.Intents = append(out.Intents, *c)
			}
		}
	}
	out.StartWord = derefInt32(in.StartWord)
	out.Text = derefStr(in.Text)
	return out
}

func convertIntentsResult(in *spectypes.IntentsResult) *IntentsResult {
	if in == nil {
		return nil
	}
	out := &IntentsResult{}
	if in.Segments != nil {
		out.Segments = make([]IntentSegment, 0, len(in.Segments))
		for i := range in.Segments {
			if c := convertIntentSegment(&in.Segments[i]); c != nil {
				out.Segments = append(out.Segments, *c)
			}
		}
	}
	return out
}

func convertReadAverageSentiment(in *spectypes.ReadAverageSentiment) *ReadAverageSentiment {
	if in == nil {
		return nil
	}
	out := &ReadAverageSentiment{}
	out.EndTime = derefF32(in.EndTime)
	out.Sentiment = string(in.Sentiment)
	out.SentimentScore = derefF32(in.SentimentScore)
	out.StartTime = derefF32(in.StartTime)
	return out
}

func convertReadMetadata(in *spectypes.ReadMetadata) *ReadMetadata {
	if in == nil {
		return nil
	}
	out := &ReadMetadata{}
	out.Created = derefStr(in.Created)
	out.IntentsInfo = convertTokenMetadata(in.IntentsInfo)
	out.Language = derefStr(in.Language)
	out.RequestID = derefStr(in.RequestId)
	out.SentimentInfo = convertTokenMetadata(in.SentimentInfo)
	out.SummaryInfo = convertTokenMetadata(in.SummaryInfo)
	out.Tags = in.Tags
	out.TopicsInfo = convertTokenMetadata(in.TopicsInfo)
	return out
}

func convertReadResults(in *spectypes.ReadResults) *ReadResults {
	if in == nil {
		return nil
	}
	out := &ReadResults{}
	out.Intents = convertIntentsResult(in.Intents)
	out.Sentiments = convertSentimentsResult(in.Sentiments)
	out.Summary = convertSummaryResult(in.Summary)
	out.Topics = convertTopicsResult(in.Topics)
	return out
}

func convertSentimentsResult(in *spectypes.SentimentsResult) *SentimentsResult {
	if in == nil {
		return nil
	}
	out := &SentimentsResult{}
	out.Average = convertReadAverageSentiment(in.Average)
	if in.Segments != nil {
		out.Segments = make([]SitSentimentSegment, 0, len(in.Segments))
		for i := range in.Segments {
			if c := convertSitSentimentSegment(&in.Segments[i]); c != nil {
				out.Segments = append(out.Segments, *c)
			}
		}
	}
	return out
}

func convertSitSentimentSegment(in *spectypes.SitSentimentSegment) *SitSentimentSegment {
	if in == nil {
		return nil
	}
	out := &SitSentimentSegment{}
	out.EndWord = derefInt32(in.EndWord)
	out.Sentiment = string(in.Sentiment)
	out.SentimentScore = derefF32(in.SentimentScore)
	out.StartWord = derefInt32(in.StartWord)
	out.Text = derefStr(in.Text)
	return out
}

func convertSummaryResult(in *spectypes.SummaryResult) *SummaryResult {
	if in == nil {
		return nil
	}
	out := &SummaryResult{}
	out.Text = derefStr(in.Text)
	return out
}

func convertTokenMetadata(in *spectypes.TokenMetadata) *TokenMetadata {
	if in == nil {
		return nil
	}
	out := &TokenMetadata{}
	out.InputTokens = derefInt64(in.InputTokens)
	out.Model = derefStr(in.Model)
	out.ModelUUID = derefStr(in.ModelUuid)
	out.OutputTokens = derefInt64(in.OutputTokens)
	return out
}

func convertTopic(in *spectypes.Topic) *Topic {
	if in == nil {
		return nil
	}
	out := &Topic{}
	out.ConfidenceScore = derefF32(in.ConfidenceScore)
	out.Topic = derefStr(in.Topic)
	return out
}

func convertTopicSegment(in *spectypes.TopicSegment) *TopicSegment {
	if in == nil {
		return nil
	}
	out := &TopicSegment{}
	out.EndWord = derefInt32(in.EndWord)
	out.StartWord = derefInt32(in.StartWord)
	out.Text = derefStr(in.Text)
	if in.Topics != nil {
		out.Topics = make([]Topic, 0, len(in.Topics))
		for i := range in.Topics {
			if c := convertTopic(&in.Topics[i]); c != nil {
				out.Topics = append(out.Topics, *c)
			}
		}
	}
	return out
}

func convertTopicsResult(in *spectypes.TopicsResult) *TopicsResult {
	if in == nil {
		return nil
	}
	out := &TopicsResult{}
	if in.Segments != nil {
		out.Segments = make([]TopicSegment, 0, len(in.Segments))
		for i := range in.Segments {
			if c := convertTopicSegment(&in.Segments[i]); c != nil {
				out.Segments = append(out.Segments, *c)
			}
		}
	}
	return out
}
