// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing, value-typed response structs with idiomatic Go
// field names. Generated from the operations' output shapes; the
// conversion from the generated wire types lives in
// convert_output.go.

package readv1

type AnalyzeOutput struct {
	Metadata  *ReadMetadata `json:"metadata,omitempty"`
	RequestID string        `json:"request_id,omitempty"`
	Results   *ReadResults  `json:"results,omitempty"`
}

type Intent struct {
	ConfidenceScore float64 `json:"confidence_score,omitempty"`
	Intent          string  `json:"intent,omitempty"`
}

type IntentSegment struct {
	EndWord   int      `json:"end_word,omitempty"`
	Intents   []Intent `json:"intents,omitempty"`
	StartWord int      `json:"start_word,omitempty"`
	Text      string   `json:"text,omitempty"`
}

type IntentsResult struct {
	Segments []IntentSegment `json:"segments,omitempty"`
}

type ReadAverageSentiment struct {
	EndTime        float64 `json:"end_time,omitempty"`
	Sentiment      string  `json:"sentiment,omitempty"`
	SentimentScore float64 `json:"sentiment_score,omitempty"`
	StartTime      float64 `json:"start_time,omitempty"`
}

type ReadMetadata struct {
	Created       string         `json:"created,omitempty"`
	IntentsInfo   *TokenMetadata `json:"intents_info,omitempty"`
	Language      string         `json:"language,omitempty"`
	RequestID     string         `json:"request_id,omitempty"`
	SentimentInfo *TokenMetadata `json:"sentiment_info,omitempty"`
	SummaryInfo   *TokenMetadata `json:"summary_info,omitempty"`
	Tags          []string       `json:"tags,omitempty"`
	TopicsInfo    *TokenMetadata `json:"topics_info,omitempty"`
}

type ReadResults struct {
	Intents    *IntentsResult    `json:"intents,omitempty"`
	Sentiments *SentimentsResult `json:"sentiments,omitempty"`
	Summary    *SummaryResult    `json:"summary,omitempty"`
	Topics     *TopicsResult     `json:"topics,omitempty"`
}

type SentimentsResult struct {
	Average  *ReadAverageSentiment `json:"average,omitempty"`
	Segments []SitSentimentSegment `json:"segments,omitempty"`
}

type SitSentimentSegment struct {
	EndWord        int     `json:"end_word,omitempty"`
	Sentiment      string  `json:"sentiment,omitempty"`
	SentimentScore float64 `json:"sentiment_score,omitempty"`
	StartWord      int     `json:"start_word,omitempty"`
	Text           string  `json:"text,omitempty"`
}

type SummaryResult struct {
	Text string `json:"text,omitempty"`
}

type TokenMetadata struct {
	InputTokens  int    `json:"input_tokens,omitempty"`
	Model        string `json:"model,omitempty"`
	ModelUUID    string `json:"model_uuid,omitempty"`
	OutputTokens int    `json:"output_tokens,omitempty"`
}

type Topic struct {
	ConfidenceScore float64 `json:"confidence_score,omitempty"`
	Topic           string  `json:"topic,omitempty"`
}

type TopicSegment struct {
	EndWord   int     `json:"end_word,omitempty"`
	StartWord int     `json:"start_word,omitempty"`
	Text      string  `json:"text,omitempty"`
	Topics    []Topic `json:"topics,omitempty"`
}

type TopicsResult struct {
	Segments []TopicSegment `json:"segments,omitempty"`
}
