// Code generated by spec-codegen-go. DO NOT EDIT.
//
// HTTP route metadata for the AgentSettings service. Each *Route
// value captures the @http binding for one operation: method, URI
// path, and FieldBindings naming the input struct fields that bind
// to query / header / path parameters via @httpQuery / @httpHeader
// / @httpLabel traits. PayloadField names the single member (if
// any) carrying the request body via @httpPayload.
//
// DecodeError on each *Route, when non-nil, is a per-operation
// decoder that maps a non-2xx response into one of the
// operation's declared @error structures (smithy-go-generated,
// in this same package). Customer code reaches the typed error
// via errors.As(httpErr.Typed, &target).
//
// These values feed transport/http.Invoke[I, O any] which uses
// reflection on the named fields to assemble *http.Request objects.

package types

import (
	"encoding/json"

	nethttp "net/http"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
)

// decodeListThinkProvidersError matches a non-2xx response to one of ListThinkProviders's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListThinkProvidersError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListThinkProvidersRoute describes the HTTP binding for the ListThinkProviders operation.
var ListThinkProvidersRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/agent/settings/think/providers",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Include", WireName: "include"},
	},
	DecodeError: decodeListThinkProvidersError,
}

// decodeGetThinkProviderError matches a non-2xx response to one of GetThinkProvider's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetThinkProviderError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetThinkProviderRoute describes the HTTP binding for the GetThinkProvider operation.
var GetThinkProviderRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/agent/settings/think/providers/{provider}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Provider", WireName: "provider"},
	},
	DecodeError: decodeGetThinkProviderError,
}

// decodeListThinkModelsError matches a non-2xx response to one of ListThinkModels's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListThinkModelsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListThinkModelsRoute describes the HTTP binding for the ListThinkModels operation.
var ListThinkModelsRoute = httptransport.HTTPRoute{
	Method:      "GET",
	Path:        "/v1/agent/settings/think/models",
	DecodeError: decodeListThinkModelsError,
}

// decodeListProviderModelsError matches a non-2xx response to one of ListProviderModels's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProviderModelsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProviderModelsRoute describes the HTTP binding for the ListProviderModels operation.
var ListProviderModelsRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/agent/settings/think/providers/{provider}/models",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Provider", WireName: "provider"},
	},
	DecodeError: decodeListProviderModelsError,
}

// decodeValidateSettingsError matches a non-2xx response to one of ValidateSettings's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeValidateSettingsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ValidateSettingsRoute describes the HTTP binding for the ValidateSettings operation.
var ValidateSettingsRoute = httptransport.HTTPRoute{
	Method:       "POST",
	Path:         "/v1/agent/settings/validate",
	PayloadField: "Settings",
	DecodeError:  decodeValidateSettingsError,
}

// decodeValidateAgentError matches a non-2xx response to one of ValidateAgent's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeValidateAgentError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ValidateAgentRoute describes the HTTP binding for the ValidateAgent operation.
var ValidateAgentRoute = httptransport.HTTPRoute{
	Method:       "POST",
	Path:         "/v1/agent/settings/agent/validate",
	PayloadField: "Agent",
	DecodeError:  decodeValidateAgentError,
}
