// Code generated by spec-codegen-go. DO NOT EDIT.
//
// HTTP route metadata for the Auth service. Each *Route
// value captures the @http binding for one operation: method, URI
// path, and FieldBindings naming the input struct fields that bind
// to query / header / path parameters via @httpQuery / @httpHeader
// / @httpLabel traits. PayloadField names the single member (if
// any) carrying the request body via @httpPayload.
//
// DecodeError on each *Route, when non-nil, is a per-operation
// decoder that maps a non-2xx response into one of the
// operation's declared @error structures (smithy-go-generated,
// in this same package). Customer code reaches the typed error
// via errors.As(httpErr.Typed, &target).
//
// These values feed transport/http.Invoke[I, O any] which uses
// reflection on the named fields to assemble *http.Request objects.

package types

import (
	"encoding/json"

	nethttp "net/http"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
)

// decodeGrantTokenError matches a non-2xx response to one of GrantToken's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGrantTokenError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GrantTokenRoute describes the HTTP binding for the GrantToken operation.
var GrantTokenRoute = httptransport.HTTPRoute{
	Method:       "POST",
	Path:         "/v1/auth/grant",
	PayloadField: "Body",
	DecodeError:  decodeGrantTokenError,
}
