// Code generated by smithy-go-codegen DO NOT EDIT.


package types

type Sentiment string

// Enum values for Sentiment
const (
	SentimentPositive Sentiment = "positive"
	SentimentNeutral Sentiment = "neutral"
	SentimentNegative Sentiment = "negative"
)

// Values returns all known values for Sentiment. Note that this can be expanded
// in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (Sentiment) Values() []Sentiment {
	return []Sentiment{
		"positive",
		"neutral",
		"negative",
	}
}

type WarningType string

// Enum values for WarningType
const (
	WarningTypeUnsupportedLanguage WarningType = "UNSUPPORTED_LANGUAGE"
	WarningTypeUnsupportedModel WarningType = "UNSUPPORTED_MODEL"
	WarningTypeUnsupportedEncoding WarningType = "UNSUPPORTED_ENCODING"
	WarningTypeDeprecated WarningType = "DEPRECATED"
)

// Values returns all known values for WarningType. Note that this can be expanded
// in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (WarningType) Values() []WarningType {
	return []WarningType{
		"UNSUPPORTED_LANGUAGE",
		"UNSUPPORTED_MODEL",
		"UNSUPPORTED_ENCODING",
		"DEPRECATED",
	}
}

type CallbackMethod string

// Enum values for CallbackMethod
const (
	CallbackMethodPost CallbackMethod = "POST"
	CallbackMethodPut CallbackMethod = "PUT"
)

// Values returns all known values for CallbackMethod. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (CallbackMethod) Values() []CallbackMethod {
	return []CallbackMethod{
		"POST",
		"PUT",
	}
}

type Chunker string

// Enum values for Chunker
const (
	ChunkerBatch Chunker = "batch"
	ChunkerStreaming Chunker = "streaming"
)

// Values returns all known values for Chunker. Note that this can be expanded in
// the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (Chunker) Values() []Chunker {
	return []Chunker{
		"batch",
		"streaming",
	}
}

type KeywordBoost string

// Enum values for KeywordBoost
const (
	// Boost + post-search for out-of-vocabulary keywords. Default.
	KeywordBoostStandard KeywordBoost = "standard"
	// Apply boosting only to in-vocabulary terms (no post-search).
	KeywordBoostLegacy KeywordBoost = "legacy"
)

// Values returns all known values for KeywordBoost. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (KeywordBoost) Values() []KeywordBoost {
	return []KeywordBoost{
		"standard",
		"legacy",
	}
}

type SummaryLength string

// Enum values for SummaryLength
const (
	SummaryLengthShort SummaryLength = "short"
	SummaryLengthMedium SummaryLength = "medium"
	SummaryLengthLong SummaryLength = "long"
)

// Values returns all known values for SummaryLength. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (SummaryLength) Values() []SummaryLength {
	return []SummaryLength{
		"short",
		"medium",
		"long",
	}
}

type WsErrorVariant string

// Enum values for WsErrorVariant
const (
	// Session is being closed by the server. Will be followed by a WS close frame.
	// Only emitted when ?debug=true .
	WsErrorVariantClosing WsErrorVariant = "Closing"
	// Client sent malformed JSON. Server keeps the session open.
	WsErrorVariantSchemaError WsErrorVariant = "SchemaError"
)

// Values returns all known values for WsErrorVariant. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (WsErrorVariant) Values() []WsErrorVariant {
	return []WsErrorVariant{
		"Closing",
		"SchemaError",
	}
}
