// Code generated by smithy-go-codegen DO NOT EDIT.

package types

type Sentiment string

// Enum values for Sentiment
const (
	SentimentPositive Sentiment = "positive"
	SentimentNeutral  Sentiment = "neutral"
	SentimentNegative Sentiment = "negative"
)

// Values returns all known values for Sentiment. Note that this can be expanded
// in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (Sentiment) Values() []Sentiment {
	return []Sentiment{
		"positive",
		"neutral",
		"negative",
	}
}

type CallbackMethod string

// Enum values for CallbackMethod
const (
	CallbackMethodPost CallbackMethod = "POST"
	CallbackMethodPut  CallbackMethod = "PUT"
)

// Values returns all known values for CallbackMethod. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (CallbackMethod) Values() []CallbackMethod {
	return []CallbackMethod{
		"POST",
		"PUT",
	}
}

type WarningType string

// Enum values for WarningType
const (
	WarningTypeUnsupportedLanguage WarningType = "UNSUPPORTED_LANGUAGE"
	WarningTypeUnsupportedModel    WarningType = "UNSUPPORTED_MODEL"
	WarningTypeUnsupportedEncoding WarningType = "UNSUPPORTED_ENCODING"
	WarningTypeDeprecated          WarningType = "DEPRECATED"
)

// Values returns all known values for WarningType. Note that this can be expanded
// in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (WarningType) Values() []WarningType {
	return []WarningType{
		"UNSUPPORTED_LANGUAGE",
		"UNSUPPORTED_MODEL",
		"UNSUPPORTED_ENCODING",
		"DEPRECATED",
	}
}

type WsErrorVariant string

// Enum values for WsErrorVariant
const (
	// Session is being closed by the server. Will be followed by a WS close frame.
	// Only emitted when ?debug=true .
	WsErrorVariantClosing WsErrorVariant = "Closing"
	// Client sent malformed JSON. Server keeps the session open.
	WsErrorVariantSchemaError WsErrorVariant = "SchemaError"
)

// Values returns all known values for WsErrorVariant. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (WsErrorVariant) Values() []WsErrorVariant {
	return []WsErrorVariant{
		"Closing",
		"SchemaError",
	}
}

type SpeakContainer string

// Enum values for SpeakContainer
const (
	SpeakContainerWav  SpeakContainer = "wav"
	SpeakContainerNone SpeakContainer = "none"
	SpeakContainerOgg  SpeakContainer = "ogg"
)

// Values returns all known values for SpeakContainer. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (SpeakContainer) Values() []SpeakContainer {
	return []SpeakContainer{
		"wav",
		"none",
		"ogg",
	}
}

type SpeakEncoding string

// Enum values for SpeakEncoding
const (
	SpeakEncodingLinear16 SpeakEncoding = "linear16"
	SpeakEncodingMulaw    SpeakEncoding = "mulaw"
	SpeakEncodingAlaw     SpeakEncoding = "alaw"
	SpeakEncodingMp3      SpeakEncoding = "mp3"
	SpeakEncodingOpus     SpeakEncoding = "opus"
	SpeakEncodingFlac     SpeakEncoding = "flac"
	SpeakEncodingAac      SpeakEncoding = "aac"
)

// Values returns all known values for SpeakEncoding. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (SpeakEncoding) Values() []SpeakEncoding {
	return []SpeakEncoding{
		"linear16",
		"mulaw",
		"alaw",
		"mp3",
		"opus",
		"flac",
		"aac",
	}
}

type SpeakTimestampEvent string

// Enum values for SpeakTimestampEvent
const (
	SpeakTimestampEventUpgradedWebsocketConnection SpeakTimestampEvent = "UpgradedWebSocketConnection"
	SpeakTimestampEventReceivedFirstInputText      SpeakTimestampEvent = "ReceivedFirstInputText"
	SpeakTimestampEventReceivedFirstSentence       SpeakTimestampEvent = "ReceivedFirstSentence"
	SpeakTimestampEventRequestedFirstAudioChunk    SpeakTimestampEvent = "RequestedFirstAudioChunk"
	SpeakTimestampEventReceivedFirstAudioChunk     SpeakTimestampEvent = "ReceivedFirstAudioChunk"
)

// Values returns all known values for SpeakTimestampEvent. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (SpeakTimestampEvent) Values() []SpeakTimestampEvent {
	return []SpeakTimestampEvent{
		"UpgradedWebSocketConnection",
		"ReceivedFirstInputText",
		"ReceivedFirstSentence",
		"RequestedFirstAudioChunk",
		"ReceivedFirstAudioChunk",
	}
}
