// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Defines the noSmithyDocumentSerde marker that smithy-go-generated
// shape types embed. ShapeCodegenPlugin omits this helper because
// it's normally written by ProtocolDocumentGenerator during full
// client codegen; without it the types package fails to compile.


package types

import smithydocument "github.com/aws/smithy-go/document"

type noSmithyDocumentSerde = smithydocument.NoSerde
