// Code generated by spec-codegen-go. DO NOT EDIT.
//
// HTTP route metadata for the Listen service. Each *Route
// value captures the @http binding for one operation: method, URI
// path, and FieldBindings naming the input struct fields that bind
// to query / header / path parameters via @httpQuery / @httpHeader
// / @httpLabel traits. PayloadField names the single member (if
// any) carrying the request body via @httpPayload.
//
// These values feed transport/http.Invoke[I, O any] which uses
// reflection on the named fields to assemble *http.Request objects.

package types

import httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"

// TranscribeRoute describes the HTTP binding for the Transcribe operation.
var TranscribeRoute = httptransport.HTTPRoute{
	Method: "POST",
	Path:   "/v1/listen",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Callback", WireName: "callback"},
		{GoField: "CallbackMethod", WireName: "callback_method"},
		{GoField: "Model", WireName: "model"},
		{GoField: "Language", WireName: "language"},
		{GoField: "Version", WireName: "version"},
		{GoField: "Tier", WireName: "tier"},
		{GoField: "Punctuate", WireName: "punctuate"},
		{GoField: "Diarize", WireName: "diarize"},
		{GoField: "DiarizeVersion", WireName: "diarize_version"},
		{GoField: "DiarizeModel", WireName: "diarize_model"},
		{GoField: "VadTurnoff", WireName: "vad_turnoff"},
		{GoField: "SmartFormat", WireName: "smart_format"},
		{GoField: "Utterances", WireName: "utterances"},
		{GoField: "Paragraphs", WireName: "paragraphs"},
		{GoField: "Multichannel", WireName: "multichannel"},
		{GoField: "Redact", WireName: "redact"},
		{GoField: "Keywords", WireName: "keywords"},
		{GoField: "Keyterm", WireName: "keyterm"},
		{GoField: "Search", WireName: "search"},
		{GoField: "Replace", WireName: "replace"},
		{GoField: "Tag", WireName: "tag"},
		{GoField: "Encoding", WireName: "encoding"},
		{GoField: "SampleRate", WireName: "sample_rate"},
		{GoField: "Channels", WireName: "channels"},
		{GoField: "FillerWords", WireName: "filler_words"},
		{GoField: "ProfanityFilter", WireName: "profanity_filter"},
		{GoField: "Sentiment", WireName: "sentiment"},
		{GoField: "Topics", WireName: "topics"},
		{GoField: "Intents", WireName: "intents"},
		{GoField: "Summarize", WireName: "summarize"},
		{GoField: "DetectEntities", WireName: "detect_entities"},
		{GoField: "DetectLanguage", WireName: "detect_language"},
		{GoField: "MipOptOut", WireName: "mip_opt_out"},
		{GoField: "LogData", WireName: "log_data"},
		{GoField: "Alternatives", WireName: "alternatives"},
		{GoField: "Numerals", WireName: "numerals"},
		{GoField: "MaxSpeakers", WireName: "max_speakers"},
		{GoField: "Endpointing", WireName: "endpointing"},
		{GoField: "VadTurnon", WireName: "vad_turnon"},
		{GoField: "VadSuppression", WireName: "vad_suppression"},
		{GoField: "VadEvents", WireName: "vad_events"},
		{GoField: "Chunker", WireName: "chunker"},
		{GoField: "EmulateStreaming", WireName: "emulate_streaming"},
		{GoField: "Identify", WireName: "identify"},
		{GoField: "UnifySpeakerId", WireName: "unify_speaker_id"},
		{GoField: "Dates", WireName: "dates"},
		{GoField: "DateFormat", WireName: "date_format"},
		{GoField: "Dictation", WireName: "dictation"},
		{GoField: "Measurements", WireName: "measurements"},
		{GoField: "Numbers", WireName: "numbers"},
		{GoField: "NumbersSpaces", WireName: "numbers_spaces"},
		{GoField: "Times", WireName: "times"},
		{GoField: "SummarizeLength", WireName: "summarize_length"},
		{GoField: "Threshold", WireName: "threshold"},
		{GoField: "KeywordBoost", WireName: "keyword_boost"},
		{GoField: "ShowRedactedText", WireName: "show_redacted_text"},
		{GoField: "EntityPrompt", WireName: "entity_prompt"},
		{GoField: "Ner", WireName: "ner"},
		{GoField: "Yelling", WireName: "YELLING"},
		{GoField: "Uttseg", WireName: "uttseg"},
		{GoField: "UttSplit", WireName: "utt_split"},
		{GoField: "UttSplitInterruptions", WireName: "utt_split_interruptions"},
		{GoField: "Performance", WireName: "performance"},
		{GoField: "Context", WireName: "context"},
		{GoField: "DatasetId", WireName: "dataset-id"},
		{GoField: "Name", WireName: "name"},
	},
	HeaderFields: []httptransport.FieldBinding{
		{GoField: "ContentType", WireName: "Content-Type"},
	},
	PayloadField: "Body",
}

