// Code generated by spec-codegen-go. DO NOT EDIT.
//
// HTTP route metadata for the Listen service. Each *Route
// value captures the @http binding for one operation: method, URI
// path, and FieldBindings naming the input struct fields that bind
// to query / header / path parameters via @httpQuery / @httpHeader
// / @httpLabel traits. PayloadField names the single member (if
// any) carrying the request body via @httpPayload.
//
// These values feed transport/http.Invoke[I, O any] which uses
// reflection on the named fields to assemble *http.Request objects.

package types

import httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"

// TranscribeRoute describes the HTTP binding for the Transcribe operation.
var TranscribeRoute = httptransport.HTTPRoute{
	Method: "POST",
	Path:   "/v1/listen",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Callback", WireName: "callback"},
		{GoField: "CallbackMethod", WireName: "callback_method"},
		{GoField: "Model", WireName: "model"},
		{GoField: "Language", WireName: "language"},
		{GoField: "Version", WireName: "version"},
		{GoField: "Punctuate", WireName: "punctuate"},
		{GoField: "Diarize", WireName: "diarize"},
		{GoField: "DiarizeVersion", WireName: "diarize_version"},
		{GoField: "DiarizeModel", WireName: "diarize_model"},
		{GoField: "VadTurnoff", WireName: "vad_turnoff"},
		{GoField: "SmartFormat", WireName: "smart_format"},
		{GoField: "Utterances", WireName: "utterances"},
		{GoField: "Paragraphs", WireName: "paragraphs"},
		{GoField: "Multichannel", WireName: "multichannel"},
		{GoField: "Redact", WireName: "redact"},
		{GoField: "Keywords", WireName: "keywords"},
		{GoField: "Keyterm", WireName: "keyterm"},
		{GoField: "Search", WireName: "search"},
		{GoField: "Replace", WireName: "replace"},
		{GoField: "Tag", WireName: "tag"},
		{GoField: "Encoding", WireName: "encoding"},
		{GoField: "FillerWords", WireName: "filler_words"},
		{GoField: "ProfanityFilter", WireName: "profanity_filter"},
		{GoField: "Sentiment", WireName: "sentiment"},
		{GoField: "Topics", WireName: "topics"},
		{GoField: "Intents", WireName: "intents"},
		{GoField: "Summarize", WireName: "summarize"},
		{GoField: "DetectEntities", WireName: "detect_entities"},
		{GoField: "DetectLanguage", WireName: "detect_language"},
		{GoField: "MipOptOut", WireName: "mip_opt_out"},
		{GoField: "LogData", WireName: "log_data"},
		{GoField: "Numerals", WireName: "numerals"},
		{GoField: "Dictation", WireName: "dictation"},
		{GoField: "Measurements", WireName: "measurements"},
		{GoField: "UttSplit", WireName: "utt_split"},
	},
	HeaderFields: []httptransport.FieldBinding{
		{GoField: "ContentType", WireName: "Content-Type"},
	},
	PayloadField: "Body",
}

