// Code generated by spec-codegen-go. DO NOT EDIT.
//
// HTTP route metadata for the %SERVICE_NAME% service. Each *Route
// value captures the @http binding for one operation: method, URI
// path, and FieldBindings naming the input struct fields that bind
// to query / header / path parameters via @httpQuery / @httpHeader
// / @httpLabel traits. PayloadField names the single member (if
// any) carrying the request body via @httpPayload.
//
// DecodeError on each *Route, when non-nil, is a per-operation
// decoder that maps a non-2xx response into one of the
// operation's declared @error structures (smithy-go-generated,
// in this same package). Customer code reaches the typed error
// via errors.As(httpErr.Typed, &target).
//
// These values feed transport/http.Invoke[I, O any] which uses
// reflection on the named fields to assemble *http.Request objects.


package types

import (
	"encoding/json"

	nethttp "net/http"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
)

// decodeTranscribeError matches a non-2xx response to one of Transcribe's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeTranscribeError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 402:
		v := &PaymentRequiredError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 408:
		v := &SlowUploadError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 413:
		v := &PayloadTooLargeError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 415:
		v := &UnsupportedMediaTypeError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 429:
		v := &RateLimitedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		if h := headers.Get("Retry-After"); h != "" {
			hCopy := h
			v.RetryAfter = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// TranscribeRoute describes the HTTP binding for the Transcribe operation.
var TranscribeRoute = httptransport.HTTPRoute{
	Method: "POST",
	Path:   "/v1/listen",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Callback", WireName: "callback"},
		{GoField: "CallbackMethod", WireName: "callback_method"},
		{GoField: "Model", WireName: "model"},
		{GoField: "Language", WireName: "language"},
		{GoField: "Version", WireName: "version"},
		{GoField: "Punctuate", WireName: "punctuate"},
		{GoField: "Diarize", WireName: "diarize"},
		{GoField: "DiarizeVersion", WireName: "diarize_version"},
		{GoField: "DiarizeModel", WireName: "diarize_model"},
		{GoField: "VadTurnoff", WireName: "vad_turnoff"},
		{GoField: "SmartFormat", WireName: "smart_format"},
		{GoField: "Utterances", WireName: "utterances"},
		{GoField: "Paragraphs", WireName: "paragraphs"},
		{GoField: "Multichannel", WireName: "multichannel"},
		{GoField: "Redact", WireName: "redact"},
		{GoField: "Keywords", WireName: "keywords"},
		{GoField: "Keyterm", WireName: "keyterm"},
		{GoField: "Search", WireName: "search"},
		{GoField: "Replace", WireName: "replace"},
		{GoField: "Tag", WireName: "tag"},
		{GoField: "Encoding", WireName: "encoding"},
		{GoField: "FillerWords", WireName: "filler_words"},
		{GoField: "ProfanityFilter", WireName: "profanity_filter"},
		{GoField: "Sentiment", WireName: "sentiment"},
		{GoField: "Topics", WireName: "topics"},
		{GoField: "Intents", WireName: "intents"},
		{GoField: "Summarize", WireName: "summarize"},
		{GoField: "DetectEntities", WireName: "detect_entities"},
		{GoField: "DetectLanguage", WireName: "detect_language"},
		{GoField: "MipOptOut", WireName: "mip_opt_out"},
		{GoField: "LogData", WireName: "log_data"},
		{GoField: "Numerals", WireName: "numerals"},
		{GoField: "Dictation", WireName: "dictation"},
		{GoField: "Measurements", WireName: "measurements"},
		{GoField: "UttSplit", WireName: "utt_split"},
	},
	HeaderFields: []httptransport.FieldBinding{
		{GoField: "ContentType", WireName: "Content-Type"},
	},
	PayloadField: "Body",
	DecodeError: decodeTranscribeError,
}

