// Code generated by spec-codegen-go. DO NOT EDIT.
//
// HTTP route metadata for the Manage service. Each *Route
// value captures the @http binding for one operation: method, URI
// path, and FieldBindings naming the input struct fields that bind
// to query / header / path parameters via @httpQuery / @httpHeader
// / @httpLabel traits. PayloadField names the single member (if
// any) carrying the request body via @httpPayload.
//
// DecodeError on each *Route, when non-nil, is a per-operation
// decoder that maps a non-2xx response into one of the
// operation's declared @error structures (smithy-go-generated,
// in this same package). Customer code reaches the typed error
// via errors.As(httpErr.Typed, &target).
//
// These values feed transport/http.Invoke[I, O any] which uses
// reflection on the named fields to assemble *http.Request objects.

package types

import (
	"encoding/json"

	nethttp "net/http"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
)

// decodeListProjectsError matches a non-2xx response to one of ListProjects's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectsRoute describes the HTTP binding for the ListProjects operation.
var ListProjectsRoute = httptransport.HTTPRoute{
	Method:      "GET",
	Path:        "/v1/projects",
	DecodeError: decodeListProjectsError,
}

// decodeGetProjectError matches a non-2xx response to one of GetProject's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetProjectError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetProjectRoute describes the HTTP binding for the GetProject operation.
var GetProjectRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Limit", WireName: "limit"},
		{GoField: "Page", WireName: "page"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeGetProjectError,
}

// decodeUpdateProjectError matches a non-2xx response to one of UpdateProject's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeUpdateProjectError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// UpdateProjectRoute describes the HTTP binding for the UpdateProject operation.
var UpdateProjectRoute = httptransport.HTTPRoute{
	Method: "PATCH",
	Path:   "/v1/projects/{project_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	PayloadField: "Body",
	DecodeError:  decodeUpdateProjectError,
}

// decodeDeleteProjectError matches a non-2xx response to one of DeleteProject's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeDeleteProjectError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// DeleteProjectRoute describes the HTTP binding for the DeleteProject operation.
var DeleteProjectRoute = httptransport.HTTPRoute{
	Method: "DELETE",
	Path:   "/v1/projects/{project_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeDeleteProjectError,
}

// decodeLeaveProjectError matches a non-2xx response to one of LeaveProject's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeLeaveProjectError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// LeaveProjectRoute describes the HTTP binding for the LeaveProject operation.
var LeaveProjectRoute = httptransport.HTTPRoute{
	Method: "DELETE",
	Path:   "/v1/projects/{project_id}/leave",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeLeaveProjectError,
}

// decodeListProjectKeysError matches a non-2xx response to one of ListProjectKeys's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectKeysError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectKeysRoute describes the HTTP binding for the ListProjectKeys operation.
var ListProjectKeysRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/keys",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Status", WireName: "status"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectKeysError,
}

// decodeCreateProjectKeyError matches a non-2xx response to one of CreateProjectKey's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeCreateProjectKeyError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// CreateProjectKeyRoute describes the HTTP binding for the CreateProjectKey operation.
var CreateProjectKeyRoute = httptransport.HTTPRoute{
	Method: "POST",
	Path:   "/v1/projects/{project_id}/keys",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	PayloadField: "Body",
	DecodeError:  decodeCreateProjectKeyError,
}

// decodeGetProjectKeyError matches a non-2xx response to one of GetProjectKey's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetProjectKeyError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetProjectKeyRoute describes the HTTP binding for the GetProjectKey operation.
var GetProjectKeyRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/keys/{key_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Key_id", WireName: "key_id"},
	},
	DecodeError: decodeGetProjectKeyError,
}

// decodeDeleteProjectKeyError matches a non-2xx response to one of DeleteProjectKey's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeDeleteProjectKeyError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// DeleteProjectKeyRoute describes the HTTP binding for the DeleteProjectKey operation.
var DeleteProjectKeyRoute = httptransport.HTTPRoute{
	Method: "DELETE",
	Path:   "/v1/projects/{project_id}/keys/{key_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Key_id", WireName: "key_id"},
	},
	DecodeError: decodeDeleteProjectKeyError,
}

// decodeListProjectMembersError matches a non-2xx response to one of ListProjectMembers's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectMembersError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectMembersRoute describes the HTTP binding for the ListProjectMembers operation.
var ListProjectMembersRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/members",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectMembersError,
}

// decodeRemoveProjectMemberError matches a non-2xx response to one of RemoveProjectMember's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeRemoveProjectMemberError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// RemoveProjectMemberRoute describes the HTTP binding for the RemoveProjectMember operation.
var RemoveProjectMemberRoute = httptransport.HTTPRoute{
	Method: "DELETE",
	Path:   "/v1/projects/{project_id}/members/{member_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Member_id", WireName: "member_id"},
	},
	DecodeError: decodeRemoveProjectMemberError,
}

// decodeListMemberScopesError matches a non-2xx response to one of ListMemberScopes's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListMemberScopesError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListMemberScopesRoute describes the HTTP binding for the ListMemberScopes operation.
var ListMemberScopesRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/members/{member_id}/scopes",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Member_id", WireName: "member_id"},
	},
	DecodeError: decodeListMemberScopesError,
}

// decodeUpdateMemberScopesError matches a non-2xx response to one of UpdateMemberScopes's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeUpdateMemberScopesError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// UpdateMemberScopesRoute describes the HTTP binding for the UpdateMemberScopes operation.
var UpdateMemberScopesRoute = httptransport.HTTPRoute{
	Method: "PUT",
	Path:   "/v1/projects/{project_id}/members/{member_id}/scopes",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Member_id", WireName: "member_id"},
	},
	PayloadField: "Body",
	DecodeError:  decodeUpdateMemberScopesError,
}

// decodeListProjectInvitesError matches a non-2xx response to one of ListProjectInvites's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectInvitesError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectInvitesRoute describes the HTTP binding for the ListProjectInvites operation.
var ListProjectInvitesRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/invites",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectInvitesError,
}

// decodeCreateProjectInviteError matches a non-2xx response to one of CreateProjectInvite's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeCreateProjectInviteError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// CreateProjectInviteRoute describes the HTTP binding for the CreateProjectInvite operation.
var CreateProjectInviteRoute = httptransport.HTTPRoute{
	Method: "POST",
	Path:   "/v1/projects/{project_id}/invites",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	PayloadField: "Body",
	DecodeError:  decodeCreateProjectInviteError,
}

// decodeDeleteProjectInviteError matches a non-2xx response to one of DeleteProjectInvite's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeDeleteProjectInviteError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// DeleteProjectInviteRoute describes the HTTP binding for the DeleteProjectInvite operation.
var DeleteProjectInviteRoute = httptransport.HTTPRoute{
	Method: "DELETE",
	Path:   "/v1/projects/{project_id}/invites/{email}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Email", WireName: "email"},
	},
	DecodeError: decodeDeleteProjectInviteError,
}

// decodeListProjectBalancesError matches a non-2xx response to one of ListProjectBalances's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectBalancesError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectBalancesRoute describes the HTTP binding for the ListProjectBalances operation.
var ListProjectBalancesRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/balances",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectBalancesError,
}

// decodeGetProjectBalanceError matches a non-2xx response to one of GetProjectBalance's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetProjectBalanceError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetProjectBalanceRoute describes the HTTP binding for the GetProjectBalance operation.
var GetProjectBalanceRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/balances/{balance_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Balance_id", WireName: "balance_id"},
	},
	DecodeError: decodeGetProjectBalanceError,
}

// decodeGetBillingBreakdownError matches a non-2xx response to one of GetBillingBreakdown's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetBillingBreakdownError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetBillingBreakdownRoute describes the HTTP binding for the GetBillingBreakdown operation.
var GetBillingBreakdownRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/billing/breakdown",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Start", WireName: "start"},
		{GoField: "End", WireName: "end"},
		{GoField: "Accessor", WireName: "accessor"},
		{GoField: "Deployment", WireName: "deployment"},
		{GoField: "Tag", WireName: "tag"},
		{GoField: "Line_item", WireName: "line_item"},
		{GoField: "Grouping", WireName: "grouping"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeGetBillingBreakdownError,
}

// decodeListBillingFieldsError matches a non-2xx response to one of ListBillingFields's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListBillingFieldsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListBillingFieldsRoute describes the HTTP binding for the ListBillingFields operation.
var ListBillingFieldsRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/billing/fields",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Start", WireName: "start"},
		{GoField: "End", WireName: "end"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListBillingFieldsError,
}

// decodeListProjectPurchasesError matches a non-2xx response to one of ListProjectPurchases's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectPurchasesError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectPurchasesRoute describes the HTTP binding for the ListProjectPurchases operation.
var ListProjectPurchasesRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/purchases",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Limit", WireName: "limit"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectPurchasesError,
}

// decodeListProjectRequestsError matches a non-2xx response to one of ListProjectRequests's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectRequestsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectRequestsRoute describes the HTTP binding for the ListProjectRequests operation.
var ListProjectRequestsRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/requests",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Start", WireName: "start"},
		{GoField: "End", WireName: "end"},
		{GoField: "Limit", WireName: "limit"},
		{GoField: "Page", WireName: "page"},
		{GoField: "Accessor", WireName: "accessor"},
		{GoField: "Request_id", WireName: "request_id"},
		{GoField: "Deployment", WireName: "deployment"},
		{GoField: "Endpoint", WireName: "endpoint"},
		{GoField: "Method", WireName: "method"},
		{GoField: "Status", WireName: "status"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectRequestsError,
}

// decodeGetProjectRequestError matches a non-2xx response to one of GetProjectRequest's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetProjectRequestError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetProjectRequestRoute describes the HTTP binding for the GetProjectRequest operation.
var GetProjectRequestRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/requests/{request_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Request_id", WireName: "request_id"},
	},
	DecodeError: decodeGetProjectRequestError,
}

// decodeGetProjectUsageError matches a non-2xx response to one of GetProjectUsage's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetProjectUsageError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetProjectUsageRoute describes the HTTP binding for the GetProjectUsage operation.
var GetProjectUsageRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/usage",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Start", WireName: "start"},
		{GoField: "End", WireName: "end"},
		{GoField: "Accessor", WireName: "accessor"},
		{GoField: "Deployment", WireName: "deployment"},
		{GoField: "Endpoint", WireName: "endpoint"},
		{GoField: "Method", WireName: "method"},
		{GoField: "Model", WireName: "model"},
		{GoField: "Tag", WireName: "tag"},
		{GoField: "Alternatives", WireName: "alternatives"},
		{GoField: "Callback_method", WireName: "callback_method"},
		{GoField: "Callback", WireName: "callback"},
		{GoField: "Channels", WireName: "channels"},
		{GoField: "Custom_intent_mode", WireName: "custom_intent_mode"},
		{GoField: "Custom_intent", WireName: "custom_intent"},
		{GoField: "Custom_topic_mode", WireName: "custom_topic_mode"},
		{GoField: "Custom_topic", WireName: "custom_topic"},
		{GoField: "Detect_entities", WireName: "detect_entities"},
		{GoField: "Detect_language", WireName: "detect_language"},
		{GoField: "Diarize", WireName: "diarize"},
		{GoField: "Dictation", WireName: "dictation"},
		{GoField: "Encoding", WireName: "encoding"},
		{GoField: "Extra", WireName: "extra"},
		{GoField: "Filler_words", WireName: "filler_words"},
		{GoField: "Intents", WireName: "intents"},
		{GoField: "Keyterm", WireName: "keyterm"},
		{GoField: "Keywords", WireName: "keywords"},
		{GoField: "Language", WireName: "language"},
		{GoField: "Measurements", WireName: "measurements"},
		{GoField: "Multichannel", WireName: "multichannel"},
		{GoField: "Numerals", WireName: "numerals"},
		{GoField: "Paragraphs", WireName: "paragraphs"},
		{GoField: "Profanity_filter", WireName: "profanity_filter"},
		{GoField: "Punctuate", WireName: "punctuate"},
		{GoField: "Redact", WireName: "redact"},
		{GoField: "Replace", WireName: "replace"},
		{GoField: "Sample_rate", WireName: "sample_rate"},
		{GoField: "Search", WireName: "search"},
		{GoField: "Sentiment", WireName: "sentiment"},
		{GoField: "Smart_format", WireName: "smart_format"},
		{GoField: "Summarize", WireName: "summarize"},
		{GoField: "Topics", WireName: "topics"},
		{GoField: "Utt_split", WireName: "utt_split"},
		{GoField: "Utterances", WireName: "utterances"},
		{GoField: "Version", WireName: "version"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeGetProjectUsageError,
}

// decodeListUsageFieldsError matches a non-2xx response to one of ListUsageFields's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListUsageFieldsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListUsageFieldsRoute describes the HTTP binding for the ListUsageFields operation.
var ListUsageFieldsRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/usage/fields",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Start", WireName: "start"},
		{GoField: "End", WireName: "end"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListUsageFieldsError,
}

// decodeGetUsageBreakdownError matches a non-2xx response to one of GetUsageBreakdown's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetUsageBreakdownError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetUsageBreakdownRoute describes the HTTP binding for the GetUsageBreakdown operation.
var GetUsageBreakdownRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/usage/breakdown",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Start", WireName: "start"},
		{GoField: "End", WireName: "end"},
		{GoField: "Accessor", WireName: "accessor"},
		{GoField: "Deployment", WireName: "deployment"},
		{GoField: "Endpoint", WireName: "endpoint"},
		{GoField: "Method", WireName: "method"},
		{GoField: "Model", WireName: "model"},
		{GoField: "Tag", WireName: "tag"},
		{GoField: "Alternatives", WireName: "alternatives"},
		{GoField: "Callback_method", WireName: "callback_method"},
		{GoField: "Callback", WireName: "callback"},
		{GoField: "Channels", WireName: "channels"},
		{GoField: "Custom_intent_mode", WireName: "custom_intent_mode"},
		{GoField: "Custom_intent", WireName: "custom_intent"},
		{GoField: "Custom_topic_mode", WireName: "custom_topic_mode"},
		{GoField: "Custom_topic", WireName: "custom_topic"},
		{GoField: "Detect_entities", WireName: "detect_entities"},
		{GoField: "Detect_language", WireName: "detect_language"},
		{GoField: "Diarize", WireName: "diarize"},
		{GoField: "Dictation", WireName: "dictation"},
		{GoField: "Encoding", WireName: "encoding"},
		{GoField: "Extra", WireName: "extra"},
		{GoField: "Filler_words", WireName: "filler_words"},
		{GoField: "Intents", WireName: "intents"},
		{GoField: "Keyterm", WireName: "keyterm"},
		{GoField: "Keywords", WireName: "keywords"},
		{GoField: "Language", WireName: "language"},
		{GoField: "Measurements", WireName: "measurements"},
		{GoField: "Multichannel", WireName: "multichannel"},
		{GoField: "Numerals", WireName: "numerals"},
		{GoField: "Paragraphs", WireName: "paragraphs"},
		{GoField: "Profanity_filter", WireName: "profanity_filter"},
		{GoField: "Punctuate", WireName: "punctuate"},
		{GoField: "Redact", WireName: "redact"},
		{GoField: "Replace", WireName: "replace"},
		{GoField: "Sample_rate", WireName: "sample_rate"},
		{GoField: "Search", WireName: "search"},
		{GoField: "Sentiment", WireName: "sentiment"},
		{GoField: "Smart_format", WireName: "smart_format"},
		{GoField: "Summarize", WireName: "summarize"},
		{GoField: "Topics", WireName: "topics"},
		{GoField: "Utt_split", WireName: "utt_split"},
		{GoField: "Utterances", WireName: "utterances"},
		{GoField: "Version", WireName: "version"},
		{GoField: "Grouping", WireName: "grouping"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeGetUsageBreakdownError,
}

// decodeListModelsError matches a non-2xx response to one of ListModels's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListModelsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListModelsRoute describes the HTTP binding for the ListModels operation.
var ListModelsRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/models",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Include_outdated", WireName: "include_outdated"},
	},
	DecodeError: decodeListModelsError,
}

// decodeGetModelError matches a non-2xx response to one of GetModel's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetModelError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetModelRoute describes the HTTP binding for the GetModel operation.
var GetModelRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/models/{model_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Model_id", WireName: "model_id"},
	},
	DecodeError: decodeGetModelError,
}

// decodeListProjectModelsError matches a non-2xx response to one of ListProjectModels's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeListProjectModelsError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 400:
		v := &InvalidQueryParameterError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// ListProjectModelsRoute describes the HTTP binding for the ListProjectModels operation.
var ListProjectModelsRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/models",
	QueryFields: []httptransport.FieldBinding{
		{GoField: "Include_outdated", WireName: "include_outdated"},
	},
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
	},
	DecodeError: decodeListProjectModelsError,
}

// decodeGetProjectModelError matches a non-2xx response to one of GetProjectModel's declared
// @error structures by HTTP status, JSON-decodes the body into it, and
// copies @httpHeader-bound fields from the response headers. Returns nil
// when the status does not correspond to a declared error or the body
// fails to decode (e.g. an upstream gateway returned non-JSON HTML).
func decodeGetProjectModelError(status int, body []byte, headers nethttp.Header) error {
	switch status {
	case 401:
		v := &UnauthorizedError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 403:
		v := &ForbiddenError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 404:
		v := &NotFoundError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	case 500:
		v := &InternalServerError{}
		if err := json.Unmarshal(body, v); err != nil {
			return nil
		}
		if h := headers.Get("dg-error"); h != "" {
			hCopy := h
			v.DgError = &hCopy
		}
		return v
	}
	return nil
}

// GetProjectModelRoute describes the HTTP binding for the GetProjectModel operation.
var GetProjectModelRoute = httptransport.HTTPRoute{
	Method: "GET",
	Path:   "/v1/projects/{project_id}/models/{model_id}",
	PathParams: []httptransport.FieldBinding{
		{GoField: "Project_id", WireName: "project_id"},
		{GoField: "Model_id", WireName: "model_id"},
	},
	DecodeError: decodeGetProjectModelError,
}
