// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Shared marshalling helpers for @streaming unions, used by the
// per-service <service>_streaming.go files. Emitted once.

package types

import "encoding/json"

// marshalTagged JSON-marshals payload then injects a top-level
// `"type": typeName` field on the result. Used for streaming-union
// members whose target structure carries @messageType.
func marshalTagged(typeName string, payload any) ([]byte, error) {
	data, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	if raw == nil {
		raw = map[string]any{}
	}
	raw["type"] = typeName
	return json.Marshal(raw)
}
