// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	"github.com/deepgram/spec-mock-go-sdk/api/document"
)

// Audio frame variant. Wire form is a binary WS frame whose body is data .
type AgentAudioFrame struct {

	// This member is required.
	Data []byte `json:"data"`

	noSmithyDocumentSerde
}

// {"type":"FunctionCallResponse","id":"...","name":"...","content":"..."} . Used
// in BOTH directions (client reply + server-side result).
type AgentFunctionCallResponse struct {

	// This member is required.
	Content *string `json:"content"`

	// This member is required.
	Id *string `json:"id"`

	// This member is required.
	Name *string `json:"name"`

	noSmithyDocumentSerde
}

// {"type":"InjectAgentMessage","content":"...","behavior":"..."} .
type AgentInjectAgentMessage struct {

	// This member is required.
	Content *string `json:"content"`

	// Interaction with ongoing speech: Default | Queue | Interrupt .
	Behavior AgentInjectBehavior `json:"behavior,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"InjectUserMessage","content":"..."} .
type AgentInjectUserMessage struct {

	// This member is required.
	Content *string `json:"content"`

	noSmithyDocumentSerde
}

// {"type":"KeepAlive"} .
type AgentKeepAlive struct {
	noSmithyDocumentSerde
}

// {"type":"ReplacePrompt","prompt":"..."} . Requires experimental: true .
type AgentReplacePrompt struct {

	// This member is required.
	Prompt *string `json:"prompt"`

	noSmithyDocumentSerde
}

type AgentAudioInput struct {
	Encoding AgentInputEncoding `json:"encoding,omitempty"`

	SampleRate *int32 `json:"sample_rate,omitempty"`

	noSmithyDocumentSerde
}

type AgentAudioOutput struct {
	Bitrate *int32 `json:"bitrate,omitempty"`

	Container AgentOutputContainer `json:"container,omitempty"`

	Encoding AgentOutputEncoding `json:"encoding,omitempty"`

	SampleRate *int32 `json:"sample_rate,omitempty"`

	// Stream audio in fixed-size chunks. Default true.
	Stream *bool `json:"stream,omitempty"`

	noSmithyDocumentSerde
}

type AgentAudio struct {
	Input *AgentAudioInput `json:"input,omitempty"`

	Output *AgentAudioOutput `json:"output,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"Settings", ...} . Session configuration. The agent provider config
// (listen/think/speak) is deeply nested and open — modeled as Document . See
// AGENT-001.
type AgentSettings struct {

	// Agent provider config (listen/think/speak/functions/greeting/...), OR a bare
	// agent-id string. Deeply nested + provider-specific; open Document .
	Agent document.Interface `json:"agent,omitempty"`

	Audio *AgentAudio `json:"audio,omitempty"`

	Experimental *bool `json:"experimental,omitempty"`

	// Session flags (e.g. { "history": true } ). Open map.
	Flags document.Interface `json:"flags,omitempty"`

	MipOptOut *bool `json:"mip_opt_out,omitempty"`

	Tags []string `json:"tags,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"UpdatePrompt","prompt":"..."} .
type AgentUpdatePrompt struct {

	// This member is required.
	Prompt *string `json:"prompt"`

	noSmithyDocumentSerde
}

// {"type":"UpdateSpeak","speak":...} . speak is a single object or array of
// provider configs (open). See AGENT-001.
type AgentUpdateSpeak struct {

	// This member is required.
	Speak document.Interface `json:"speak"`

	noSmithyDocumentSerde
}

// {"type":"UpdateThink","think":...} . think is a single object or array of
// provider configs (open). See AGENT-001.
type AgentUpdateThink struct {

	// This member is required.
	Think document.Interface `json:"think"`

	noSmithyDocumentSerde
}

// The following types satisfy this interface:
//
//	AgentClientStreamMemberAudio
//	AgentClientStreamMemberFunctionCallResponse
//	AgentClientStreamMemberInjectAgentMessage
//	AgentClientStreamMemberInjectUserMessage
//	AgentClientStreamMemberKeepAlive
//	AgentClientStreamMemberReplacePrompt
//	AgentClientStreamMemberSettings
//	AgentClientStreamMemberUpdatePrompt
//	AgentClientStreamMemberUpdateSpeak
//	AgentClientStreamMemberUpdateThink
type AgentClientStream interface {
	isAgentClientStream()
}

// Raw mic audio bytes. Binary WebSocket frame, NOT JSON. Allowed only after
// Settings .
type AgentClientStreamMemberAudio struct {
	Value AgentAudioFrame

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberAudio) isAgentClientStream() {}

// {"type":"FunctionCallResponse","id":"...","name":"...","content":"..."} . Used
// in BOTH directions (client reply + server-side result).
type AgentClientStreamMemberFunctionCallResponse struct {
	Value AgentFunctionCallResponse

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberFunctionCallResponse) isAgentClientStream() {}

// {"type":"InjectAgentMessage","content":"...","behavior":"..."} .
type AgentClientStreamMemberInjectAgentMessage struct {
	Value AgentInjectAgentMessage

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberInjectAgentMessage) isAgentClientStream() {}

// {"type":"InjectUserMessage","content":"..."} .
type AgentClientStreamMemberInjectUserMessage struct {
	Value AgentInjectUserMessage

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberInjectUserMessage) isAgentClientStream() {}

// {"type":"KeepAlive"} .
type AgentClientStreamMemberKeepAlive struct {
	Value AgentKeepAlive

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberKeepAlive) isAgentClientStream() {}

// {"type":"ReplacePrompt","prompt":"..."} . Requires experimental: true .
type AgentClientStreamMemberReplacePrompt struct {
	Value AgentReplacePrompt

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberReplacePrompt) isAgentClientStream() {}

// Session configuration. Must be the first message.
type AgentClientStreamMemberSettings struct {
	Value AgentSettings

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberSettings) isAgentClientStream() {}

// {"type":"UpdatePrompt","prompt":"..."} .
type AgentClientStreamMemberUpdatePrompt struct {
	Value AgentUpdatePrompt

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberUpdatePrompt) isAgentClientStream() {}

// {"type":"UpdateSpeak","speak":...} . speak is a single object or array of
// provider configs (open). See AGENT-001.
type AgentClientStreamMemberUpdateSpeak struct {
	Value AgentUpdateSpeak

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberUpdateSpeak) isAgentClientStream() {}

// {"type":"UpdateThink","think":...} . think is a single object or array of
// provider configs (open). See AGENT-001.
type AgentClientStreamMemberUpdateThink struct {
	Value AgentUpdateThink

	noSmithyDocumentSerde
}

func (*AgentClientStreamMemberUpdateThink) isAgentClientStream() {}

type ConverseInput struct {
	SecWebSocketProtocol *string `json:"-"`

	noSmithyDocumentSerde
}

// {"type":"AgentAudioDone"} . No more audio frames for the current utterance.
type AgentAudioDone struct {
	noSmithyDocumentSerde
}

// {"type":"AgentStartedSpeaking", ...} .
type AgentStartedSpeaking struct {

	// This member is required.
	TtsLatency *float64 `json:"tts_latency"`

	// This member is required.
	TttLatency *float64 `json:"ttt_latency"`

	TotalLatency *float64 `json:"total_latency,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"AgentThinking","content":"..."} . Non-verbalized reasoning.
type AgentThinking struct {

	// This member is required.
	Content *string `json:"content"`

	noSmithyDocumentSerde
}

// {"type":"ConversationText","role":"...","content":"..."} . User or agent
// utterance; interim when is_final is false.
type AgentConversationText struct {

	// This member is required.
	Content *string `json:"content"`

	// This member is required.
	Role AgentRole `json:"role"`

	IsFinal *bool `json:"is_final,omitempty"`

	Languages []string `json:"languages,omitempty"`

	// Word-level detail (open; provider-dependent).
	Words document.Interface `json:"words,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"EndOfThought"} .
type AgentEndOfThought struct {
	noSmithyDocumentSerde
}

// {"type":"Error","description":"...","code":"..."} . Fatal; sent before the
// server closes the connection.
type AgentError struct {

	// Error code (e.g. INVALID_SETTINGS ). Open set; see developer docs.
	//
	// This member is required.
	Code *string `json:"code"`

	// This member is required.
	Description *string `json:"description"`

	noSmithyDocumentSerde
}

// {"type":"FunctionCallRequest","functions":[...]} . functions is an open list of
// {id,name,arguments,client_side,...} . See AGENT-001.
type AgentFunctionCallRequest struct {

	// This member is required.
	Functions document.Interface `json:"functions"`

	noSmithyDocumentSerde
}

// {"type":"History", ...} . Conversation-history entry at session start when
// flags.history is set. Payload is untagged (a conversation message OR a
// function-call record); modeled as open Document . See AGENT-001.
type AgentHistory struct {
	Entry document.Interface `json:"entry,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"LatencyReport", ...} . One latency metric per message (the wire
// flattens a single field); modeled flat with all metrics optional. See AGENT-003.
type AgentLatencyReport struct {
	SttLatency *float64 `json:"stt_latency,omitempty"`

	TotalLatency *float64 `json:"total_latency,omitempty"`

	TtsLatency *float64 `json:"tts_latency,omitempty"`

	TttTextLatency *float64 `json:"ttt_text_latency,omitempty"`

	TttThinkingLatency *float64 `json:"ttt_thinking_latency,omitempty"`

	TttTokenLatency *float64 `json:"ttt_token_latency,omitempty"`

	TttToolLatency *float64 `json:"ttt_tool_latency,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"PromptReplaced"} .
type AgentPromptReplaced struct {
	noSmithyDocumentSerde
}

// {"type":"PromptUpdated"} .
type AgentPromptUpdated struct {
	noSmithyDocumentSerde
}

// {"type":"SettingsApplied"} .
type AgentSettingsApplied struct {
	noSmithyDocumentSerde
}

// {"type":"SpeakUpdated"} .
type AgentSpeakUpdated struct {
	noSmithyDocumentSerde
}

// {"type":"ThinkUpdated"} .
type AgentThinkUpdated struct {
	noSmithyDocumentSerde
}

// {"type":"UserStartedSpeaking"} .
type AgentUserStartedSpeaking struct {
	noSmithyDocumentSerde
}

// {"type":"Warning","description":"...","code":"..."} . Non-fatal.
type AgentWarning struct {

	// Warning code (e.g. PROMPT_TOO_LONG ). Open set; see developer docs.
	//
	// This member is required.
	Code *string `json:"code"`

	// This member is required.
	Description *string `json:"description"`

	noSmithyDocumentSerde
}

// {"type":"Welcome","request_id":"..."} . First message on every connection.
type AgentWelcome struct {

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`

	noSmithyDocumentSerde
}

// The following types satisfy this interface:
//
//	AgentServerStreamMemberAgentAudioDone
//	AgentServerStreamMemberAgentStartedSpeaking
//	AgentServerStreamMemberAgentThinking
//	AgentServerStreamMemberAudio
//	AgentServerStreamMemberConversationText
//	AgentServerStreamMemberEndOfThought
//	AgentServerStreamMemberError
//	AgentServerStreamMemberFunctionCallRequest
//	AgentServerStreamMemberFunctionCallResponse
//	AgentServerStreamMemberHistory
//	AgentServerStreamMemberLatencyReport
//	AgentServerStreamMemberPromptReplaced
//	AgentServerStreamMemberPromptUpdated
//	AgentServerStreamMemberSettingsApplied
//	AgentServerStreamMemberSpeakUpdated
//	AgentServerStreamMemberThinkUpdated
//	AgentServerStreamMemberUserStartedSpeaking
//	AgentServerStreamMemberWarning
//	AgentServerStreamMemberWelcome
type AgentServerStream interface {
	isAgentServerStream()
}

// {"type":"AgentAudioDone"} . No more audio frames for the current utterance.
type AgentServerStreamMemberAgentAudioDone struct {
	Value AgentAudioDone

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberAgentAudioDone) isAgentServerStream() {}

// {"type":"AgentStartedSpeaking", ...} .
//
// Deprecated: Use latencyReport instead.
type AgentServerStreamMemberAgentStartedSpeaking struct {
	Value AgentStartedSpeaking

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberAgentStartedSpeaking) isAgentServerStream() {}

// {"type":"AgentThinking","content":"..."} . Non-verbalized reasoning.
type AgentServerStreamMemberAgentThinking struct {
	Value AgentThinking

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberAgentThinking) isAgentServerStream() {}

// Agent speech bytes. Binary WebSocket frame, NOT JSON.
type AgentServerStreamMemberAudio struct {
	Value AgentAudioFrame

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberAudio) isAgentServerStream() {}

// {"type":"ConversationText","role":"...","content":"..."} . User or agent
// utterance; interim when is_final is false.
type AgentServerStreamMemberConversationText struct {
	Value AgentConversationText

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberConversationText) isAgentServerStream() {}

// {"type":"EndOfThought"} .
type AgentServerStreamMemberEndOfThought struct {
	Value AgentEndOfThought

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberEndOfThought) isAgentServerStream() {}

// {"type":"Error","description":"...","code":"..."} . Fatal; sent before the
// server closes the connection.
type AgentServerStreamMemberError struct {
	Value AgentError

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberError) isAgentServerStream() {}

// {"type":"FunctionCallRequest","functions":[...]} . functions is an open list of
// {id,name,arguments,client_side,...} . See AGENT-001.
type AgentServerStreamMemberFunctionCallRequest struct {
	Value AgentFunctionCallRequest

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberFunctionCallRequest) isAgentServerStream() {}

// {"type":"FunctionCallResponse","id":"...","name":"...","content":"..."} . Used
// in BOTH directions (client reply + server-side result).
type AgentServerStreamMemberFunctionCallResponse struct {
	Value AgentFunctionCallResponse

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberFunctionCallResponse) isAgentServerStream() {}

// {"type":"History", ...} . Conversation-history entry at session start when
// flags.history is set. Payload is untagged (a conversation message OR a
// function-call record); modeled as open Document . See AGENT-001.
type AgentServerStreamMemberHistory struct {
	Value AgentHistory

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberHistory) isAgentServerStream() {}

// {"type":"LatencyReport", ...} . One latency metric per message (the wire
// flattens a single field); modeled flat with all metrics optional. See AGENT-003.
type AgentServerStreamMemberLatencyReport struct {
	Value AgentLatencyReport

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberLatencyReport) isAgentServerStream() {}

// {"type":"PromptReplaced"} .
type AgentServerStreamMemberPromptReplaced struct {
	Value AgentPromptReplaced

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberPromptReplaced) isAgentServerStream() {}

// {"type":"PromptUpdated"} .
type AgentServerStreamMemberPromptUpdated struct {
	Value AgentPromptUpdated

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberPromptUpdated) isAgentServerStream() {}

// {"type":"SettingsApplied"} .
type AgentServerStreamMemberSettingsApplied struct {
	Value AgentSettingsApplied

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberSettingsApplied) isAgentServerStream() {}

// {"type":"SpeakUpdated"} .
type AgentServerStreamMemberSpeakUpdated struct {
	Value AgentSpeakUpdated

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberSpeakUpdated) isAgentServerStream() {}

// {"type":"ThinkUpdated"} .
type AgentServerStreamMemberThinkUpdated struct {
	Value AgentThinkUpdated

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberThinkUpdated) isAgentServerStream() {}

// {"type":"UserStartedSpeaking"} .
type AgentServerStreamMemberUserStartedSpeaking struct {
	Value AgentUserStartedSpeaking

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberUserStartedSpeaking) isAgentServerStream() {}

// {"type":"Warning","description":"...","code":"..."} . Non-fatal.
type AgentServerStreamMemberWarning struct {
	Value AgentWarning

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberWarning) isAgentServerStream() {}

// {"type":"Welcome","request_id":"..."} . First message on every connection.
type AgentServerStreamMemberWelcome struct {
	Value AgentWelcome

	noSmithyDocumentSerde
}

func (*AgentServerStreamMemberWelcome) isAgentServerStream() {}

type ConverseOutput struct {
	SecWebSocketProtocol *string `json:"-"`

	noSmithyDocumentSerde
}

type Entity struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`

	// This member is required.
	EndWord *int32 `json:"end_word"`

	// This member is required.
	Label *string `json:"label"`

	// This member is required.
	StartWord *int32 `json:"start_word"`

	// This member is required.
	Value *string `json:"value"`

	// Original non-formatted text as spoken. Present when smart-formatting rewrote
	// value ; absent when no rewrite happened.
	RawValue *string `json:"raw_value,omitempty"`

	noSmithyDocumentSerde
}

type Sentence struct {

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`

	// This member is required.
	Text *string `json:"text"`

	// Per-sentence sentiment.
	Sentiment Sentiment `json:"sentiment,omitempty"`

	SentimentScore *float32 `json:"sentiment_score,omitempty"`

	noSmithyDocumentSerde
}

type Paragraph struct {

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`

	// This member is required.
	NumWords *int32 `json:"num_words"`

	// This member is required.
	Sentences []Sentence `json:"sentences"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`

	// Channel index when the paragraph aggregates across multiple channels
	// (multichannel batch responses).
	Channel *int64 `json:"channel,omitempty"`

	// Per-paragraph sentiment when ?sentiment=true . Flattens to sentiment +
	// sentiment_score on the Paragraph object.
	Sentiment Sentiment `json:"sentiment,omitempty"`

	SentimentScore *float32 `json:"sentiment_score,omitempty"`

	// Speaker assignment for the paragraph (when diarized).
	Speaker *int64 `json:"speaker,omitempty"`

	noSmithyDocumentSerde
}

// Paragraph segmentation wrapper.
type Paragraphs struct {

	// This member is required.
	Paragraphs []Paragraph `json:"paragraphs"`

	Transcript *string `json:"transcript,omitempty"`

	noSmithyDocumentSerde
}

// Phoneme-level word. Used in pronunciation analysis features.
type PhonemeWord struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`

	// This member is required.
	Phoneme *string `json:"phoneme"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`

	noSmithyDocumentSerde
}

type SitSentimentSegment struct {

	// This member is required.
	EndWord *int32 `json:"end_word"`

	// This member is required.
	Sentiment Sentiment `json:"sentiment"`

	// This member is required.
	SentimentScore *float32 `json:"sentiment_score"`

	// This member is required.
	StartWord *int32 `json:"start_word"`

	Text *string `json:"text,omitempty"`

	noSmithyDocumentSerde
}

type Summary struct {

	// This member is required.
	EndWord *int32 `json:"end_word"`

	// This member is required.
	StartWord *int32 `json:"start_word"`

	// This member is required.
	Summary *string `json:"summary"`

	noSmithyDocumentSerde
}

type Topic struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	ConfidenceScore *float32 `json:"confidence_score"`

	// This member is required.
	Topic *string `json:"topic"`

	noSmithyDocumentSerde
}

type TopicSegment struct {

	// This member is required.
	EndWord *int32 `json:"end_word"`

	// This member is required.
	StartWord *int32 `json:"start_word"`

	// This member is required.
	Text *string `json:"text"`

	// This member is required.
	Topics []Topic `json:"topics"`

	noSmithyDocumentSerde
}

type Translation struct {

	// BCP-47 language code. Examples: en , en-US , es , pt-BR .
	//
	// This member is required.
	Language *string `json:"language"`

	// This member is required.
	Translation *string `json:"translation"`

	noSmithyDocumentSerde
}

// One word in the transcript. Many fields are conditionally present depending on
// the requested features.
type Word struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`

	// Lowercased dictionary form.
	//
	// This member is required.
	Word *string `json:"word"`

	// Raw bytes attached to this word. Used internally and only sometimes surfaced on
	// the wire.
	Context []byte `json:"context,omitempty"`

	// Embedding vector — a named dictionary of per-dimension floats, not a positional
	// list.
	FullVec map[string]float32 `json:"full_vec,omitempty"`

	// Detected language for this word. WSS-populated when ?detect_language=true .
	Language *string `json:"language,omitempty"`

	// Capitalized + punctuated form (when ?punctuate=true ).
	PunctuatedWord *string `json:"punctuated_word,omitempty"`

	// Replacement text after ?redact=... is applied.
	RedactedText *string `json:"redacted_text,omitempty"`

	// Per-word sentiment, present when ?sentiment=true . Flattens to sentiment +
	// sentiment_score on the Word object.
	Sentiment Sentiment `json:"sentiment,omitempty"`

	SentimentScore *float32 `json:"sentiment_score,omitempty"`

	// Speaker label, present when ?diarize=true . Indexed from 0.
	Speaker *int64 `json:"speaker,omitempty"`

	// Confidence in the speaker assignment. REST-populated.
	SpeakerConfidence *float32 `json:"speaker_confidence,omitempty"`

	// Stable speaker ID across requests when ?identify=true .
	SpeakerId *string `json:"speaker_id,omitempty"`

	noSmithyDocumentSerde
}

// One ranked alternative interpretation of the audio segment.
type Alternative struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`

	// This member is required.
	Transcript *string `json:"transcript"`

	// This member is required.
	Words []Word `json:"words"`

	// Detected entities. Present when ?detect_entities=true .
	Entities []Entity `json:"entities,omitempty"`

	// Languages detected in this alternative. Mostly populated when
	// ?detect_language=true .
	Languages []string `json:"languages,omitempty"`

	// Paragraph segmentation. Present when ?paragraphs=true or when smart formatting
	// groups the transcript.
	Paragraphs *Paragraphs `json:"paragraphs,omitempty"`

	// Phoneme-level annotations. Rare; present when ?phoneme_lattice=true .
	Phonemes []PhonemeWord `json:"phonemes,omitempty"`

	// Sentiment segments inline with the alternative, when ?sentiment=true .
	SentimentSegments []SitSentimentSegment `json:"sentiment_segments,omitempty"`

	Summaries []Summary `json:"summaries,omitempty"`

	// Topic tags inline with the alternative, when ?topics=true .
	Topics []TopicSegment `json:"topics,omitempty"`

	// Translations of the transcript, when applicable.
	Translations []Translation `json:"translations,omitempty"`

	noSmithyDocumentSerde
}

type Hit struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`

	// Matched text snippet.
	Snippet *string `json:"snippet,omitempty"`

	noSmithyDocumentSerde
}

type SearchResult struct {

	// This member is required.
	Hits []Hit `json:"hits"`

	// This member is required.
	Query *string `json:"query"`

	noSmithyDocumentSerde
}

// One channel of a transcript. Multichannel responses contain one of these per
// audio channel; mono contains exactly one. REST ResponseResults carries a list
// of these; WSS StreamingResponse carries exactly one (selected by channel_index ).
type Channel struct {

	// This member is required.
	Alternatives []Alternative `json:"alternatives"`

	// Detected language for this channel. Present when ?detect_language=true .
	DetectedLanguage *string `json:"detected_language,omitempty"`

	// Confidence in the detected language. Range [0, 1].
	LanguageConfidence *float32 `json:"language_confidence,omitempty"`

	// Phrase-search hits. Empty when no ?search= queries were submitted.
	Search []SearchResult `json:"search,omitempty"`

	// Per-channel utterance segment boundaries. Present when ?utterances=true . Each
	// entry is a word-index marking the start of an utterance for this channel's first
	// alternative. The top-level Result.utterances field (REST batch only) carries
	// the richer Utterance objects.
	Utterances []int32 `json:"utterances,omitempty"`

	noSmithyDocumentSerde
}

// A single detected intent with a confidence score. Shared across products that
// surface intent detection (Listen batch, Read). Mirrors Topic .
type Intent struct {

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	ConfidenceScore *float32 `json:"confidence_score"`

	// This member is required.
	Intent *string `json:"intent"`

	noSmithyDocumentSerde
}

type ModelInfo struct {
	Arch *string `json:"arch,omitempty"`

	Name *string `json:"name,omitempty"`

	Version *string `json:"version,omitempty"`

	noSmithyDocumentSerde
}

// Token-count metadata for AI features (summarize, sentiment, topics, intents).
// Populated on REST ResponseMetadata per-feature. model_uuid is the canonical
// UUID identifier; model is an SDK convenience for the model name.
type TokenMetadata struct {

	// This member is required.
	InputTokens *int64 `json:"input_tokens"`

	// Stable UUID for a specific model instance. UUID v4 in canonical lowercase
	// string form. Distinct from ModelId (which is a human-readable family label like
	// nova-3-general ) — ModelUuid identifies the exact deployed model build.
	//
	// This member is required.
	ModelUuid *string `json:"model_uuid"`

	// This member is required.
	OutputTokens *int64 `json:"output_tokens"`

	// Convenience: model name. Resolved by SDK using model_uuid lookup.
	Model *string `json:"model,omitempty"`

	noSmithyDocumentSerde
}

type Utterance struct {

	// This member is required.
	Channel *int32 `json:"channel"`

	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`

	// Stable utterance UUID. Allocated server-side per utterance.
	//
	// This member is required.
	Id *string `json:"id"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`

	// This member is required.
	Transcript *string `json:"transcript"`

	// This member is required.
	Words []Word `json:"words"`

	// Languages detected in this utterance, ranked most-to-least frequent. Populated
	// when words have language set.
	Languages []string `json:"languages,omitempty"`

	// Per-utterance sentiment, flattens to sentiment + sentiment_score on the
	// Utterance object.
	Sentiment Sentiment `json:"sentiment,omitempty"`

	SentimentScore *float32 `json:"sentiment_score,omitempty"`

	// Speaker label.
	Speaker *int64 `json:"speaker,omitempty"`

	noSmithyDocumentSerde
}

type Warning struct {

	// This member is required.
	Message *string `json:"message"`

	// This member is required.
	Parameter *string `json:"parameter"`

	// This member is required.
	Type WarningType `json:"type"`

	noSmithyDocumentSerde
}

type SentimentAggregate struct {

	// This member is required.
	Sentiment Sentiment `json:"sentiment"`

	// This member is required.
	SentimentScore *float32 `json:"sentiment_score"`

	noSmithyDocumentSerde
}

type AverageSentiment struct {

	// This member is required.
	Average *SentimentAggregate `json:"average"`

	noSmithyDocumentSerde
}

type UrlSource struct {

	// HTTPS URL where Deepgram's servers can fetch the audio.
	//
	// This member is required.
	Url *string `json:"url"`

	noSmithyDocumentSerde
}

// POST /v1/listen accepts two request body shapes selected by Content-Type . See LISTEN-004.
//
// The following types satisfy this interface:
//
//	TranscribeRequestBodyMemberAudio
//	TranscribeRequestBodyMemberUrlSource
type TranscribeRequestBody interface {
	isTranscribeRequestBody()
}

// Raw audio bytes. Sent with any non-blacklisted Content-Type (audio/, video/,
// application/octet-stream — NOT text/plain or application/json or text/html,
// which are reserved/blacklisted).
type TranscribeRequestBodyMemberAudio struct {
	Value []byte

	noSmithyDocumentSerde
}

func (*TranscribeRequestBodyMemberAudio) isTranscribeRequestBody() {}

// JSON envelope referencing audio at a remote URL. Content-Type: application/json
// selects this variant.
type TranscribeRequestBodyMemberUrlSource struct {
	Value UrlSource

	noSmithyDocumentSerde
}

func (*TranscribeRequestBodyMemberUrlSource) isTranscribeRequestBody() {}

type TranscribeInput struct {

	// POST /v1/listen accepts two request body shapes selected by Content-Type . See LISTEN-004.
	Body TranscribeRequestBody `json:"-"`

	// Where to deliver the completed transcript. When set, the operation returns
	// immediately with only requestId populated; results are POSTed to this URL once
	// transcoding completes.
	Callback *string `json:"-"`

	// HTTP method to use for callback delivery. Default POST .
	CallbackMethod CallbackMethod `json:"-"`

	ContentType *string `json:"-"`

	DetectEntities *bool `json:"-"`

	// Detect spoken languages from a constrained candidate set. Each repeated value
	// adds one allowed language code (BCP-47). When omitted, the request relies on the
	// language parameter or the Deepgram API's full-vocabulary language detector.
	DetectLanguage []string `json:"-"`

	// Deprecated: Legacy flag. Prefer diarize_model for explicit model selection.
	// diarize=true continues to work for backward compatibility but is mutually
	// exclusive with diarize_model .
	Diarize *bool `json:"-"`

	DiarizeModel *string `json:"-"`

	// Deprecated: Legacy diarization-model selector. Prefer diarize_model . Mutually
	// exclusive with diarize_model .
	DiarizeVersion *string `json:"-"`

	// Format dictation commands (e.g. "period" → ".", "new paragraph" → "\n\n") in
	// the transcript.
	Dictation *bool `json:"-"`

	Encoding *string `json:"-"`

	FillerWords *bool `json:"-"`

	Intents *bool `json:"-"`

	Keyterm []string `json:"-"`

	Keywords []string `json:"-"`

	// BCP-47 language code. Examples: en , en-US , es , pt-BR .
	Language *string `json:"-"`

	// Deprecated: Prefer mip_opt_out . log_data is recognized for backward
	// compatibility; sending both with conflicting values returns 400.
	LogData *bool `json:"-"`

	// Detect and format measurements (e.g. "five feet" → "5 ft", "two kilograms" → "2
	// kg").
	Measurements *bool `json:"-"`

	MipOptOut *bool `json:"-"`

	// A model identifier (e.g. nova-3-general , nova-2-medical ). Free-form string;
	// the set evolves. Documented in
	// https://developers.deepgram.com/docs/models-languages-overview.
	Model *string `json:"-"`

	Multichannel *bool `json:"-"`

	// Convert spelled-out numbers to digits in the transcript (e.g. "twenty-five" →
	// "25"). Boolean; default false.
	Numerals *bool `json:"-"`

	Paragraphs *bool `json:"-"`

	ProfanityFilter *bool `json:"-"`

	Punctuate *bool `json:"-"`

	Redact []string `json:"-"`

	// Find-and-replace substitution pairs applied during post-processing. Wire syntax
	// is repeated ?replace=find:with pairs (colon-separated key/value, NOT a
	// comma-joined list). The Deepgram API rewrites transcript tokens matching each
	// find before emission. Billable when non-empty.
	Replace []string `json:"-"`

	Search []string `json:"-"`

	Sentiment *bool `json:"-"`

	SmartFormat *bool `json:"-"`

	Summarize *string `json:"-"`

	Tag []string `json:"-"`

	Topics *bool `json:"-"`

	// Maximum silence (seconds) between words within an utterance before a new
	// utterance is started.
	UttSplit *float32 `json:"-"`

	Utterances *bool `json:"-"`

	// Deprecated: Use endpointing instead. vad_turnoff is rejected when endpointing
	// is also an integer; if only vad_turnoff is set it is silently mapped onto
	// endpointing .
	VadTurnoff *int32 `json:"-"`

	Version *string `json:"-"`

	noSmithyDocumentSerde
}

type ResponseMetadata struct {

	// This member is required.
	Channels *int32 `json:"channels"`

	// This member is required.
	Created *string `json:"created"`

	// A duration in seconds. Always non-negative.
	//
	// This member is required.
	Duration *float32 `json:"duration"`

	// This member is required.
	ModelInfo map[string]ModelInfo `json:"model_info"`

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`

	// This member is required.
	Sha256 *string `json:"sha256"`

	// Always serialized as the literal string "deprecated" . Historically carried
	// encrypted debug context; replaced by request_id . Retained in the response body
	// so legacy clients deserializing strict schemas don't break.
	//
	// This member is required.
	//
	// Deprecated: Field is always the literal string "deprecated". Use request_id for
	// debug correlation.
	TransactionKey *string `json:"transaction_key"`

	Extra map[string]string `json:"extra,omitempty"`

	// Token-count metadata for intent detection. Present when ?intents=true .
	IntentsInfo *TokenMetadata `json:"intents_info,omitempty"`

	// Subset of model_info keys, retained for backward compatibility with clients
	// that parsed models before model_info existed. Prefer model_info keys directly.
	//
	// Deprecated: Subset of model_info . Use model_info keys instead.
	Models []string `json:"models,omitempty"`

	// Per-batch processing time in seconds. Present only when ?performance=true was
	// set on the request.
	ProcessingTime *float32 `json:"processing_time,omitempty"`

	// Token-count metadata for sentiment analysis. Present when ?sentiment=true .
	SentimentInfo *TokenMetadata `json:"sentiment_info,omitempty"`

	// Token-count metadata for summarization. Present when ?summarize=v2 .
	SummaryInfo *TokenMetadata `json:"summary_info,omitempty"`

	// Tags echoed back from the request's ?tag= query parameters.
	Tags []string `json:"tags,omitempty"`

	// Token-count metadata for topic detection. Present when ?topics=true .
	TopicsInfo *TokenMetadata `json:"topics_info,omitempty"`

	Warnings []Warning `json:"warnings,omitempty"`

	noSmithyDocumentSerde
}

type ResponseResults struct {

	// This member is required.
	Channels []Channel `json:"channels"`

	// Document-level intents (when ?intents=true ).
	Intents []Intent `json:"intents,omitempty"`

	// Document-level sentiments aggregate (when ?sentiment=true ).
	Sentiments *AverageSentiment `json:"sentiments,omitempty"`

	// Document-level summaries (when ?summarize=v2 ).
	Summary []Summary `json:"summary,omitempty"`

	// Document-level topics (when ?topics=true ).
	Topics []Topic `json:"topics,omitempty"`

	// Channel-aware utterance segmentation (when ?utterances=true ).
	Utterances []Utterance `json:"utterances,omitempty"`

	noSmithyDocumentSerde
}

// Transcribe response.
//
// Always carries requestId (in body and via the dg-request-id header). metadata
// and results are populated only on the synchronous path (no ?callback= ); when
// callback is set on the request, they are absent from the immediate response body
// and instead delivered later to the callback URL with the same shape.
type TranscribeOutput struct {

	// Always populated. Same as the dg-request-id header.
	//
	// This member is required.
	RequestId *string `json:"request_id"`

	// Deepgram project identifier. UUID v4. Surfaced in the dg-project-id response
	// header on authenticated requests.
	DgProjectId *string `json:"-"`

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	DgRequestId *string `json:"-"`

	// Populated on synchronous responses. Absent on the immediate response when
	// ?callback= is set; appears in the callback delivery instead.
	Metadata *ResponseMetadata `json:"metadata,omitempty"`

	// Populated on synchronous responses. Absent on the immediate response when
	// ?callback= is set; appears in the callback delivery instead.
	Results *ResponseResults `json:"results,omitempty"`

	noSmithyDocumentSerde
}

// Audio frame variant. Smithy @streaming union members must be structures; the
// actual wire form is a binary WS frame whose body is data .
//
// @eventPayload marks the field as the binary payload of the event-stream frame
// (per AWS event-stream conventions); our custom WebSocket protocol generator
// interprets this as "send the bytes as a WS binary frame."
type AudioFrame struct {

	// Raw audio bytes (PCM, opus, etc., per the session's encoding query parameter).
	// Sent as the WS binary frame body, NOT JSON-encoded.
	//
	// This member is required.
	Data []byte `json:"data"`

	noSmithyDocumentSerde
}

// {"type":"CloseStream"} .
type CloseStream struct {
	noSmithyDocumentSerde
}

// {"type":"Configure","features":{...}} .
//
// features is an open key→value map. Values are JSON documents — the allowed keys
// evolve and aren't worth modelling exhaustively in the schema. Use the developer
// docs for the canonical list.
type Configure struct {

	// Map of feature name → arbitrary JSON value.
	//
	// This member is required.
	Features map[string]document.Interface `json:"features"`

	noSmithyDocumentSerde
}

// {"type":"Finalize","channel":<int|null>} .
//
// channel is optional — when omitted, finalize fires for every channel. On a
// single-channel session, omit it.
type Finalize struct {

	// 0-indexed channel to finalize. Omit for "all channels".
	Channel *int32 `json:"channel,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"KeepAlive"} .
type KeepAlive struct {
	noSmithyDocumentSerde
}

// {"type":"Sync","id":<u64>} .
type ClientSync struct {

	// This member is required.
	Id *int64 `json:"id"`

	noSmithyDocumentSerde
}

// Bidirectional WS stream from client to server. Audio bytes ride as binary
// frames ( audio variant); control messages ride as JSON text frames whose type
// field discriminates the variant.
//
// The following types satisfy this interface:
//
//	ClientStreamMemberAudio
//	ClientStreamMemberCloseStream
//	ClientStreamMemberConfigure
//	ClientStreamMemberFinalize
//	ClientStreamMemberKeepAlive
//	ClientStreamMemberSync
type ClientStream interface {
	isClientStream()
}

// Raw audio bytes. Sent as a binary WebSocket frame, NOT as JSON. An empty binary
// frame is treated equivalent to a closeStream JSON message.
type ClientStreamMemberAudio struct {
	Value AudioFrame

	noSmithyDocumentSerde
}

func (*ClientStreamMemberAudio) isClientStream() {}

// Graceful end-of-audio marker. Server flushes pending results and emits a final
// Metadata message before closing.
type ClientStreamMemberCloseStream struct {
	Value CloseStream

	noSmithyDocumentSerde
}

func (*ClientStreamMemberCloseStream) isClientStream() {}

// Update post-processor / feature configuration mid-session.
type ClientStreamMemberConfigure struct {
	Value Configure

	noSmithyDocumentSerde
}

func (*ClientStreamMemberConfigure) isClientStream() {}

// Force the server to emit a final transcript for the open utterance.
type ClientStreamMemberFinalize struct {
	Value Finalize

	noSmithyDocumentSerde
}

func (*ClientStreamMemberFinalize) isClientStream() {}

// Resets client + driver inactivity timers. Send periodically when the client has
// no audio to transmit but wants to keep the session alive.
type ClientStreamMemberKeepAlive struct {
	Value KeepAlive

	noSmithyDocumentSerde
}

func (*ClientStreamMemberKeepAlive) isClientStream() {}

// Echo-back marker for deterministic test pipelines.
type ClientStreamMemberSync struct {
	Value ClientSync

	noSmithyDocumentSerde
}

func (*ClientStreamMemberSync) isClientStream() {}

// In-message metadata. Distinct from the per-session WsMetadata — this describes
// only this Results frame. Inlined per LISTEN-013(was flatten in Rust).
type InterimMetadata struct {
	Extra map[string]string `json:"extra,omitempty"`

	ModelInfo *ModelInfo `json:"model_info,omitempty"`

	ModelUuid *string `json:"model_uuid,omitempty"`

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	RequestId *string `json:"request_id,omitempty"`

	noSmithyDocumentSerde
}

type StreamInput struct {
	Channels *int32 `json:"-"`

	// Deprecated: Legacy flag. Prefer diarize_model for explicit model selection.
	// Mutually exclusive with diarize_model .
	Diarize *bool `json:"-"`

	// Deprecated: Legacy diarization-model selector. Prefer diarize_model .
	DiarizeVersion *string `json:"-"`

	Encoding *string `json:"-"`

	Endpointing *int32 `json:"-"`

	InterimResults *bool `json:"-"`

	Keyterm []string `json:"-"`

	Keywords []string `json:"-"`

	// BCP-47 language code. Examples: en , en-US , es , pt-BR .
	Language *string `json:"-"`

	// Deprecated: Prefer mip_opt_out . log_data is recognized for backward
	// compatibility.
	LogData *bool `json:"-"`

	MipOptOut *bool `json:"-"`

	// A model identifier (e.g. nova-3-general , nova-2-medical ). Free-form string;
	// the set evolves. Documented in
	// https://developers.deepgram.com/docs/models-languages-overview.
	Model *string `json:"-"`

	Multichannel *bool `json:"-"`

	ProfanityFilter *bool `json:"-"`

	Punctuate *bool `json:"-"`

	Redact []string `json:"-"`

	SampleRate *int32 `json:"-"`

	Search []string `json:"-"`

	SecWebSocketProtocol *string `json:"-"`

	SmartFormat *bool `json:"-"`

	Tag []string `json:"-"`

	UtteranceEndMs *int32 `json:"-"`

	VadEvents *bool `json:"-"`

	// Deprecated: Use endpointing instead. Rejected when endpointing is also set as
	// an integer.
	VadTurnoff *int32 `json:"-"`

	Version *string `json:"-"`

	noSmithyDocumentSerde
}

// Mid-stream error. See LISTEN-006 for the unusual flat-on-wire representation:
//
//	{ "type": "Error", "variant": "Closing", "code": "NET-0001", "description":
//	"..." }
//
//	{ "type": "Error", "variant": "SchemaError", "description": "...", "message":
//	"..." }
//
// We model this as a single flat structure with a discriminator member — NOT as a
// nested union — because the wire is flat. Codegen handles the branching.
type WsError struct {

	// Discriminator between the two error shapes.
	//
	// This member is required.
	Variant WsErrorVariant `json:"variant"`

	// Stable error code. Present when variant=Closing . Documented values: NET-0001
	// (ClientTimeout), NET-0000 (DriverTimeout), DATA-0000 (CodecError).
	Code *string `json:"code,omitempty"`

	// Human-readable description. Present in both variants.
	Description *string `json:"description,omitempty"`

	// Additional context. Present when variant=SchemaError — the offending message
	// text.
	Message *string `json:"message,omitempty"`

	noSmithyDocumentSerde
}

// Final per-session metadata. Always emitted at session end before the close
// frame.
type WsMetadata struct {

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`

	// Number of audio channels.
	Channels *int32 `json:"channels,omitempty"`

	// Total number of audio samples processed.
	Created *string `json:"created,omitempty"`

	// Wall-clock-relative duration of audio processed in seconds.
	Duration *float32 `json:"duration,omitempty"`

	// Free-form integration data echoed back from the request.
	Extra map[string]string `json:"extra,omitempty"`

	// Models that produced the transcript.
	ModelInfo map[string]ModelInfo `json:"model_info,omitempty"`

	// SHA fingerprint of the wire-protocol schema used to encode this response.
	Sha256 *string `json:"sha256,omitempty"`

	// Always serialized as the literal string "deprecated" . Retained for legacy
	// clients with strict-schema deserializers. Use request_id .
	//
	// Deprecated: Field is always the literal string "deprecated". Use request_id for
	// debug correlation.
	TransactionKey *string `json:"transaction_key,omitempty"`

	// Server-emitted warnings (deprecation notices, fallbacks).
	Warnings []Warning `json:"warnings,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"Results", ...} . The body of the message is the StreamingResponse shape
// inlined at the top level of the JSON object.
type StreamingResponse struct {

	// One channel of a transcript. Multichannel responses contain one of these per
	// audio channel; mono contains exactly one. REST ResponseResults carries a list
	// of these; WSS StreamingResponse carries exactly one (selected by channel_index ).
	//
	// This member is required.
	Channel *Channel `json:"channel"`

	// [index, total] — which of the multichannel set this result belongs to.
	//
	// This member is required.
	ChannelIndex []int16 `json:"channel_index"`

	// Duration of the audio segment this result covers, in seconds.
	//
	// This member is required.
	Duration *float32 `json:"duration"`

	// true if this Results message was emitted in response to a client Finalize
	// message; false for normal endpointing.
	//
	// This member is required.
	FromFinalize *bool `json:"from_finalize"`

	// true if this is the final result for the segment; false for interim.
	//
	// This member is required.
	IsFinal *bool `json:"is_final"`

	// In-message metadata. Distinct from the per-session WsMetadata — this describes
	// only this Results frame. Inlined per LISTEN-013(was flatten in Rust).
	//
	// This member is required.
	Metadata *InterimMetadata `json:"metadata"`

	// Offset from session start of the start of this segment, in seconds.
	//
	// This member is required.
	Start *float32 `json:"start"`

	// Detected entities (only when ?detect_entities=true ).
	Entities []Entity `json:"entities,omitempty"`

	// true if the segment has finalized due to speech end (e.g. a long pause); false
	// if it's a periodic interim update; absent if the server made no determination.
	// See LISTEN-008.
	SpeechFinal *bool `json:"speech_final,omitempty"`

	// Caller-supplied tag echoed back. Tags via ?tag=... query parameter.
	Tag *string `json:"tag,omitempty"`

	noSmithyDocumentSerde
}

// {"type":"SpeechStarted","channel":[i,t],"timestamp":<float>} .
type SpeechStarted struct {

	// [index, total] pair that Deepgram uses to identify a channel in a multichannel
	// transcript. On the wire today this is a 2-element JSON array (e.g. [0, 1] ). See
	// divergence-log entry LISTEN-007 for the rationale and the long-term cleanup
	// target.
	//
	// This member is required.
	Channel []int16 `json:"channel"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Timestamp *float32 `json:"timestamp"`

	noSmithyDocumentSerde
}

// {"type":"Sync","id":<u64>} .
type ServerSync struct {

	// This member is required.
	Id *int64 `json:"id"`

	noSmithyDocumentSerde
}

// {"type":"UtteranceEnd","channel":[i,t],"last_word_end":<float>} .
type UtteranceEnd struct {

	// [index, total] pair that Deepgram uses to identify a channel in a multichannel
	// transcript. On the wire today this is a 2-element JSON array (e.g. [0, 1] ). See
	// divergence-log entry LISTEN-007 for the rationale and the long-term cleanup
	// target.
	//
	// This member is required.
	Channel []int16 `json:"channel"`

	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	LastWordEnd *float32 `json:"last_word_end"`

	noSmithyDocumentSerde
}

// Server → Client message stream. All variants are JSON text frames.
//
// The server NEVER sends binary frames on this direction.
//
// The following types satisfy this interface:
//
//	ServerStreamMemberError
//	ServerStreamMemberMetadata
//	ServerStreamMemberResults
//	ServerStreamMemberSpeechStarted
//	ServerStreamMemberSync
//	ServerStreamMemberUtteranceEnd
type ServerStream interface {
	isServerStream()
}

// Error condition. May be sent mid-stream (e.g. malformed client JSON) or
// immediately preceding a close frame (when ?debug=true ).
type ServerStreamMemberError struct {
	Value WsError

	noSmithyDocumentSerde
}

func (*ServerStreamMemberError) isServerStream() {}

// Per-session metadata. Always emitted at session end.
type ServerStreamMemberMetadata struct {
	Value WsMetadata

	noSmithyDocumentSerde
}

func (*ServerStreamMemberMetadata) isServerStream() {}

// Interim or final transcription result.
type ServerStreamMemberResults struct {
	Value StreamingResponse

	noSmithyDocumentSerde
}

func (*ServerStreamMemberResults) isServerStream() {}

// Speech-detected signal (only when ?vad_events=true ).
type ServerStreamMemberSpeechStarted struct {
	Value SpeechStarted

	noSmithyDocumentSerde
}

func (*ServerStreamMemberSpeechStarted) isServerStream() {}

// Echo of a ClientSync message. Used to align test pipelines.
type ServerStreamMemberSync struct {
	Value ServerSync

	noSmithyDocumentSerde
}

func (*ServerStreamMemberSync) isServerStream() {}

// VAD-driven utterance boundary signal.
type ServerStreamMemberUtteranceEnd struct {
	Value UtteranceEnd

	noSmithyDocumentSerde
}

func (*ServerStreamMemberUtteranceEnd) isServerStream() {}

type StreamOutput struct {
	SecWebSocketProtocol *string `json:"-"`

	noSmithyDocumentSerde
}

// JSON request body for /v1/read . Exactly one of text or url must be set —
// Smithy cannot express "exactly one of", so it is enforced server-side (sending
// neither or both returns a 400). See READ-004.
type ReadTextSource struct {

	// Inline text to analyze.
	Text *string `json:"text,omitempty"`

	// HTTPS URL Deepgram fetches the text document from.
	Url *string `json:"url,omitempty"`

	noSmithyDocumentSerde
}

// POST /v1/read accepts the input text in one of two body shapes selected by
// Content-Type . See READ-004.
//
// The following types satisfy this interface:
//
//	ReadRequestBodyMemberSource
//	ReadRequestBodyMemberText
type ReadRequestBody interface {
	isReadRequestBody()
}

// JSON envelope carrying inline text or a URL to fetch text from. Content-Type:
// application/json selects this variant.
type ReadRequestBodyMemberSource struct {
	Value ReadTextSource

	noSmithyDocumentSerde
}

func (*ReadRequestBodyMemberSource) isReadRequestBody() {}

// Raw text. Sent with Content-Type: text/plain (or no Content-Type ).
type ReadRequestBodyMemberText struct {
	Value string

	noSmithyDocumentSerde
}

func (*ReadRequestBodyMemberText) isReadRequestBody() {}

type AnalyzeInput struct {

	// Language of the input text. Must begin with en (English-only today); other
	// values are rejected with a 400.
	//
	// This member is required.
	Language *string `json:"-"`

	// POST /v1/read accepts the input text in one of two body shapes selected by
	// Content-Type . See READ-004.
	Body ReadRequestBody `json:"-"`

	// Where to deliver the completed analysis. When set, the operation returns
	// immediately with only requestId populated; results are delivered to this URL.
	Callback *string `json:"-"`

	// HTTP method to use for callback delivery. Default POST .
	CallbackMethod CallbackMethod `json:"-"`

	ContentType *string `json:"-"`

	// Custom intents to bias detection toward. Wire syntax is repeated
	// ?custom_intent=... . Max 100 entries, each <= 120 chars.
	CustomIntent []string `json:"-"`

	// Detection strictness for custom intents. See READ-003.
	CustomIntentMode *string `json:"-"`

	// Custom topics to bias detection toward. Wire syntax is repeated
	// ?custom_topic=... . Max 100 entries, each <= 120 chars.
	CustomTopic []string `json:"-"`

	// Detection strictness for custom topics.
	CustomTopicMode *string `json:"-"`

	// Enable intent detection.
	Intents *bool `json:"-"`

	// Deprecated: Prefer mip_opt_out . log_data is recognized for backward
	// compatibility; sending both with conflicting values returns 400.
	LogData *bool `json:"-"`

	// Opt out of the Model Improvement Program (request not persisted for training).
	MipOptOut *bool `json:"-"`

	// Enable sentiment analysis.
	Sentiment *bool `json:"-"`

	// Enable summarization. Accepts true or a version string (e.g. v2 ); modeled as
	// String to carry both forms, matching Listen's summarize .
	Summarize *string `json:"-"`

	// Tags echoed back in the response metadata. Repeated ?tag= .
	Tag []string `json:"-"`

	// Enable topic detection.
	Topics *bool `json:"-"`

	noSmithyDocumentSerde
}

type ReadMetadata struct {

	// This member is required.
	Created *string `json:"created"`

	// Always en today.
	//
	// This member is required.
	Language *string `json:"language"`

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`

	// Token-count metadata for intent detection. Present when intents ran.
	IntentsInfo *TokenMetadata `json:"intents_info,omitempty"`

	// Token-count metadata for sentiment analysis. Present when sentiment ran.
	SentimentInfo *TokenMetadata `json:"sentiment_info,omitempty"`

	// Token-count metadata for summarization. Present when summarization ran.
	SummaryInfo *TokenMetadata `json:"summary_info,omitempty"`

	// Tags echoed back from the request's ?tag= parameters.
	Tags []string `json:"tags,omitempty"`

	// Token-count metadata for topic detection. Present when topics ran.
	TopicsInfo *TokenMetadata `json:"topics_info,omitempty"`

	noSmithyDocumentSerde
}

type IntentSegment struct {

	// This member is required.
	EndWord *int32 `json:"end_word"`

	// This member is required.
	Intents []Intent `json:"intents"`

	// This member is required.
	StartWord *int32 `json:"start_word"`

	// This member is required.
	Text *string `json:"text"`

	noSmithyDocumentSerde
}

type IntentsResult struct {

	// This member is required.
	Segments []IntentSegment `json:"segments"`

	noSmithyDocumentSerde
}

// Aggregate sentiment across the whole document. Read-prefixed to avoid a name
// collision with com.deepgram.api.v1.listen#AverageSentiment (a different shape)
// in the shared generated api/types . See READ-006.
type ReadAverageSentiment struct {

	// This member is required.
	Sentiment Sentiment `json:"sentiment"`

	// Range [-1, 1].
	//
	// This member is required.
	SentimentScore *float32 `json:"sentiment_score"`

	// See startTime .
	EndTime *float32 `json:"end_time,omitempty"`

	// Always null on Read responses; carried for shape-compatibility with the
	// streaming sentiment aggregate.
	StartTime *float32 `json:"start_time,omitempty"`

	noSmithyDocumentSerde
}

type SentimentsResult struct {

	// Aggregate sentiment across the whole document. Read-prefixed to avoid a name
	// collision with com.deepgram.api.v1.listen#AverageSentiment (a different shape)
	// in the shared generated api/types . See READ-006.
	//
	// This member is required.
	Average *ReadAverageSentiment `json:"average"`

	// This member is required.
	Segments []SitSentimentSegment `json:"segments"`

	noSmithyDocumentSerde
}

type SummaryResult struct {

	// This member is required.
	Text *string `json:"text"`

	noSmithyDocumentSerde
}

type TopicsResult struct {

	// Topic detections per text segment. Reuses the cross-product TopicSegment shape
	// (identical wire form to Listen's batch topics).
	//
	// This member is required.
	Segments []TopicSegment `json:"segments"`

	noSmithyDocumentSerde
}

type ReadResults struct {

	// Present when ?intents=true .
	Intents *IntentsResult `json:"intents,omitempty"`

	// Present when ?sentiment=true .
	Sentiments *SentimentsResult `json:"sentiments,omitempty"`

	// Present when ?summarize=... was enabled.
	Summary *SummaryResult `json:"summary,omitempty"`

	// Present when ?topics=true .
	Topics *TopicsResult `json:"topics,omitempty"`

	noSmithyDocumentSerde
}

// Read response.
//
// Synchronous responses carry metadata + results . When ?callback= is set, the
// immediate response carries only requestId , and the full result is delivered
// later to the callback URL with the same shape. See READ-001.
type AnalyzeOutput struct {

	// Populated on synchronous responses. Absent on the async ack.
	Metadata *ReadMetadata

	// Populated only on the asynchronous (callback) immediate ack: {"request_id":
	// "..."} . On synchronous responses the request id is inside metadata.requestId
	// instead.
	RequestId *string

	// Populated on synchronous responses. Absent on the async ack.
	Results *ReadResults

	noSmithyDocumentSerde
}

// JSON request body for /v1/speak . Exactly one of text or url must be set
// (enforced server-side; Smithy cannot express "exactly one of").
type SpeakTextSource struct {

	// Inline text to synthesize.
	Text *string `json:"text,omitempty"`

	// HTTPS URL Deepgram fetches the text document from.
	Url *string `json:"url,omitempty"`

	noSmithyDocumentSerde
}

// POST /v1/speak accepts the input text in one of two body shapes selected by
// Content-Type (same pattern as Read; see READ-004).
//
// The following types satisfy this interface:
//
//	SpeakRequestBodyMemberSource
//	SpeakRequestBodyMemberText
type SpeakRequestBody interface {
	isSpeakRequestBody()
}

// JSON envelope carrying inline text or a URL to fetch text from. Content-Type:
// application/json selects this variant.
type SpeakRequestBodyMemberSource struct {
	Value SpeakTextSource

	noSmithyDocumentSerde
}

func (*SpeakRequestBodyMemberSource) isSpeakRequestBody() {}

// Raw text. Content-Type: text/plain (or no Content-Type ).
type SpeakRequestBodyMemberText struct {
	Value string

	noSmithyDocumentSerde
}

func (*SpeakRequestBodyMemberText) isSpeakRequestBody() {}

type SynthesizeInput struct {

	// Output bit rate (bps). Valid for mp3 / opus / aac only.
	BitRate *int32 `json:"-"`

	// POST /v1/speak accepts the input text in one of two body shapes selected by
	// Content-Type (same pattern as Read; see READ-004).
	Body SpeakRequestBody `json:"-"`

	// Where to deliver the synthesized audio. When set, the operation returns
	// {"request_id": ...} immediately and POSTs/PUTs the audio to this URL. See
	// SPEAK-002.
	Callback *string `json:"-"`

	// HTTP method for callback delivery. Default POST .
	CallbackMethod CallbackMethod `json:"-"`

	// Output container. Valid values depend on encoding (e.g. wav / none for
	// linear16, ogg for opus).
	Container SpeakContainer `json:"-"`

	ContentType *string `json:"-"`

	// Output audio codec. Default mp3 .
	Encoding SpeakEncoding `json:"-"`

	// Opt out of the Model Improvement Program.
	MipOptOut *bool `json:"-"`

	// Voice model, formatted {tier}-{voice}-{language} (e.g. aura-2-asteria-en ).
	// Default aura-asteria-en .
	Model *string `json:"-"`

	// Output sample rate (Hz). Valid values depend on encoding .
	SampleRate *int32 `json:"-"`

	// Playback speed multiplier (e.g. 1.0 , 1.5 ).
	Speed *float32 `json:"-"`

	// Tags echoed back in dg-* response metadata. Repeated ?tag= .
	Tag []string `json:"-"`

	noSmithyDocumentSerde
}

// Synchronous Speak response: the body is the synthesized audio; format and model
// metadata travel in response headers.
type SynthesizeOutput struct {

	// Comma-separated additional model UUIDs, when applicable.
	AdditionalModelUuids *string `json:"-"`

	// The synthesized audio bytes.
	//
	// This value conforms to the media type: audio/*
	Audio []byte `json:"-"`

	// Count of pronunciation break tokens applied.
	BreaksApplied *int32 `json:"-"`

	// Number of input characters (UTF-8 chars).
	CharCount *int32 `json:"-"`

	// Audio MIME type (e.g. audio/mpeg , audio/wav , audio/ogg ), derived from
	// encoding + container .
	ContentType *string `json:"-"`

	// Model used (e.g. aura-2-asteria-en ).
	ModelName *string `json:"-"`

	ModelUuid *string `json:"-"`

	// Count of pronunciation override tokens applied.
	PronunciationsApplied *int32 `json:"-"`

	// Comma-separated pronunciation-validation warning codes ( PRON-00x ), when
	// present.
	Warnings *string `json:"-"`

	noSmithyDocumentSerde
}

// Audio frame variant. The wire form is a binary WS frame whose body is data .
// @eventPayload marks the binary payload (per AWS event-stream conventions); the
// custom WebSocket protocol generator emits it as a WS binary frame.
type SpeakAudioFrame struct {

	// Raw synthesized audio bytes (per the session's encoding ).
	//
	// This member is required.
	Data []byte `json:"data"`

	noSmithyDocumentSerde
}

// {"type":"AudioMetadata", ...} . Only when ?performance=true .
type SpeakAudioMetadata struct {

	// This member is required.
	ContentType *string `json:"content_type"`

	// This member is required.
	InputNumChars *int32 `json:"input_num_chars"`

	// This member is required.
	InputText *string `json:"input_text"`

	// Latency in milliseconds.
	//
	// This member is required.
	LatencyMilliseconds *int64 `json:"latency_milliseconds"`

	noSmithyDocumentSerde
}

// {"type":"Clear"} .
type SpeakClear struct {
	noSmithyDocumentSerde
}

// {"type":"Cleared","sequence_id":<u64>} .
type SpeakCleared struct {

	// This member is required.
	SequenceId *int64 `json:"sequence_id"`

	noSmithyDocumentSerde
}

// {"type":"Close"} .
type SpeakClose struct {
	noSmithyDocumentSerde
}

// {"type":"Flush"} .
type SpeakFlush struct {
	noSmithyDocumentSerde
}

// {"type":"Speak","text":"..."} .
type SpeakText struct {

	// Text to synthesize. An empty/absent value is treated as empty text.
	//
	// This member is required.
	Text *string `json:"text"`

	noSmithyDocumentSerde
}

// Client → Server message stream. All variants are JSON text frames whose type
// field discriminates the variant. The client never sends binary.
//
// The following types satisfy this interface:
//
//	SpeakClientStreamMemberClear
//	SpeakClientStreamMemberClose
//	SpeakClientStreamMemberFlush
//	SpeakClientStreamMemberSpeak
type SpeakClientStream interface {
	isSpeakClientStream()
}

// Discard buffered text and any in-flight synthesis.
type SpeakClientStreamMemberClear struct {
	Value SpeakClear

	noSmithyDocumentSerde
}

func (*SpeakClientStreamMemberClear) isSpeakClientStream() {}

// Cleanly close the session.
type SpeakClientStreamMemberClose struct {
	Value SpeakClose

	noSmithyDocumentSerde
}

func (*SpeakClientStreamMemberClose) isSpeakClientStream() {}

// Synthesize and emit all buffered text immediately.
type SpeakClientStreamMemberFlush struct {
	Value SpeakFlush

	noSmithyDocumentSerde
}

func (*SpeakClientStreamMemberFlush) isSpeakClientStream() {}

// Enqueue text for synthesis.
type SpeakClientStreamMemberSpeak struct {
	Value SpeakText

	noSmithyDocumentSerde
}

func (*SpeakClientStreamMemberSpeak) isSpeakClientStream() {}

// {"type":"Flushed","sequence_id":<u64>} .
type SpeakFlushed struct {

	// This member is required.
	SequenceId *int64 `json:"sequence_id"`

	noSmithyDocumentSerde
}

type SpeakStreamInput struct {

	// Automatically flush buffered audio. Default true . Streaming-only.
	AutoFlush *bool `json:"-"`

	// Webhook URL for completion callback.
	Callback *string `json:"-"`

	// HTTP method for callback delivery. Default POST .
	CallbackMethod CallbackMethod `json:"-"`

	// Output codec. Streaming supports linear16 / mulaw / alaw .
	Encoding SpeakEncoding `json:"-"`

	// Opt out of the Model Improvement Program.
	MipOptOut *bool `json:"-"`

	// Voice model (e.g. aura-2-asteria-en ). Default aura-asteria-en .
	Model *string `json:"-"`

	// Output sample rate (Hz). Valid values depend on encoding .
	SampleRate *int32 `json:"-"`

	SecWebSocketProtocol *string `json:"-"`

	// Playback speed multiplier.
	Speed *float32 `json:"-"`

	// Tags echoed back. Repeated ?tag= .
	Tag []string `json:"-"`

	noSmithyDocumentSerde
}

// {"type":"Metadata", ...} .
type SpeakMetadata struct {

	// This member is required.
	AdditionalModelUuids []string `json:"additional_model_uuids"`

	// This member is required.
	ModelName *string `json:"model_name"`

	// This member is required.
	ModelUuid *string `json:"model_uuid"`

	// This member is required.
	ModelVersion *string `json:"model_version"`

	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`

	noSmithyDocumentSerde
}

// {"type":"Timestamp", ...} . Only when ?performance=true .
type SpeakTimestamp struct {

	// This member is required.
	Event SpeakTimestampEvent `json:"event"`

	// Milliseconds from session start.
	//
	// This member is required.
	MillisecondsFromStart *int64 `json:"milliseconds_from_start"`

	noSmithyDocumentSerde
}

// {"type":"Warning","warn_code":"...","warn_msg":"..."} .
type SpeakWarning struct {

	// This member is required.
	WarnCode *string `json:"warn_code"`

	// This member is required.
	WarnMsg *string `json:"warn_msg"`

	noSmithyDocumentSerde
}

// Server → Client message stream. Synthesized audio rides as binary frames ( audio
// variant); status messages ride as JSON text frames whose type field
// discriminates the variant.
//
// The following types satisfy this interface:
//
//	SpeakServerStreamMemberAudio
//	SpeakServerStreamMemberAudioMetadata
//	SpeakServerStreamMemberCleared
//	SpeakServerStreamMemberFlushed
//	SpeakServerStreamMemberMetadata
//	SpeakServerStreamMemberTimestamp
//	SpeakServerStreamMemberWarning
type SpeakServerStream interface {
	isSpeakServerStream()
}

// Synthesized audio bytes. Sent as a binary WebSocket frame, NOT JSON.
type SpeakServerStreamMemberAudio struct {
	Value SpeakAudioFrame

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberAudio) isSpeakServerStream() {}

// Per-flush audio metadata. Only when ?performance=true .
type SpeakServerStreamMemberAudioMetadata struct {
	Value SpeakAudioMetadata

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberAudioMetadata) isSpeakServerStream() {}

// Acknowledges a client Clear .
type SpeakServerStreamMemberCleared struct {
	Value SpeakCleared

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberCleared) isSpeakServerStream() {}

// Acknowledges a client Flush .
type SpeakServerStreamMemberFlushed struct {
	Value SpeakFlushed

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberFlushed) isSpeakServerStream() {}

// Per-session metadata. Emitted at the start of synthesis.
type SpeakServerStreamMemberMetadata struct {
	Value SpeakMetadata

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberMetadata) isSpeakServerStream() {}

// Latency timestamp event. Only when ?performance=true .
type SpeakServerStreamMemberTimestamp struct {
	Value SpeakTimestamp

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberTimestamp) isSpeakServerStream() {}

// Non-fatal warning (e.g. pronunciation/control validation).
type SpeakServerStreamMemberWarning struct {
	Value SpeakWarning

	noSmithyDocumentSerde
}

func (*SpeakServerStreamMemberWarning) isSpeakServerStream() {}

type SpeakStreamOutput struct {
	SecWebSocketProtocol *string `json:"-"`

	noSmithyDocumentSerde
}
