// Code generated by smithy-go-codegen DO NOT EDIT.


package types

import (
	"github.com/deepgram/spec-mock-go-sdk/api/document"
)

type Entity struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`
	
	// This member is required.
	EndWord *int32 `json:"end_word"`
	
	// This member is required.
	Label *string `json:"label"`
	
	// This member is required.
	StartWord *int32 `json:"start_word"`
	
	// This member is required.
	Value *string `json:"value"`
	
	// Original non-formatted text as spoken. Present when smart-formatting rewrote
	// value ; absent when no rewrite happened. Stem-side Option<String> .
	RawValue *string `json:"raw_value,omitempty"`
	
	noSmithyDocumentSerde
}

type Sentence struct {
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	// This member is required.
	Text *string `json:"text"`
	
	// Per-sentence sentiment.
	Sentiment Sentiment `json:"sentiment,omitempty"`
	
	SentimentScore *float32 `json:"sentiment_score,omitempty"`
	
	noSmithyDocumentSerde
}

type Paragraph struct {
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`
	
	// This member is required.
	NumWords *int32 `json:"num_words"`
	
	// This member is required.
	Sentences []Sentence `json:"sentences"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	// Channel index when the paragraph aggregates across multiple channels
	// (multichannel batch responses). Stem-side Option<i64> .
	Channel *int64 `json:"channel,omitempty"`
	
	// Per-paragraph sentiment when ?sentiment=true . Flattens to sentiment +
	// sentiment_score on the Paragraph object.
	Sentiment Sentiment `json:"sentiment,omitempty"`
	
	SentimentScore *float32 `json:"sentiment_score,omitempty"`
	
	// Speaker assignment for the paragraph (when diarized). Stem-side Option<i64> .
	Speaker *int64 `json:"speaker,omitempty"`
	
	noSmithyDocumentSerde
}

// Paragraph segmentation wrapper.
type Paragraphs struct {
	
	// This member is required.
	Paragraphs []Paragraph `json:"paragraphs"`
	
	Transcript *string `json:"transcript,omitempty"`
	
	noSmithyDocumentSerde
}

// Phoneme-level word. Used in pronunciation analysis features.
type PhonemeWord struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`
	
	// This member is required.
	Phoneme *string `json:"phoneme"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	noSmithyDocumentSerde
}

type SitSentimentSegment struct {
	
	// This member is required.
	EndWord *int32 `json:"end_word"`
	
	// This member is required.
	Sentiment Sentiment `json:"sentiment"`
	
	// This member is required.
	SentimentScore *float32 `json:"sentiment_score"`
	
	// This member is required.
	StartWord *int32 `json:"start_word"`
	
	Text *string `json:"text,omitempty"`
	
	noSmithyDocumentSerde
}

type Summary struct {
	
	// This member is required.
	EndWord *int32 `json:"end_word"`
	
	// This member is required.
	StartWord *int32 `json:"start_word"`
	
	// This member is required.
	Summary *string `json:"summary"`
	
	noSmithyDocumentSerde
}

type Topic struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	ConfidenceScore *float32 `json:"confidence_score"`
	
	// This member is required.
	Topic *string `json:"topic"`
	
	noSmithyDocumentSerde
}

type TopicSegment struct {
	
	// This member is required.
	EndWord *int32 `json:"end_word"`
	
	// This member is required.
	StartWord *int32 `json:"start_word"`
	
	// This member is required.
	Text *string `json:"text"`
	
	// This member is required.
	Topics []Topic `json:"topics"`
	
	noSmithyDocumentSerde
}

type Translation struct {
	
	// BCP-47 language code. Examples: en , en-US , es , pt-BR .
	//
	// This member is required.
	Language *string `json:"language"`
	
	// This member is required.
	Translation *string `json:"translation"`
	
	noSmithyDocumentSerde
}

// One word in the transcript. Many fields are conditionally present depending on
// the requested features.
type Word struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	// Lowercased dictionary form.
	//
	// This member is required.
	Word *string `json:"word"`
	
	// Raw bytes attached to this word. Stem-side Option<Vec<u8>> ; used internally and
	// only sometimes surfaced on the wire. Modeled as Blob because Smithy Blob ↔ Rust
	// Vec<u8> is the canonical pair.
	Context []byte `json:"context,omitempty"`
	
	// Embedding vector. Stem-side Option<HashMap<String, f32>> (a named dictionary of
	// per-dimension floats, not a positional list).
	FullVec map[string]float32 `json:"full_vec,omitempty"`
	
	// Detected language for this word. WSS-populated when ?detect_language=true .
	Language *string `json:"language,omitempty"`
	
	// Capitalized + punctuated form (when ?punctuate=true ).
	PunctuatedWord *string `json:"punctuated_word,omitempty"`
	
	// Replacement text after ?redact=... is applied.
	RedactedText *string `json:"redacted_text,omitempty"`
	
	// Per-word sentiment, present when ?sentiment=true . Stem-side this comes from a
	// #[serde(flatten)] -ed AverageSentiment whose start_time / end_time fields are
	// forced to None when flattened into a Word (which already has its own start / end
	// ). The resulting wire shape is exactly sentiment + sentiment_score on the Word
	// object. (Inlined per LISTEN-013.)
	Sentiment Sentiment `json:"sentiment,omitempty"`
	
	SentimentScore *float32 `json:"sentiment_score,omitempty"`
	
	// Speaker label, present when ?diarize=true . Indexed from 0. Stem-side type is
	// i64 ( Option<i64> ); modeled as Long here.
	Speaker *int64 `json:"speaker,omitempty"`
	
	// Confidence in the speaker assignment. REST-populated.
	SpeakerConfidence *float32 `json:"speaker_confidence,omitempty"`
	
	// Stable speaker ID across requests when ?identify=true .
	SpeakerId *string `json:"speaker_id,omitempty"`
	
	noSmithyDocumentSerde
}

// One ranked alternative interpretation of the audio segment.
type Alternative struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`
	
	// This member is required.
	Transcript *string `json:"transcript"`
	
	// This member is required.
	Words []Word `json:"words"`
	
	// Detected entities. Present when ?detect_entities=true .
	Entities []Entity `json:"entities,omitempty"`
	
	// Languages detected in this alternative. Mostly populated when
	// ?detect_language=true .
	Languages []string `json:"languages,omitempty"`
	
	// Paragraph segmentation. Present when ?paragraphs=true or when smart formatting
	// groups the transcript.
	Paragraphs *Paragraphs `json:"paragraphs,omitempty"`
	
	// Phoneme-level annotations. Rare; present when ?phoneme_lattice=true .
	Phonemes []PhonemeWord `json:"phonemes,omitempty"`
	
	// Sentiment segments inline with the alternative, when ?sentiment=true .
	SentimentSegments []SitSentimentSegment `json:"sentiment_segments,omitempty"`
	
	Summaries []Summary `json:"summaries,omitempty"`
	
	// Topic tags inline with the alternative, when ?topics=true .
	Topics []TopicSegment `json:"topics,omitempty"`
	
	// Translations of the transcript, when applicable.
	Translations []Translation `json:"translations,omitempty"`
	
	noSmithyDocumentSerde
}

type Hit struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	// Matched text snippet. Stem-side Option<String> .
	Snippet *string `json:"snippet,omitempty"`
	
	noSmithyDocumentSerde
}

type SearchResult struct {
	
	// This member is required.
	Hits []Hit `json:"hits"`
	
	// This member is required.
	Query *string `json:"query"`
	
	noSmithyDocumentSerde
}

// One channel of a transcript. Multichannel responses contain one of these per
// audio channel; mono contains exactly one. REST ResponseResults carries a list
// of these; WSS StreamingResponse carries exactly one (selected by channel_index ).
type Channel struct {
	
	// This member is required.
	Alternatives []Alternative `json:"alternatives"`
	
	// Detected language for this channel. Present when ?detect_language=true .
	DetectedLanguage *string `json:"detected_language,omitempty"`
	
	// Confidence in the detected language. Range [0, 1].
	LanguageConfidence *float32 `json:"language_confidence,omitempty"`
	
	// Phrase-search hits. Empty when no ?search= queries were submitted.
	Search []SearchResult `json:"search,omitempty"`
	
	// Per-channel utterance segment boundaries. Present when ?utterances=true . Stem
	// models this as a UttSegments newtype wrapping Vec<usize> — a flat JSON array of
	// word-indices marking the start of each utterance for this channel's first
	// alternative. The top-level Result.utterances field (REST batch only) carries
	// the richer Utterance objects.
	Utterances []int32 `json:"utterances,omitempty"`
	
	noSmithyDocumentSerde
}

type ModelInfo struct {
	
	Arch *string `json:"arch,omitempty"`
	
	Name *string `json:"name,omitempty"`
	
	Version *string `json:"version,omitempty"`
	
	noSmithyDocumentSerde
}

// Token-count metadata for AI features (summarize, sentiment, topics, intents).
// Populated on REST ResponseMetadata per-feature.
//
// Stem source: messages/src/public/v1/asr/metadata.rs — TokenMetadata . All three
// fields are required on the stem side; model is a Deepgram SDK convenience for
// the model name, while model_uuid is the canonical UUID identifier.
type TokenMetadata struct {
	
	// This member is required.
	InputTokens *int64 `json:"input_tokens"`
	
	// Stable UUID for a specific model instance. UUID v4 in canonical lowercase
	// string form. Distinct from ModelId (which is a human-readable family label like
	// nova-3-general ) — ModelUuid identifies the exact deployed model build.
	//
	// This member is required.
	ModelUuid *string `json:"model_uuid"`
	
	// This member is required.
	OutputTokens *int64 `json:"output_tokens"`
	
	// Convenience: model name. Resolved by SDK using model_uuid lookup.
	Model *string `json:"model,omitempty"`
	
	noSmithyDocumentSerde
}

type Utterance struct {
	
	// This member is required.
	Channel *int32 `json:"channel"`
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	Confidence *float32 `json:"confidence"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	End *float32 `json:"end"`
	
	// Stable utterance UUID. Stem-side this is a required Uuid (NOT optional).
	// Allocated server-side per utterance.
	//
	// This member is required.
	Id *string `json:"id"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	// This member is required.
	Transcript *string `json:"transcript"`
	
	// This member is required.
	Words []Word `json:"words"`
	
	// Languages detected in this utterance, ranked most-to-least frequent. Stem-side
	// Vec<String> ; populated when words have language set.
	Languages []string `json:"languages,omitempty"`
	
	// Per-utterance sentiment, flattens to sentiment + sentiment_score on the
	// Utterance object.
	Sentiment Sentiment `json:"sentiment,omitempty"`
	
	SentimentScore *float32 `json:"sentiment_score,omitempty"`
	
	// Speaker label. Stem-side Option<i64> .
	Speaker *int64 `json:"speaker,omitempty"`
	
	noSmithyDocumentSerde
}

type Warning struct {
	
	// This member is required.
	Message *string `json:"message"`
	
	// This member is required.
	Parameter *string `json:"parameter"`
	
	// This member is required.
	Type WarningType `json:"type"`
	
	noSmithyDocumentSerde
}

type SentimentAggregate struct {
	
	// This member is required.
	Sentiment Sentiment `json:"sentiment"`
	
	// This member is required.
	SentimentScore *float32 `json:"sentiment_score"`
	
	noSmithyDocumentSerde
}

type AverageSentiment struct {
	
	// This member is required.
	Average *SentimentAggregate `json:"average"`
	
	noSmithyDocumentSerde
}

type Intent struct {
	
	// A confidence value in [0.0, 1.0]. Models output this for transcripts,
	// alternatives, and per-word confidences.
	//
	// This member is required.
	ConfidenceScore *float32 `json:"confidence_score"`
	
	// This member is required.
	Intent *string `json:"intent"`
	
	noSmithyDocumentSerde
}

type UrlSource struct {
	
	// HTTPS URL where Deepgram's servers can fetch the audio.
	//
	// This member is required.
	Url *string `json:"url"`
	
	noSmithyDocumentSerde
}

// POST /v1/listen accepts two request body shapes selected by Content-Type . See LISTEN-004.
//
// The following types satisfy this interface:
//  TranscribeRequestBodyMemberAudio
//  TranscribeRequestBodyMemberUrlSource
type TranscribeRequestBody interface {
	isTranscribeRequestBody()
}

// Raw audio bytes. Sent with any non-blacklisted Content-Type (audio/, video/,
// application/octet-stream — NOT text/plain or application/json or text/html,
// which are reserved/blacklisted).
type TranscribeRequestBodyMemberAudio struct {
	Value []byte
	
	noSmithyDocumentSerde
}
func (*TranscribeRequestBodyMemberAudio) isTranscribeRequestBody() {}
// JSON envelope referencing audio at a remote URL. Content-Type: application/json
// selects this variant.
type TranscribeRequestBodyMemberUrlSource struct {
	Value UrlSource
	
	noSmithyDocumentSerde
}
func (*TranscribeRequestBodyMemberUrlSource) isTranscribeRequestBody() {}

type TranscribeInput struct {
	
	// POST /v1/listen accepts two request body shapes selected by Content-Type . See LISTEN-004.
	Body TranscribeRequestBody `json:"-"`
	
	// Where to deliver the completed transcript. When set, the operation returns
	// immediately with only requestId populated; results are POSTed to this URL once
	// transcoding completes.
	Callback *string `json:"-"`
	
	// HTTP method to use for callback delivery. Default POST .
	CallbackMethod CallbackMethod `json:"-"`
	
	Channels *int32 `json:"-"`
	
	ContentType *string `json:"-"`
	
	DetectEntities *bool `json:"-"`
	
	DetectLanguage *string `json:"-"`
	
	// Deprecated: Legacy flag. Prefer diarize_model for explicit model selection.
	// diarize=true continues to work for backward compatibility but is mutually
	// exclusive with diarize_model .
	Diarize *bool `json:"-"`
	
	DiarizeModel *string `json:"-"`
	
	// Deprecated: Legacy Impeller-side diarization selector. Prefer diarize_model .
	// Mutually exclusive with diarize_model .
	DiarizeVersion *string `json:"-"`
	
	Encoding *string `json:"-"`
	
	FillerWords *bool `json:"-"`
	
	Intents *bool `json:"-"`
	
	Keyterm []string `json:"-"`
	
	Keywords []string `json:"-"`
	
	// BCP-47 language code. Examples: en , en-US , es , pt-BR .
	Language *string `json:"-"`
	
	// Deprecated: Prefer mip_opt_out . log_data is recognized for backward
	// compatibility; sending both with conflicting values returns 400.
	LogData *bool `json:"-"`
	
	MipOptOut *bool `json:"-"`
	
	// A model identifier (e.g. nova-3-general , nova-2-medical ). Free-form string;
	// the set evolves. Documented in
	// https://developers.deepgram.com/docs/models-languages-overview.
	Model *string `json:"-"`
	
	Multichannel *bool `json:"-"`
	
	Paragraphs *bool `json:"-"`
	
	ProfanityFilter *bool `json:"-"`
	
	Punctuate *bool `json:"-"`
	
	Redact []string `json:"-"`
	
	SampleRate *int32 `json:"-"`
	
	Search []string `json:"-"`
	
	Sentiment *bool `json:"-"`
	
	SmartFormat *bool `json:"-"`
	
	Summarize *string `json:"-"`
	
	Tag []string `json:"-"`
	
	Tier *string `json:"-"`
	
	Topics *bool `json:"-"`
	
	Utterances *bool `json:"-"`
	
	// Deprecated: Use endpointing instead. vad_turnoff is rejected when endpointing
	// is also an integer; if only vad_turnoff is set it is silently mapped onto
	// endpointing .
	VadTurnoff *int32 `json:"-"`
	
	Version *string `json:"-"`
	
	noSmithyDocumentSerde
}

type ResponseMetadata struct {
	
	// This member is required.
	Channels *int32 `json:"channels"`
	
	// This member is required.
	Created *string `json:"created"`
	
	// A duration in seconds. Always non-negative.
	//
	// This member is required.
	Duration *float32 `json:"duration"`
	
	// This member is required.
	ModelInfo map[string]ModelInfo `json:"model_info"`
	
	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`
	
	// This member is required.
	Sha256 *string `json:"sha256"`
	
	// Always serialized as the literal string "deprecated" . Historically carried
	// encrypted debug context; replaced by request_id . Retained in the response body
	// so legacy clients deserializing strict schemas don't break.
	//
	// This member is required.
	//
	// Deprecated: Field is always the literal string "deprecated". Use request_id for
	// debug correlation.
	TransactionKey *string `json:"transaction_key"`
	
	Extra map[string]string `json:"extra,omitempty"`
	
	// Token-count metadata for intent detection. Present when ?intents=true .
	IntentsInfo *TokenMetadata `json:"intents_info,omitempty"`
	
	// Subset of model_info keys, retained for backward compatibility with clients
	// that parsed models before model_info existed. Prefer model_info keys directly.
	//
	// Deprecated: Subset of model_info . Use model_info keys instead.
	Models []string `json:"models,omitempty"`
	
	// Per-batch processing time in seconds. Present only when ?performance=true was
	// set on the request.
	ProcessingTime *float32 `json:"processing_time,omitempty"`
	
	// Token-count metadata for sentiment analysis. Present when ?sentiment=true .
	SentimentInfo *TokenMetadata `json:"sentiment_info,omitempty"`
	
	// Token-count metadata for summarization. Present when ?summarize=v2 .
	SummaryInfo *TokenMetadata `json:"summary_info,omitempty"`
	
	// Tags echoed back from the request's ?tag= query parameters.
	Tags []string `json:"tags,omitempty"`
	
	// Token-count metadata for topic detection. Present when ?topics=true .
	TopicsInfo *TokenMetadata `json:"topics_info,omitempty"`
	
	Warnings []Warning `json:"warnings,omitempty"`
	
	noSmithyDocumentSerde
}

type ResponseResults struct {
	
	// This member is required.
	Channels []Channel `json:"channels"`
	
	// Document-level intents (when ?intents=true ).
	Intents []Intent `json:"intents,omitempty"`
	
	// Document-level sentiments aggregate (when ?sentiment=true ).
	Sentiments *AverageSentiment `json:"sentiments,omitempty"`
	
	// Document-level summaries (when ?summarize=v2 ).
	Summary []Summary `json:"summary,omitempty"`
	
	// Document-level topics (when ?topics=true ).
	Topics []Topic `json:"topics,omitempty"`
	
	// Channel-aware utterance segmentation (when ?utterances=true ).
	Utterances []Utterance `json:"utterances,omitempty"`
	
	noSmithyDocumentSerde
}

// Transcribe response.
//
// Always carries requestId (in body and via the dg-request-id header). metadata
// and results are populated only on the synchronous path (no ?callback= ); when
// callback is set on the request, they are absent from the immediate response body
// and instead delivered later to the callback URL with the same shape.
type TranscribeOutput struct {
	
	// Always populated. Same as the dg-request-id header.
	//
	// This member is required.
	RequestId *string `json:"request_id"`
	
	// Deepgram project identifier. UUID v4. Surfaced in the dg-project-id response
	// header on authenticated requests.
	DgProjectId *string `json:"-"`
	
	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	DgRequestId *string `json:"-"`
	
	// Populated on synchronous responses. Absent on the immediate response when
	// ?callback= is set; appears in the callback delivery instead.
	Results *ResponseResults `json:"results,omitempty"`
	
	noSmithyDocumentSerde
}

// Audio frame variant. Smithy @streaming union members must be structures; the
// actual wire form is a binary WS frame whose body is data .
//
// @eventPayload marks the field as the binary payload of the event-stream frame
// (per AWS event-stream conventions); our custom WebSocket protocol generator
// interprets this as "send the bytes as a WS binary frame."
type AudioFrame struct {
	
	// Raw audio bytes (PCM, opus, etc., per the session's encoding query parameter).
	// Sent as the WS binary frame body, NOT JSON-encoded.
	//
	// This member is required.
	Data []byte `json:"data"`
	
	noSmithyDocumentSerde
}

// {"type":"CloseStream"} .
type CloseStream struct {
	
	noSmithyDocumentSerde
}

// {"type":"Configure","features":{...}} .
//
// features is an open key→value map. Values are JSON documents — the allowed keys
// evolve and aren't worth modelling exhaustively in the schema. Use the developer
// docs for the canonical list.
type Configure struct {
	
	// Map of feature name → arbitrary JSON value.
	//
	// This member is required.
	Features map[string]document.Interface `json:"features"`
	
	noSmithyDocumentSerde
}

// {"type":"Finalize","channel":<int|null>} .
//
// channel is optional — when omitted, finalize fires for every channel. On a
// single-channel session, omit it.
type Finalize struct {
	
	// 0-indexed channel to finalize. Omit for "all channels".
	Channel *int32 `json:"channel,omitempty"`
	
	noSmithyDocumentSerde
}

// {"type":"KeepAlive"} .
type KeepAlive struct {
	
	noSmithyDocumentSerde
}

// {"type":"Sync","id":<u64>} .
type ClientSync struct {
	
	// This member is required.
	Id *int64 `json:"id"`
	
	noSmithyDocumentSerde
}

// Bidirectional WS stream from client to server. Audio bytes ride as binary
// frames ( audio variant); control messages ride as JSON text frames whose type
// field discriminates the variant.
//
// The following types satisfy this interface:
//  ClientStreamMemberAudio
//  ClientStreamMemberCloseStream
//  ClientStreamMemberConfigure
//  ClientStreamMemberFinalize
//  ClientStreamMemberKeepAlive
//  ClientStreamMemberSync
type ClientStream interface {
	isClientStream()
}

// Raw audio bytes. Sent as a binary WebSocket frame, NOT as JSON. Stem forwards
// these to impeller/transcoder. An empty binary frame is treated equivalent to a
// closeStream JSON message.
type ClientStreamMemberAudio struct {
	Value AudioFrame
	
	noSmithyDocumentSerde
}
func (*ClientStreamMemberAudio) isClientStream() {}
// Graceful end-of-audio marker. Server flushes pending results and emits a final
// Metadata message before closing.
type ClientStreamMemberCloseStream struct {
	Value CloseStream
	
	noSmithyDocumentSerde
}
func (*ClientStreamMemberCloseStream) isClientStream() {}
// Update post-processor / feature configuration mid-session.
type ClientStreamMemberConfigure struct {
	Value Configure
	
	noSmithyDocumentSerde
}
func (*ClientStreamMemberConfigure) isClientStream() {}
// Force the server to emit a final transcript for the open utterance.
type ClientStreamMemberFinalize struct {
	Value Finalize
	
	noSmithyDocumentSerde
}
func (*ClientStreamMemberFinalize) isClientStream() {}
// Resets client + driver inactivity timers. Send periodically when the client has
// no audio to transmit but wants to keep the session alive.
type ClientStreamMemberKeepAlive struct {
	Value KeepAlive
	
	noSmithyDocumentSerde
}
func (*ClientStreamMemberKeepAlive) isClientStream() {}
// Echo-back marker for deterministic test pipelines.
type ClientStreamMemberSync struct {
	Value ClientSync
	
	noSmithyDocumentSerde
}
func (*ClientStreamMemberSync) isClientStream() {}

// In-message metadata. Distinct from the per-session WsMetadata — this describes
// only this Results frame. Inlined per LISTEN-013(was flatten in Rust).
type InterimMetadata struct {
	
	Extra map[string]string `json:"extra,omitempty"`
	
	ModelInfo *ModelInfo `json:"model_info,omitempty"`
	
	ModelUuid *string `json:"model_uuid,omitempty"`
	
	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	RequestId *string `json:"request_id,omitempty"`
	
	noSmithyDocumentSerde
}

type StreamInput struct {
	
	Channels *int32 `json:"-"`
	
	// Deprecated: Legacy flag. Prefer diarize_model for explicit model selection.
	// Mutually exclusive with diarize_model .
	Diarize *bool `json:"-"`
	
	DiarizeModel *string `json:"-"`
	
	// Deprecated: Legacy Impeller-side diarization selector. Prefer diarize_model .
	DiarizeVersion *string `json:"-"`
	
	Encoding *string `json:"-"`
	
	Endpointing *int32 `json:"-"`
	
	FillerWords *bool `json:"-"`
	
	InterimResults *bool `json:"-"`
	
	Keyterm []string `json:"-"`
	
	Keywords []string `json:"-"`
	
	// BCP-47 language code. Examples: en , en-US , es , pt-BR .
	Language *string `json:"-"`
	
	// Deprecated: Prefer mip_opt_out . log_data is recognized for backward
	// compatibility.
	LogData *bool `json:"-"`
	
	MipOptOut *bool `json:"-"`
	
	// A model identifier (e.g. nova-3-general , nova-2-medical ). Free-form string;
	// the set evolves. Documented in
	// https://developers.deepgram.com/docs/models-languages-overview.
	Model *string `json:"-"`
	
	Multichannel *bool `json:"-"`
	
	NoDelay *bool `json:"-"`
	
	ProfanityFilter *bool `json:"-"`
	
	Punctuate *bool `json:"-"`
	
	Redact []string `json:"-"`
	
	SampleRate *int32 `json:"-"`
	
	Search []string `json:"-"`
	
	SecWebSocketProtocol *string `json:"-"`
	
	SmartFormat *bool `json:"-"`
	
	Tag []string `json:"-"`
	
	UtteranceEndMs *int32 `json:"-"`
	
	VadEvents *bool `json:"-"`
	
	// Deprecated: Use endpointing instead. Rejected when endpointing is also set as
	// an integer.
	VadTurnoff *int32 `json:"-"`
	
	Version *string `json:"-"`
	
	noSmithyDocumentSerde
}

// Mid-stream error. See LISTEN-006 for the unusual flat-on-wire representation:
//
//     { "type": "Error", "variant": "Closing", "code": "NET-0001", "description":
//     "..." }
//
//     { "type": "Error", "variant": "SchemaError", "description": "...", "message":
//     "..." }
//
// We model this as a single flat structure with a discriminator member — NOT as a
// nested union — because the wire is flat. Codegen handles the branching.
type WsError struct {
	
	// Discriminator between the two error shapes.
	//
	// This member is required.
	Variant WsErrorVariant `json:"variant"`
	
	// Stable error code. Present when variant=Closing . Documented values: NET-0001
	// (ClientTimeout), NET-0000 (DriverTimeout), DATA-0000 (CodecError).
	Code *string `json:"code,omitempty"`
	
	// Human-readable description. Present in both variants.
	Description *string `json:"description,omitempty"`
	
	// Additional context. Present when variant=SchemaError — the offending message
	// text.
	Message *string `json:"message,omitempty"`
	
	noSmithyDocumentSerde
}

// Final per-session metadata. Always emitted at session end before the close
// frame.
type WsMetadata struct {
	
	// Deepgram request identifier, surfaced in response headers ( dg-request-id ) and
	// most response bodies. Always a UUID v4 in canonical lowercase string form (
	// 8-4-4-4-12 hex).
	//
	// This member is required.
	RequestId *string `json:"request_id"`
	
	// Number of audio channels.
	Channels *int32 `json:"channels,omitempty"`
	
	// Total number of audio samples processed.
	Created *string `json:"created,omitempty"`
	
	// Wall-clock-relative duration of audio processed in seconds.
	Duration *float32 `json:"duration,omitempty"`
	
	// Free-form integration data echoed back from the request.
	Extra map[string]string `json:"extra,omitempty"`
	
	// Models that produced the transcript.
	ModelInfo map[string]ModelInfo `json:"model_info,omitempty"`
	
	// SHA of the messages crate used to encode this response.
	Sha256 *string `json:"sha256,omitempty"`
	
	// Always serialized as the literal string "deprecated" . Retained for legacy
	// clients with strict-schema deserializers. Use request_id .
	//
	// Deprecated: Field is always the literal string "deprecated". Use request_id for
	// debug correlation.
	TransactionKey *string `json:"transaction_key,omitempty"`
	
	// Server-emitted warnings (deprecation notices, fallbacks).
	Warnings []Warning `json:"warnings,omitempty"`
	
	noSmithyDocumentSerde
}

// {"type":"Results", ...} . The body of the message is the StreamingResponse shape
// inlined at the top level of the JSON object.
type StreamingResponse struct {
	
	// One channel of a transcript. Multichannel responses contain one of these per
	// audio channel; mono contains exactly one. REST ResponseResults carries a list
	// of these; WSS StreamingResponse carries exactly one (selected by channel_index ).
	//
	// This member is required.
	Channel *Channel `json:"channel"`
	
	// [index, total] — which of the multichannel set this result belongs to.
	//
	// This member is required.
	ChannelIndex []int16 `json:"channel_index"`
	
	// Duration of the audio segment this result covers, in seconds.
	//
	// This member is required.
	Duration *float32 `json:"duration"`
	
	// true if this Results message was emitted in response to a client Finalize
	// message; false for normal endpointing.
	//
	// This member is required.
	FromFinalize *bool `json:"from_finalize"`
	
	// true if this is the final result for the segment; false for interim.
	//
	// This member is required.
	IsFinal *bool `json:"is_final"`
	
	// In-message metadata. Distinct from the per-session WsMetadata — this describes
	// only this Results frame. Inlined per LISTEN-013(was flatten in Rust).
	//
	// This member is required.
	Metadata *InterimMetadata `json:"metadata"`
	
	// Offset from session start of the start of this segment, in seconds.
	//
	// This member is required.
	Start *float32 `json:"start"`
	
	// Detected entities (only when ?detect_entities=true ).
	Entities []Entity `json:"entities,omitempty"`
	
	// true if the segment has finalized due to speech end (e.g. a long pause); false
	// if it's a periodic interim update; absent if the server made no determination.
	// See LISTEN-008.
	SpeechFinal *bool `json:"speech_final,omitempty"`
	
	// Caller-supplied tag echoed back. Tags via ?tag=... query parameter.
	Tag *string `json:"tag,omitempty"`
	
	noSmithyDocumentSerde
}

// {"type":"SpeechStarted","channel":[i,t],"timestamp":<float>} .
type SpeechStarted struct {
	
	// [index, total] pair that Deepgram uses to identify a channel in a multichannel
	// transcript. On the wire today this is a 2-element JSON array (e.g. [0, 1] ). See
	// divergence-log entry LISTEN-007 for the rationale and the long-term cleanup
	// target.
	//
	// This member is required.
	Channel []int16 `json:"channel"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	Timestamp *float32 `json:"timestamp"`
	
	noSmithyDocumentSerde
}

// {"type":"Sync","id":<u64>} .
type ServerSync struct {
	
	// This member is required.
	Id *int64 `json:"id"`
	
	noSmithyDocumentSerde
}

// {"type":"UtteranceEnd","channel":[i,t],"last_word_end":<float>} .
type UtteranceEnd struct {
	
	// [index, total] pair that Deepgram uses to identify a channel in a multichannel
	// transcript. On the wire today this is a 2-element JSON array (e.g. [0, 1] ). See
	// divergence-log entry LISTEN-007 for the rationale and the long-term cleanup
	// target.
	//
	// This member is required.
	Channel []int16 `json:"channel"`
	
	// A relative timestamp in seconds from the start of the audio session. Always
	// non-negative. Used for word start , utterance offsets, etc.
	//
	// This member is required.
	LastWordEnd *float32 `json:"last_word_end"`
	
	noSmithyDocumentSerde
}

// Server → Client message stream. All variants are JSON text frames.
//
// The server NEVER sends binary frames on this direction.
//
// The following types satisfy this interface:
//  ServerStreamMemberError
//  ServerStreamMemberMetadata
//  ServerStreamMemberResults
//  ServerStreamMemberSpeechStarted
//  ServerStreamMemberSync
//  ServerStreamMemberUtteranceEnd
type ServerStream interface {
	isServerStream()
}

// Error condition. May be sent mid-stream (e.g. malformed client JSON) or
// immediately preceding a close frame (when ?debug=true ).
type ServerStreamMemberError struct {
	Value WsError
	
	noSmithyDocumentSerde
}
func (*ServerStreamMemberError) isServerStream() {}
// Per-session metadata. Always emitted at session end.
type ServerStreamMemberMetadata struct {
	Value WsMetadata
	
	noSmithyDocumentSerde
}
func (*ServerStreamMemberMetadata) isServerStream() {}
// Interim or final transcription result.
type ServerStreamMemberResults struct {
	Value StreamingResponse
	
	noSmithyDocumentSerde
}
func (*ServerStreamMemberResults) isServerStream() {}
// Speech-detected signal (only when ?vad_events=true ).
type ServerStreamMemberSpeechStarted struct {
	Value SpeechStarted
	
	noSmithyDocumentSerde
}
func (*ServerStreamMemberSpeechStarted) isServerStream() {}
// Echo of a ClientSync message. Used to align test pipelines.
type ServerStreamMemberSync struct {
	Value ServerSync
	
	noSmithyDocumentSerde
}
func (*ServerStreamMemberSync) isServerStream() {}
// VAD-driven utterance boundary signal.
type ServerStreamMemberUtteranceEnd struct {
	Value UtteranceEnd
	
	noSmithyDocumentSerde
}
func (*ServerStreamMemberUtteranceEnd) isServerStream() {}

type StreamOutput struct {
	
	SecWebSocketProtocol *string `json:"-"`
	
	noSmithyDocumentSerde
}

