// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing multi-operation REST client, generated by
// spec-codegen-go's multi-op REST facade emitter: one method per
// operation, @httpLabel path params as args, @httpQuery as a
// per-op Options struct, @httpPayload body JSON-marshalled.

package agentsettingsv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	nethttp "net/http"
	"net/url"
	"os"
	"reflect"
	"strconv"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

const DefaultBaseURL = "https://api.deepgram.com"

type Client struct {
	apiKey, accessToken, baseURL string
	httpClient                   *nethttp.Client
}
type Option func(*Client)

func New(opts ...Option) *Client {
	c := &Client{apiKey: os.Getenv("DEEPGRAM_API_KEY"), accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"), baseURL: DefaultBaseURL, httpClient: nethttp.DefaultClient}
	for _, opt := range opts {
		opt(c)
	}
	return c
}
func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}
func WithAPIKey(apiKey string) Option { return func(c *Client) { c.apiKey = apiKey } }
func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}
func WithBaseURL(baseURL string) Option            { return func(c *Client) { c.baseURL = baseURL } }
func WithHTTPClient(client *nethttp.Client) Option { return func(c *Client) { c.httpClient = client } }

type GetThinkProviderOptions struct {
	AdditionalQueryParams url.Values `schema:"-"`
}

type ListProviderModelsOptions struct {
	AdditionalQueryParams url.Values `schema:"-"`
}

type ListThinkModelsOptions struct {
	AdditionalQueryParams url.Values `schema:"-"`
}

type ListThinkProvidersOptions struct {
	Include               string     `schema:"include,omitempty"`
	AdditionalQueryParams url.Values `schema:"-"`
}

type ValidateAgentOptions struct {
	AdditionalQueryParams url.Values `schema:"-"`
}

type ValidateSettingsOptions struct {
	AdditionalQueryParams url.Values `schema:"-"`
}

func (c *Client) GetThinkProvider(ctx context.Context, provider string, opts *GetThinkProviderOptions) (*spectypes.GetThinkProviderOutput, error) {
	input := &spectypes.GetThinkProviderInput{}
	providerV := provider
	input.Provider = &providerV
	var bodyReader io.Reader
	contentType := ""
	var additional url.Values
	if opts != nil {
		additional = optionsToQuery(opts)
	}
	return httptransport.Invoke[spectypes.GetThinkProviderInput, spectypes.GetThinkProviderOutput](ctx, c.httpClient, c.baseURL, spectypes.GetThinkProviderRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, bodyReader, additional)
}

func (c *Client) ListProviderModels(ctx context.Context, provider string, opts *ListProviderModelsOptions) (*spectypes.ListProviderModelsOutput, error) {
	input := &spectypes.ListProviderModelsInput{}
	providerV := provider
	input.Provider = &providerV
	var bodyReader io.Reader
	contentType := ""
	var additional url.Values
	if opts != nil {
		additional = optionsToQuery(opts)
	}
	return httptransport.Invoke[spectypes.ListProviderModelsInput, spectypes.ListProviderModelsOutput](ctx, c.httpClient, c.baseURL, spectypes.ListProviderModelsRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, bodyReader, additional)
}

func (c *Client) ListThinkModels(ctx context.Context, opts *ListThinkModelsOptions) (*spectypes.ListThinkModelsOutput, error) {
	input := &spectypes.ListThinkModelsInput{}
	var bodyReader io.Reader
	contentType := ""
	var additional url.Values
	if opts != nil {
		additional = optionsToQuery(opts)
	}
	return httptransport.Invoke[spectypes.ListThinkModelsInput, spectypes.ListThinkModelsOutput](ctx, c.httpClient, c.baseURL, spectypes.ListThinkModelsRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, bodyReader, additional)
}

func (c *Client) ListThinkProviders(ctx context.Context, opts *ListThinkProvidersOptions) (*spectypes.ListThinkProvidersOutput, error) {
	input := &spectypes.ListThinkProvidersInput{}
	var bodyReader io.Reader
	contentType := ""
	var additional url.Values
	if opts != nil {
		additional = optionsToQuery(opts)
	}
	return httptransport.Invoke[spectypes.ListThinkProvidersInput, spectypes.ListThinkProvidersOutput](ctx, c.httpClient, c.baseURL, spectypes.ListThinkProvidersRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, bodyReader, additional)
}

func (c *Client) ValidateAgent(ctx context.Context, agent any, opts *ValidateAgentOptions) (*spectypes.ValidateAgentOutput, error) {
	input := &spectypes.ValidateAgentInput{}
	var bodyReader io.Reader
	contentType := ""
	bb, err := json.Marshal(agent)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(bb)
	contentType = "application/json"
	var additional url.Values
	if opts != nil {
		additional = optionsToQuery(opts)
	}
	return httptransport.Invoke[spectypes.ValidateAgentInput, spectypes.ValidateAgentOutput](ctx, c.httpClient, c.baseURL, spectypes.ValidateAgentRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, bodyReader, additional)
}

func (c *Client) ValidateSettings(ctx context.Context, settings any, opts *ValidateSettingsOptions) (*spectypes.ValidateSettingsOutput, error) {
	input := &spectypes.ValidateSettingsInput{}
	var bodyReader io.Reader
	contentType := ""
	bb, err := json.Marshal(settings)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(bb)
	contentType = "application/json"
	var additional url.Values
	if opts != nil {
		additional = optionsToQuery(opts)
	}
	return httptransport.Invoke[spectypes.ValidateSettingsInput, spectypes.ValidateSettingsOutput](ctx, c.httpClient, c.baseURL, spectypes.ValidateSettingsRoute, &restAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, bodyReader, additional)
}

type restAuthenticator struct{ apiKey, accessToken, contentType string }

func (a *restAuthenticator) Apply(r *nethttp.Request) error {
	if a.contentType != "" {
		r.Header.Set("Content-Type", a.contentType)
	}
	switch {
	case a.accessToken != "":
		r.Header.Set("Authorization", "Bearer "+a.accessToken)
	case a.apiKey != "":
		r.Header.Set("Authorization", "Token "+a.apiKey)
	default:
		return errors.New("agentsettings: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return nil
}

func optionsToQuery(opts any) url.Values {
	q := url.Values{}
	if opts == nil {
		return q
	}
	v := reflect.ValueOf(opts)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := t.Field(i)
		fv := v.Field(i)
		if field.Name == "AdditionalQueryParams" {
			if aq, ok := fv.Interface().(url.Values); ok {
				for k, vs := range aq {
					q.Del(k)
					for _, vv := range vs {
						q.Add(k, vv)
					}
				}
			}
			continue
		}
		name := field.Tag.Get("schema")
		if name == "" || name == "-" {
			continue
		}
		if comma := stringsIndexByte(name, ','); comma >= 0 {
			name = name[:comma]
		}
		if isZeroQueryField(fv) {
			continue
		}
		addQueryField(q, name, fv)
	}
	return q
}
func stringsIndexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
func isZeroQueryField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map, reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}
func addQueryField(q url.Values, name string, v reflect.Value) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.Slice {
		for i := 0; i < v.Len(); i++ {
			addQueryField(q, name, v.Index(i))
		}
		return
	}
	switch v.Kind() {
	case reflect.String:
		q.Add(name, v.String())
	case reflect.Bool:
		q.Add(name, strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		q.Add(name, strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		q.Add(name, strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		q.Add(name, strconv.FormatFloat(v.Float(), 'g', -1, 64))
	}
}
