// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion from generated wire types to the idiomatic response
// structs. Deref helpers turn optional wire pointers into plain
// values so customers never nil-check a primitive.

package agentsettingsv1

import spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}
func derefBool(p *bool) bool {
	if p == nil {
		return false
	}
	return *p
}
func derefInt32(p *int32) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefInt64(p *int64) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefF32(p *float32) float64 {
	if p == nil {
		return 0
	}
	return float64(*p)
}
func derefF64(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p
}

func convertAgentThinkModel(in *spectypes.AgentThinkModel) *AgentThinkModel {
	if in == nil {
		return nil
	}
	out := &AgentThinkModel{}
	out.ID = derefStr(in.Id)
	out.Name = derefStr(in.Name)
	return out
}

func convertAgentThinkModelInfo(in *spectypes.AgentThinkModelInfo) *AgentThinkModelInfo {
	if in == nil {
		return nil
	}
	out := &AgentThinkModelInfo{}
	out.ID = derefStr(in.Id)
	out.Name = derefStr(in.Name)
	out.Provider = derefStr(in.Provider)
	return out
}

func convertAgentThinkProvider(in *spectypes.AgentThinkProvider) *AgentThinkProvider {
	if in == nil {
		return nil
	}
	out := &AgentThinkProvider{}
	out.ID = derefStr(in.Id)
	if in.Models != nil {
		out.Models = make([]AgentThinkModel, 0, len(in.Models))
		for i := range in.Models {
			if c := convertAgentThinkModel(&in.Models[i]); c != nil {
				out.Models = append(out.Models, *c)
			}
		}
	}
	out.Name = derefStr(in.Name)
	return out
}

func convertGetThinkProviderOutput(in *spectypes.GetThinkProviderOutput) *GetThinkProviderOutput {
	if in == nil {
		return nil
	}
	out := &GetThinkProviderOutput{}
	out.ID = derefStr(in.Id)
	out.Name = derefStr(in.Name)
	return out
}

func convertListProviderModelsOutput(in *spectypes.ListProviderModelsOutput) *ListProviderModelsOutput {
	if in == nil {
		return nil
	}
	out := &ListProviderModelsOutput{}
	if in.Models != nil {
		out.Models = make([]AgentThinkModel, 0, len(in.Models))
		for i := range in.Models {
			if c := convertAgentThinkModel(&in.Models[i]); c != nil {
				out.Models = append(out.Models, *c)
			}
		}
	}
	return out
}

func convertListThinkModelsOutput(in *spectypes.ListThinkModelsOutput) *ListThinkModelsOutput {
	if in == nil {
		return nil
	}
	out := &ListThinkModelsOutput{}
	if in.Models != nil {
		out.Models = make([]AgentThinkModelInfo, 0, len(in.Models))
		for i := range in.Models {
			if c := convertAgentThinkModelInfo(&in.Models[i]); c != nil {
				out.Models = append(out.Models, *c)
			}
		}
	}
	return out
}

func convertListThinkProvidersOutput(in *spectypes.ListThinkProvidersOutput) *ListThinkProvidersOutput {
	if in == nil {
		return nil
	}
	out := &ListThinkProvidersOutput{}
	if in.Providers != nil {
		out.Providers = make([]AgentThinkProvider, 0, len(in.Providers))
		for i := range in.Providers {
			if c := convertAgentThinkProvider(&in.Providers[i]); c != nil {
				out.Providers = append(out.Providers, *c)
			}
		}
	}
	return out
}

func convertValidateAgentOutput(in *spectypes.ValidateAgentOutput) *ValidateAgentOutput {
	if in == nil {
		return nil
	}
	out := &ValidateAgentOutput{}
	return out
}

func convertValidateSettingsOutput(in *spectypes.ValidateSettingsOutput) *ValidateSettingsOutput {
	if in == nil {
		return nil
	}
	out := &ValidateSettingsOutput{}
	return out
}
