// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Compile-checked usage examples, one per operation. No `// Output:`
// line, so `go test` builds them as smoke tests without running
// them (and without making network calls).

package agentsettingsv1

import "context"

func ExampleClient_GetThinkProvider() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetThinkProvider(context.Background(), "example-provider", nil)
}

func ExampleClient_ListProviderModels() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProviderModels(context.Background(), "example-provider", nil)
}

func ExampleClient_ListThinkModels() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListThinkModels(context.Background(), nil)
}

func ExampleClient_ListThinkProviders() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListThinkProviders(context.Background(), nil)
}

func ExampleClient_ValidateAgent() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ValidateAgent(context.Background(), nil, nil)
}

func ExampleClient_ValidateSettings() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ValidateSettings(context.Background(), nil, nil)
}
