// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing, value-typed response structs with idiomatic Go
// field names. Generated from the operations' output shapes; the
// conversion from the generated wire types lives in
// convert_output.go.

package agentsettingsv1

type AgentThinkModel struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

type AgentThinkModelInfo struct {
	ID       string `json:"id,omitempty"`
	Name     string `json:"name,omitempty"`
	Provider string `json:"provider,omitempty"`
}

type AgentThinkProvider struct {
	ID     string            `json:"id,omitempty"`
	Models []AgentThinkModel `json:"models,omitempty"`
	Name   string            `json:"name,omitempty"`
}

type GetThinkProviderOutput struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

type ListProviderModelsOutput struct {
	Models []AgentThinkModel `json:"models,omitempty"`
}

type ListThinkModelsOutput struct {
	Models []AgentThinkModelInfo `json:"models,omitempty"`
}

type ListThinkProvidersOutput struct {
	Providers []AgentThinkProvider `json:"providers,omitempty"`
}

type ValidateAgentOutput struct {
}

type ValidateSettingsOutput struct {
}
