// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generated wire tests, one per operation. An in-process httptest
// server captures the request; each verifies HTTP method, path
// prefix, and Token auth. Regenerated with the client; the
// hand-authored behavioral *_test.go beside it are preserved.

package agentsettingsv1

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestWireGen_GetThinkProvider(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetThinkProvider(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/agent/settings/think/providers/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProviderModels(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProviderModels(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/agent/settings/think/providers/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListThinkModels(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListThinkModels(context.Background(), nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/agent/settings/think/models") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListThinkProviders(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListThinkProviders(context.Background(), nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/agent/settings/think/providers") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ValidateAgent(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ValidateAgent(context.Background(), nil, nil)
	if gotMethod != "POST" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/agent/settings/agent/validate") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ValidateSettings(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ValidateSettings(context.Background(), nil, nil)
	if gotMethod != "POST" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/agent/settings/validate") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}
