// Code generated by spec-codegen-go. DO NOT EDIT.
//
// WebSocket transport package. Two concerns live here:
//
//  1. @websocketCloseCode constants for every error structure
//     annotated with the trait, mapped from spec to wire code.
//  2. Generic Stream[C, S any] + OpenStream[C, S any] primitives
//     backed by dvonthenen/websocket. The consumer-side facade
//     supplies marshal/unmarshal closures (from api/types) so the
//     wire framing for every union variant stays type-safe.
//
// Marshal/Unmarshal helpers themselves live in
// api/types/<service>_streaming.go alongside the union types they
// operate on; consumers should import them from there directly.

package websocket

import (
	"context"
	"fmt"
	"sync"

	nethttp "net/http"

	ws "github.com/dvonthenen/websocket"
)

// Close codes mapped from @websocketCloseCode trait on error shapes.
const (
	CloseCodeClientTimeout = 1011
	CloseCodeCodec = 1008
	CloseCodeDriverTimeout = 1011
)

// Stream is the bidirectional WebSocket session handle. C is the
// client-side stream union variant; S is the server-side stream
// union variant.
type Stream[C any, S any] interface {
	Send(msg C) error
	Recv() (S, error)
	Close() error
}

// OpenStream dials a WebSocket connection at url with the supplied
// upgrade headers, then returns a Stream that serializes Send calls
// via marshal (binary frames for @binaryFrame union members, JSON
// text frames for everything else) and deserializes Recv calls via
// unmarshal. Writes are serialized by an internal mutex; reads are
// expected to be driven by a single goroutine per Stream.
type wsStream[C any, S any] struct {
	conn      *ws.Conn
	marshal   func(C) ([]byte, bool, error)
	unmarshal func([]byte) (S, error)
	writeMu   sync.Mutex
}

// OpenStream dials a WebSocket against url using the supplied
// upgrade headers, returning a typed bidirectional Stream.
func OpenStream[C any, S any](
	ctx context.Context,
	url string,
	headers nethttp.Header,
	marshal func(C) ([]byte, bool, error),
	unmarshal func([]byte) (S, error),
) (Stream[C, S], error) {
	dialer := ws.DefaultDialer
	conn, _, err := dialer.DialContext(ctx, url, headers)
	if err != nil {
		return nil, fmt.Errorf("websocket.OpenStream: dial %s: %w", url, err)
	}
	return &wsStream[C, S]{
		conn:      conn,
		marshal:   marshal,
		unmarshal: unmarshal,
	}, nil
}

func (s *wsStream[C, S]) Send(msg C) error {
	data, isBinary, err := s.marshal(msg)
	if err != nil {
		return fmt.Errorf("websocket Send: marshal: %w", err)
	}
	msgType := ws.TextMessage
	if isBinary {
		msgType = ws.BinaryMessage
	}
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	return s.conn.WriteMessage(msgType, data)
}

func (s *wsStream[C, S]) Recv() (S, error) {
	var zero S
	_, data, err := s.conn.ReadMessage()
	if err != nil {
		return zero, err
	}
	return s.unmarshal(data)
}

func (s *wsStream[C, S]) Close() error {
	return s.conn.Close()
}
