// Code generated by spec-codegen-go. DO NOT EDIT.
//
// WebSocket transport-layer shim. Exports @websocketCloseCode
// constants and re-exports the marshal/unmarshal helpers that now
// live in api/types (see <service>_streaming.go there). The
// re-exports preserve the transport-layer surface that consumers
// call today (websocket.MarshalClientStream, etc.); they will be
// removed in Phase 6 of the endpoint-agnostic transport
// migration once consumers migrate to api/types directly.

package websocket

import types "github.com/deepgram/spec-mock-go-sdk/api/types"

// Close codes mapped from @websocketCloseCode trait on error shapes.
const (
	CloseCodeDriverTimeout = 1011
	CloseCodeCodec = 1008
	CloseCodeClientTimeout = 1011
)

// Re-exports. Removed in Phase 6; new code should call api/types directly.
var MarshalClientStream = types.MarshalClientStream
var UnmarshalClientStream = types.UnmarshalClientStream
var MarshalServerStream = types.MarshalServerStream
var UnmarshalServerStream = types.UnmarshalServerStream
