// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker bidirectional-stream transport - generic OpenStream
// primitive. Designed to wrap aws-sdk-go-v2's
// sagemakerruntime.InvokeEndpointWithBidirectionalStream once it
// ships on the Go SDK surface; as of the version pinned by this
// module the method is not yet exposed. The wrapper compiles and
// surfaces a clear error message so consuming code can already
// depend on the symbol.
//
// C and S are the client/server stream union types defined in
// api/types (e.g. types.ClientStream + types.ServerStream for
// Listen). The marshal/unmarshal closures handle wire encoding;
// SageMaker bidi framing is event-stream-based but carries the
// same logical messages defined by @messageType / @binaryFrame.


package sagemaker

import (
	"context"
	"fmt"
)

// Stream is the bidirectional session handle. C is the client-side
// stream union variant; S is the server-side stream union variant.
type Stream[C any, S any] interface {
	Send(msg C) error
	Recv() (S, error)
	Close() error
}

// OpenStream opens a bidirectional SageMaker stream against the named
// endpoint. Currently a stub pending aws-sdk-go-v2 support for
// InvokeEndpointWithBidirectionalStream.
func OpenStream[C any, S any](
	ctx context.Context,
	endpointName string,
	marshal func(C) ([]byte, bool, error),
	unmarshal func([]byte) (S, error),
) (Stream[C, S], error) {
	_ = ctx
	_ = endpointName
	_ = marshal
	_ = unmarshal
	return nil, fmt.Errorf(
		"sagemaker.OpenStream: pending aws-sdk-go-v2 support for " +
			"InvokeEndpointWithBidirectionalStream")
}
