// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker transport tuning, ported from the burst-tested Java
// transport (deepgram/deepgram-sagemaker-java). The defaults are
// the ones empirically validated against a 400-concurrent-stream
// burst on a 10x ml.g6.2xlarge endpoint: AWS's stock connect/
// acquire timeouts fail-fast under burst with client-side errors
// that look server-side; these lenient values let the connect
// layer absorb the wave.

package sagemaker

import "time"

// Config tunes the SageMaker transport. The zero value is not
// useful; start from DefaultConfig and adjust.
type Config struct {
	// ConnectionTimeout bounds the TCP/TLS connect (AWS default 2s).
	ConnectionTimeout time.Duration
	// ConnectionAcquireTimeout bounds waiting for a pooled connection
	// (AWS default 10s).
	ConnectionAcquireTimeout time.Duration
	// SubscriptionTimeout bounds waiting for the bidi stream to open.
	SubscriptionTimeout time.Duration
	// MaxConcurrency caps concurrent connections to the endpoint.
	MaxConcurrency int
	// MaxStreamsPerConnection caps HTTP/2 streams multiplexed onto one
	// connection. 1 = one stream per connection (prevents bidi stream
	// starvation). NOTE: enforcing this in Go needs a custom HTTP/2
	// conn pool — see SAGEMAKER-002.
	MaxStreamsPerConnection int
	// MaxRetries bounds retries on transient AWS errors per stream.
	MaxRetries int
	// InitialBackoff / MaxBackoff / BackoffMultiplier shape the
	// exponential backoff between retry attempts.
	InitialBackoff    time.Duration
	MaxBackoff        time.Duration
	BackoffMultiplier float64
	// RetryBudget is the total wall-clock budget across all retries
	// before a transient error is surfaced.
	RetryBudget time.Duration
	// MaxReplayBufferBytes caps the unacked-event replay buffer (FIFO
	// eviction) so a throttle storm can't exhaust memory. 0 disables.
	MaxReplayBufferBytes int64
}

// DefaultConfig returns the burst-validated defaults.
func DefaultConfig() Config {
	return Config{
		ConnectionTimeout:        30 * time.Second,
		ConnectionAcquireTimeout: 60 * time.Second,
		SubscriptionTimeout:      60 * time.Second,
		MaxConcurrency:           500,
		MaxStreamsPerConnection:  1,
		MaxRetries:               5,
		InitialBackoff:           100 * time.Millisecond,
		MaxBackoff:               5 * time.Second,
		BackoffMultiplier:        2.0,
		RetryBudget:              30 * time.Second,
		MaxReplayBufferBytes:     8 * 1024 * 1024,
	}
}
