// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker bidirectional-stream transport for the ListenLive
// service. Designed to wrap aws-sdk-go-v2's
// sagemakerruntime.InvokeEndpointWithBidirectionalStream once it
// exists on the Go SDK surface; as of the version pinned by this
// module the method is not yet exposed. The wrapper compiles and
// surfaces a clear error message so consuming code can already
// depend on the symbol; when the SDK ships support, this file's
// body is filled in by codegen with the same union-marshalling
// approach used by the WebSocket transport (the wire framing for
// BiDi SageMaker streams is event-stream-based but carries the
// same logical messages defined by @messageType / @binaryFrame).

package sagemaker

import (
	"context"
	"fmt"

	types "github.com/deepgram/spec-mock-go-sdk/api/types"
)

// OpenListenLiveStream opens a bidirectional SageMaker stream
// against the named endpoint. The returned stream Send-s ClientStream
// variants and Recv-s ServerStream variants using the same logical
// message contract as the WebSocket transport.
func OpenListenLiveStream(
	ctx context.Context,
	endpointName string,
) (*ListenLiveStream, error) {
	_ = ctx
	_ = endpointName
	return nil, fmt.Errorf(
		"sagemaker ListenLive bidirectional stream: " +
			"pending aws-sdk-go-v2 support for InvokeEndpointWithBidirectionalStream")
}

// ListenLiveStream is the bidirectional session handle. Method
// bodies remain stubs until aws-sdk-go-v2 ships
// InvokeEndpointWithBidirectionalStream; the surface matches what
// callers will need (Send for outbound, Recv for inbound, Close
// for shutdown).
type ListenLiveStream struct{}

func (s *ListenLiveStream) Send(msg types.ClientStream) error {
	_ = msg
	return fmt.Errorf("Send: pending aws-sdk-go-v2 BiDi support")
}

func (s *ListenLiveStream) Recv() (types.ServerStream, error) {
	return nil, fmt.Errorf("Recv: pending aws-sdk-go-v2 BiDi support")
}

func (s *ListenLiveStream) Close() error {
	return nil
}
