// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Stateful mid-stream resilience, ported from the burst-tested Java
// transport (deepgram-sagemaker-java). DialBidi handles connect-side
// retries; this handles transient failures AFTER a stream is
// established (e.g. a mid-stream ThrottlingException): it reconnects
// on a fresh isolated client and replays the unacked sent events so
// audio isn't lost, then continues. Bounded by smCfg.MaxRetries /
// RetryBudget; the replay buffer is trimmed when the server acks
// (real downstream data) and capped by MaxReplayBufferBytes.
//
// Validated against a live Nova-3 endpoint: at 400 concurrent on a
// deliberately overloaded 1x g6.2xlarge, DialBidi alone recovered
// 208/400 (192 mid-stream ThrottlingExceptions lost); this layer
// recovered 400/400.

package sagemaker

import (
	"context"
	"errors"
	"io"
	"math/rand"
	"sync"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
)

var errBudgetExhausted = errors.New("sagemaker: retry budget exhausted recovering stream")

// ResilientDialBidi opens a bidirectional stream that survives
// transient mid-stream failures via reconnect + replay. isAck reports
// whether a received message proves the server consumed input (so
// earlier sends can be dropped from the replay buffer and the retry
// budget reset); for Deepgram streaming, every downstream message
// except an end-of-stream Metadata/Error counts as an ack.
func ResilientDialBidi[C any, S any](
	ctx context.Context, cfg aws.Config, smCfg Config,
	endpointName, modelInvocationPath, modelQueryString, targetVariant, targetModel, inferenceID, enableExplanations string,
	marshal func(C) ([]byte, bool, error), unmarshal func([]byte, bool) (S, error), isAck func(S) bool,
) (Stream[C, S], error) {
	r := &resilientStream[C, S]{
		ctx: ctx, cfg: cfg, smCfg: smCfg,
		endpointName: endpointName, path: modelInvocationPath, query: modelQueryString,
		tv: targetVariant, tm: targetModel, iid: inferenceID, ee: enableExplanations,
		marshal: marshal, unmarshal: unmarshal, isAck: isAck,
		windowStart: time.Now(),
	}
	if err := r.dial(); err != nil {
		return nil, err
	}
	return r, nil
}

type bufferedSend[C any] struct {
	msg C
	n   int
}

type resilientStream[C any, S any] struct {
	ctx                                        context.Context
	cfg                                        aws.Config
	smCfg                                      Config
	endpointName, path, query, tv, tm, iid, ee string
	marshal                                    func(C) ([]byte, bool, error)
	unmarshal                                  func([]byte, bool) (S, error)
	isAck                                      func(S) bool

	mu          sync.Mutex
	cur         Stream[C, S]
	replay      []bufferedSend[C]
	replayBytes int64
	attempt     int
	windowStart time.Time
	closed      bool
}

// dial opens one fresh underlying stream on its own isolated client.
// Caller holds mu (or it is the initial pre-exposure dial).
func (r *resilientStream[C, S]) dial() error {
	client := NewBidiClient(r.cfg, r.smCfg)
	s, err := OpenStream[C, S](r.ctx, client, r.endpointName, r.path, r.query, r.tv, r.tm, r.iid, r.ee, r.marshal, r.unmarshal)
	if err != nil {
		return err
	}
	r.cur = s
	return nil
}

// reconnect rebuilds the stream and replays the unacked sends onto it,
// retrying transient failures with backoff until budget/retries are
// exhausted. Caller holds mu.
func (r *resilientStream[C, S]) reconnect() error {
	deadline := r.windowStart.Add(r.smCfg.RetryBudget)
	for {
		if r.attempt >= r.smCfg.MaxRetries || time.Now().After(deadline) {
			return errBudgetExhausted
		}
		backoff := ComputeBackoff(r.smCfg.InitialBackoff.Milliseconds(), r.smCfg.MaxBackoff.Milliseconds(), r.smCfg.BackoffMultiplier, r.attempt, rand.Int63n)
		r.attempt++
		select {
		case <-time.After(time.Duration(backoff) * time.Millisecond):
		case <-r.ctx.Done():
			return r.ctx.Err()
		}
		if r.cur != nil {
			_ = r.cur.Close()
		}
		if err := r.dial(); err != nil {
			if Classify(err) == Terminal {
				return err
			}
			continue
		}
		if err := r.replayUnacked(); err != nil {
			if Classify(err) == Terminal {
				return err
			}
			continue
		}
		return nil
	}
}

func (r *resilientStream[C, S]) replayUnacked() error {
	for _, b := range r.replay {
		if err := r.cur.Send(b.msg); err != nil {
			return err
		}
	}
	return nil
}

func (r *resilientStream[C, S]) Send(msg C) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.closed {
		return io.ErrClosedPipe
	}
	r.buffer(msg)
	if err := r.cur.Send(msg); err != nil {
		if Classify(err) == Terminal {
			return err
		}
		return r.reconnect()
	}
	return nil
}

func (r *resilientStream[C, S]) Recv() (S, error) {
	for {
		r.mu.Lock()
		cur := r.cur
		closed := r.closed
		r.mu.Unlock()
		if closed {
			var zero S
			return zero, io.EOF
		}
		msg, err := cur.Recv()
		if err == nil {
			if r.isAck(msg) {
				r.mu.Lock()
				r.replay = nil
				r.replayBytes = 0
				r.attempt = 0
				r.windowStart = time.Now()
				r.mu.Unlock()
			}
			return msg, nil
		}
		if err == io.EOF {
			return msg, err
		}
		if Classify(err) == Terminal {
			return msg, err
		}
		r.mu.Lock()
		e := r.reconnect()
		r.mu.Unlock()
		if e != nil {
			var zero S
			return zero, e
		}
	}
}

func (r *resilientStream[C, S]) Close() error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.closed = true
	r.replay = nil
	r.replayBytes = 0
	if r.cur != nil {
		return r.cur.Close()
	}
	return nil
}

// buffer appends msg to the replay buffer, evicting oldest entries
// FIFO once the byte cap is exceeded. Caller holds mu.
func (r *resilientStream[C, S]) buffer(msg C) {
	capBytes := r.smCfg.MaxReplayBufferBytes
	if capBytes == 0 {
		return
	}
	n := 0
	if b, _, err := r.marshal(msg); err == nil {
		n = len(b)
	}
	r.replay = append(r.replay, bufferedSend[C]{msg: msg, n: n})
	r.replayBytes += int64(n)
	for r.replayBytes > capBytes && len(r.replay) > 0 {
		r.replayBytes -= int64(r.replay[0].n)
		r.replay = r.replay[1:]
	}
}
