// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker batch transport - generic Invoke primitive. Wraps
// aws-sdk-go-v2's sagemakerruntime.InvokeEndpoint to send a typed
// *I as a JSON body and decode the JSON response into *O. The
// endpoint is expected to deploy a Deepgram-compatible model whose
// request/response wire format matches the corresponding REST
// schema; the model SHOULD respect query-parameter-bound input
// fields by reading them from the JSON body (since SageMaker
// InvokeEndpoint has no URL query string).
//
// One file per transport, not per operation: the primitive is
// operation-agnostic. Per-operation metadata lives alongside the
// shape types in api/types/<service>_route.go.

package sagemaker

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
)

// Invoke sends a JSON-marshalled *I to the named SageMaker endpoint
// and decodes the JSON response into a newly allocated *O.
func Invoke[I any, O any](
	ctx context.Context,
	client *sagemakerruntime.Client,
	endpointName string,
	input *I,
) (*O, error) {
	body, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("sagemaker.Invoke: marshal input: %w", err)
	}
	contentType := "application/json"
	resp, err := client.InvokeEndpoint(ctx, &sagemakerruntime.InvokeEndpointInput{
		EndpointName: &endpointName,
		ContentType:  &contentType,
		Body:         body,
	})
	if err != nil {
		return nil, err
	}
	var out O
	if err := json.Unmarshal(resp.Body, &out); err != nil {
		return nil, fmt.Errorf("sagemaker.Invoke: unmarshal response: %w", err)
	}
	return &out, nil
}
