// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker batch transport - generic Invoke primitive. Wraps
// aws-sdk-go-v2's sagemakerruntime.InvokeEndpoint to send an
// already-encoded request body and return the raw response body. The
// endpoint is expected to deploy a Deepgram-compatible model whose
// request/response wire format matches the corresponding REST
// schema. Transport-specific routing context can ride through
// CustomAttributes because SageMaker InvokeEndpoint has no URL query
// string.
//
// One file per transport, not per operation: the primitive is
// operation-agnostic. Per-operation metadata lives alongside the
// shape types in api/types/<service>_route.go.

package sagemaker

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
)

// Invoke sends an already-encoded body to the named SageMaker endpoint
// and returns the raw response bytes.
func Invoke(
	ctx context.Context,
	client *sagemakerruntime.Client,
	endpointName string,
	contentType string,
	body []byte,
	customAttributes string,
) ([]byte, error) {
	if client == nil {
		return nil, fmt.Errorf("sagemaker.Invoke: nil client")
	}
	if contentType == "" {
		contentType = "application/json"
	}
	req := &sagemakerruntime.InvokeEndpointInput{
		EndpointName: &endpointName,
		ContentType:  &contentType,
		Body:         body,
	}
	if customAttributes != "" {
		req.CustomAttributes = &customAttributes
	}
	resp, err := client.InvokeEndpoint(ctx, req)
	if err != nil {
		return nil, err
	}
	return resp.Body, nil
}
