// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Error classification and backoff for the SageMaker transport,
// ported from deepgram/deepgram-sagemaker-java. Default is
// Retryable: under burst there's a long tail of transient failure
// modes (HTTP/2 resets, pool-acquire timeouts, frontline
// throttling) and the retry budget — not the classifier — is the
// safety net. Only authoritative caller-side 4xx rejections are
// Terminal.

package sagemaker

import (
	"errors"
	"math"
	"strings"

	"github.com/aws/smithy-go"
)

// Classification decides whether a stream error is retried
// internally (Retryable) or surfaced to the caller (Terminal).
type Classification int

const (
	Retryable Classification = iota
	Terminal
)

// Classify mirrors the Java transport: throttling (by error code,
// any status) is always Retryable; a 4xx other than 429 (rate
// limit) and 424 (SageMaker upstream "failed to establish", which
// is transient under burst) is Terminal; everything else —
// including unrecognized errors and 5xx — defaults to Retryable.
func Classify(err error) Classification {
	if err == nil {
		return Retryable
	}
	var apiErr smithy.APIError
	if errors.As(err, &apiErr) && strings.Contains(strings.ToLower(apiErr.ErrorCode()), "throttl") {
		return Retryable
	}
	var httpErr interface{ HTTPStatusCode() int }
	if errors.As(err, &httpErr) {
		s := httpErr.HTTPStatusCode()
		if s >= 400 && s < 500 && s != 429 && s != 424 {
			return Terminal
		}
	}
	return Retryable
}

// ComputeBackoff returns the delay (ms) before the given retry
// attempt, using exponential growth capped at maxMs with full
// jitter — random uniform in [initialMs, ceiling]. Without jitter,
// N streams that fail together retry in lockstep and hammer the
// endpoint in waves. randIntn is injected (n -> [0, n)) so tests
// are deterministic; pass rand.Int63n in production.
func ComputeBackoff(initialMs, maxMs int64, multiplier float64, attempt int, randIntn func(n int64) int64) int64 {
	scaled := float64(initialMs) * math.Pow(multiplier, float64(attempt))
	var ceiling int64
	if scaled > float64(maxMs) || math.IsInf(scaled, 0) {
		ceiling = maxMs
	} else {
		ceiling = int64(scaled)
		if ceiling < initialMs {
			ceiling = initialMs
		}
	}
	if ceiling <= initialMs {
		return ceiling
	}
	return initialMs + randIntn(ceiling-initialMs+1)
}
