// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion from generated wire types to the idiomatic response
// structs. Deref helpers turn optional wire pointers into plain
// values so customers never nil-check a primitive.

package managev1

import spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}
func derefBool(p *bool) bool {
	if p == nil {
		return false
	}
	return *p
}
func derefInt32(p *int32) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefInt64(p *int64) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefF32(p *float32) float64 {
	if p == nil {
		return 0
	}
	return float64(*p)
}
func derefF64(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p
}

func convertCreateProjectInviteOutput(in *spectypes.CreateProjectInviteOutput) *CreateProjectInviteOutput {
	if in == nil {
		return nil
	}
	out := &CreateProjectInviteOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertCreateProjectKeyOutput(in *spectypes.CreateProjectKeyOutput) *CreateProjectKeyOutput {
	if in == nil {
		return nil
	}
	out := &CreateProjectKeyOutput{}
	out.APIKeyID = derefStr(in.Api_key_id)
	out.Comment = derefStr(in.Comment)
	out.ExpirationDate = derefStr(in.Expiration_date)
	out.Key = derefStr(in.Key)
	out.Scopes = in.Scopes
	out.Tags = in.Tags
	return out
}

func convertDeleteProjectInviteOutput(in *spectypes.DeleteProjectInviteOutput) *DeleteProjectInviteOutput {
	if in == nil {
		return nil
	}
	out := &DeleteProjectInviteOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertDeleteProjectKeyOutput(in *spectypes.DeleteProjectKeyOutput) *DeleteProjectKeyOutput {
	if in == nil {
		return nil
	}
	out := &DeleteProjectKeyOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertDeleteProjectOutput(in *spectypes.DeleteProjectOutput) *DeleteProjectOutput {
	if in == nil {
		return nil
	}
	out := &DeleteProjectOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertGetBillingBreakdownOutput(in *spectypes.GetBillingBreakdownOutput) *GetBillingBreakdownOutput {
	if in == nil {
		return nil
	}
	out := &GetBillingBreakdownOutput{}
	out.End = derefStr(in.End)
	out.Resolution = convertManageResolution(in.Resolution)
	if in.Results != nil {
		out.Results = make([]any, len(in.Results))
		for i := range in.Results {
			out.Results[i] = in.Results[i]
		}
	}
	out.Start = derefStr(in.Start)
	return out
}

func convertGetModelOutput(in *spectypes.GetModelOutput) *GetModelOutput {
	if in == nil {
		return nil
	}
	out := &GetModelOutput{}
	out.Architecture = derefStr(in.Architecture)
	out.Batch = derefBool(in.Batch)
	out.CanonicalName = derefStr(in.Canonical_name)
	out.FormattedOutput = derefBool(in.Formatted_output)
	out.Languages = in.Languages
	out.Metadata = convertManageTtsMetadata(in.Metadata)
	out.Name = derefStr(in.Name)
	out.Streaming = derefBool(in.Streaming)
	out.UUID = derefStr(in.Uuid)
	out.Version = derefStr(in.Version)
	return out
}

func convertGetProjectBalanceOutput(in *spectypes.GetProjectBalanceOutput) *GetProjectBalanceOutput {
	if in == nil {
		return nil
	}
	out := &GetProjectBalanceOutput{}
	out.Amount = derefF64(in.Amount)
	out.BalanceID = derefStr(in.Balance_id)
	out.PurchaseOrderID = derefStr(in.Purchase_order_id)
	out.Units = derefStr(in.Units)
	return out
}

func convertGetProjectKeyOutput(in *spectypes.GetProjectKeyOutput) *GetProjectKeyOutput {
	if in == nil {
		return nil
	}
	out := &GetProjectKeyOutput{}
	out.Item = convertManageProjectKey(in.Item)
	return out
}

func convertGetProjectModelOutput(in *spectypes.GetProjectModelOutput) *GetProjectModelOutput {
	if in == nil {
		return nil
	}
	out := &GetProjectModelOutput{}
	out.Architecture = derefStr(in.Architecture)
	out.Batch = derefBool(in.Batch)
	out.CanonicalName = derefStr(in.Canonical_name)
	out.FormattedOutput = derefBool(in.Formatted_output)
	out.Languages = in.Languages
	out.Metadata = convertManageTtsMetadata(in.Metadata)
	out.Name = derefStr(in.Name)
	out.Streaming = derefBool(in.Streaming)
	out.UUID = derefStr(in.Uuid)
	out.Version = derefStr(in.Version)
	return out
}

func convertGetProjectOutput(in *spectypes.GetProjectOutput) *GetProjectOutput {
	if in == nil {
		return nil
	}
	out := &GetProjectOutput{}
	out.MipOptOut = derefBool(in.Mip_opt_out)
	out.Name = derefStr(in.Name)
	out.ProjectID = derefStr(in.Project_id)
	return out
}

func convertGetProjectRequestOutput(in *spectypes.GetProjectRequestOutput) *GetProjectRequestOutput {
	if in == nil {
		return nil
	}
	out := &GetProjectRequestOutput{}
	out.Request = convertManageRequest(in.Request)
	return out
}

func convertGetProjectUsageOutput(in *spectypes.GetProjectUsageOutput) *GetProjectUsageOutput {
	if in == nil {
		return nil
	}
	out := &GetProjectUsageOutput{}
	out.End = derefStr(in.End)
	out.Resolution = convertManageResolution(in.Resolution)
	out.Start = derefStr(in.Start)
	return out
}

func convertGetUsageBreakdownOutput(in *spectypes.GetUsageBreakdownOutput) *GetUsageBreakdownOutput {
	if in == nil {
		return nil
	}
	out := &GetUsageBreakdownOutput{}
	out.End = derefStr(in.End)
	out.Resolution = convertManageResolution(in.Resolution)
	if in.Results != nil {
		out.Results = make([]any, len(in.Results))
		for i := range in.Results {
			out.Results[i] = in.Results[i]
		}
	}
	out.Start = derefStr(in.Start)
	return out
}

func convertLeaveProjectOutput(in *spectypes.LeaveProjectOutput) *LeaveProjectOutput {
	if in == nil {
		return nil
	}
	out := &LeaveProjectOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertListBillingFieldsOutput(in *spectypes.ListBillingFieldsOutput) *ListBillingFieldsOutput {
	if in == nil {
		return nil
	}
	out := &ListBillingFieldsOutput{}
	out.Accessors = in.Accessors
	out.Deployments = in.Deployments
	out.LineItems = in.Line_items
	out.Tags = in.Tags
	return out
}

func convertListMemberScopesOutput(in *spectypes.ListMemberScopesOutput) *ListMemberScopesOutput {
	if in == nil {
		return nil
	}
	out := &ListMemberScopesOutput{}
	out.Scopes = in.Scopes
	return out
}

func convertListModelsOutput(in *spectypes.ListModelsOutput) *ListModelsOutput {
	if in == nil {
		return nil
	}
	out := &ListModelsOutput{}
	if in.Stt != nil {
		out.Stt = make([]ManageSttModel, 0, len(in.Stt))
		for i := range in.Stt {
			if c := convertManageSttModel(&in.Stt[i]); c != nil {
				out.Stt = append(out.Stt, *c)
			}
		}
	}
	if in.Tts != nil {
		out.Tts = make([]ManageTtsModel, 0, len(in.Tts))
		for i := range in.Tts {
			if c := convertManageTtsModel(&in.Tts[i]); c != nil {
				out.Tts = append(out.Tts, *c)
			}
		}
	}
	return out
}

func convertListProjectBalancesOutput(in *spectypes.ListProjectBalancesOutput) *ListProjectBalancesOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectBalancesOutput{}
	if in.Balances != nil {
		out.Balances = make([]ManageBalance, 0, len(in.Balances))
		for i := range in.Balances {
			if c := convertManageBalance(&in.Balances[i]); c != nil {
				out.Balances = append(out.Balances, *c)
			}
		}
	}
	return out
}

func convertListProjectInvitesOutput(in *spectypes.ListProjectInvitesOutput) *ListProjectInvitesOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectInvitesOutput{}
	if in.Invites != nil {
		out.Invites = make([]ManageInvite, 0, len(in.Invites))
		for i := range in.Invites {
			if c := convertManageInvite(&in.Invites[i]); c != nil {
				out.Invites = append(out.Invites, *c)
			}
		}
	}
	return out
}

func convertListProjectKeysOutput(in *spectypes.ListProjectKeysOutput) *ListProjectKeysOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectKeysOutput{}
	if in.Api_keys != nil {
		out.APIKeys = make([]ManageProjectKey, 0, len(in.Api_keys))
		for i := range in.Api_keys {
			if c := convertManageProjectKey(&in.Api_keys[i]); c != nil {
				out.APIKeys = append(out.APIKeys, *c)
			}
		}
	}
	return out
}

func convertListProjectMembersOutput(in *spectypes.ListProjectMembersOutput) *ListProjectMembersOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectMembersOutput{}
	if in.Members != nil {
		out.Members = make([]ManageMember, 0, len(in.Members))
		for i := range in.Members {
			if c := convertManageMember(&in.Members[i]); c != nil {
				out.Members = append(out.Members, *c)
			}
		}
	}
	return out
}

func convertListProjectModelsOutput(in *spectypes.ListProjectModelsOutput) *ListProjectModelsOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectModelsOutput{}
	if in.Stt != nil {
		out.Stt = make([]ManageSttModel, 0, len(in.Stt))
		for i := range in.Stt {
			if c := convertManageSttModel(&in.Stt[i]); c != nil {
				out.Stt = append(out.Stt, *c)
			}
		}
	}
	if in.Tts != nil {
		out.Tts = make([]ManageTtsModel, 0, len(in.Tts))
		for i := range in.Tts {
			if c := convertManageTtsModel(&in.Tts[i]); c != nil {
				out.Tts = append(out.Tts, *c)
			}
		}
	}
	return out
}

func convertListProjectPurchasesOutput(in *spectypes.ListProjectPurchasesOutput) *ListProjectPurchasesOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectPurchasesOutput{}
	if in.Orders != nil {
		out.Orders = make([]ManageOrder, 0, len(in.Orders))
		for i := range in.Orders {
			if c := convertManageOrder(&in.Orders[i]); c != nil {
				out.Orders = append(out.Orders, *c)
			}
		}
	}
	return out
}

func convertListProjectRequestsOutput(in *spectypes.ListProjectRequestsOutput) *ListProjectRequestsOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectRequestsOutput{}
	out.Limit = derefInt32(in.Limit)
	out.Page = derefInt32(in.Page)
	if in.Requests != nil {
		out.Requests = make([]ManageRequest, 0, len(in.Requests))
		for i := range in.Requests {
			if c := convertManageRequest(&in.Requests[i]); c != nil {
				out.Requests = append(out.Requests, *c)
			}
		}
	}
	return out
}

func convertListProjectsOutput(in *spectypes.ListProjectsOutput) *ListProjectsOutput {
	if in == nil {
		return nil
	}
	out := &ListProjectsOutput{}
	if in.Projects != nil {
		out.Projects = make([]ManageProject, 0, len(in.Projects))
		for i := range in.Projects {
			if c := convertManageProject(&in.Projects[i]); c != nil {
				out.Projects = append(out.Projects, *c)
			}
		}
	}
	return out
}

func convertListUsageFieldsOutput(in *spectypes.ListUsageFieldsOutput) *ListUsageFieldsOutput {
	if in == nil {
		return nil
	}
	out := &ListUsageFieldsOutput{}
	out.Features = in.Features
	if in.Models != nil {
		out.Models = make([]any, len(in.Models))
		for i := range in.Models {
			out.Models[i] = in.Models[i]
		}
	}
	out.ProcessingMethods = in.Processing_methods
	out.Tags = in.Tags
	return out
}

func convertManageBalance(in *spectypes.ManageBalance) *ManageBalance {
	if in == nil {
		return nil
	}
	out := &ManageBalance{}
	out.Amount = derefF64(in.Amount)
	out.BalanceID = derefStr(in.Balance_id)
	out.PurchaseOrderID = derefStr(in.Purchase_order_id)
	out.Units = derefStr(in.Units)
	return out
}

func convertManageInvite(in *spectypes.ManageInvite) *ManageInvite {
	if in == nil {
		return nil
	}
	out := &ManageInvite{}
	out.Email = derefStr(in.Email)
	out.Scope = derefStr(in.Scope)
	return out
}

func convertManageKeyInfo(in *spectypes.ManageKeyInfo) *ManageKeyInfo {
	if in == nil {
		return nil
	}
	out := &ManageKeyInfo{}
	out.APIKeyID = derefStr(in.Api_key_id)
	out.Comment = derefStr(in.Comment)
	out.Created = derefStr(in.Created)
	out.Scopes = in.Scopes
	return out
}

func convertManageKeyMember(in *spectypes.ManageKeyMember) *ManageKeyMember {
	if in == nil {
		return nil
	}
	out := &ManageKeyMember{}
	out.Email = derefStr(in.Email)
	out.MemberID = derefStr(in.Member_id)
	return out
}

func convertManageMember(in *spectypes.ManageMember) *ManageMember {
	if in == nil {
		return nil
	}
	out := &ManageMember{}
	out.Email = derefStr(in.Email)
	out.FirstName = derefStr(in.First_name)
	out.LastName = derefStr(in.Last_name)
	out.MemberID = derefStr(in.Member_id)
	out.Scopes = in.Scopes
	return out
}

func convertManageOrder(in *spectypes.ManageOrder) *ManageOrder {
	if in == nil {
		return nil
	}
	out := &ManageOrder{}
	out.Amount = derefF64(in.Amount)
	out.Created = derefStr(in.Created)
	out.Expiration = derefStr(in.Expiration)
	out.OrderID = derefStr(in.Order_id)
	out.OrderType = derefStr(in.Order_type)
	out.Units = derefStr(in.Units)
	return out
}

func convertManageProject(in *spectypes.ManageProject) *ManageProject {
	if in == nil {
		return nil
	}
	out := &ManageProject{}
	out.MipOptOut = derefBool(in.Mip_opt_out)
	out.Name = derefStr(in.Name)
	out.ProjectID = derefStr(in.Project_id)
	return out
}

func convertManageProjectKey(in *spectypes.ManageProjectKey) *ManageProjectKey {
	if in == nil {
		return nil
	}
	out := &ManageProjectKey{}
	out.APIKey = convertManageKeyInfo(in.Api_key)
	out.Member = convertManageKeyMember(in.Member)
	return out
}

func convertManageRequest(in *spectypes.ManageRequest) *ManageRequest {
	if in == nil {
		return nil
	}
	out := &ManageRequest{}
	out.APIKeyID = derefStr(in.Api_key_id)
	out.Callback = derefStr(in.Callback)
	out.Code = derefInt32(in.Code)
	out.Created = derefStr(in.Created)
	out.Deployment = derefStr(in.Deployment)
	out.Path = derefStr(in.Path)
	out.ProjectUUID = derefStr(in.Project_uuid)
	out.RequestID = derefStr(in.Request_id)
	out.Response = in.Response
	return out
}

func convertManageResolution(in *spectypes.ManageResolution) *ManageResolution {
	if in == nil {
		return nil
	}
	out := &ManageResolution{}
	out.Amount = derefF64(in.Amount)
	out.Units = derefStr(in.Units)
	return out
}

func convertManageSttModel(in *spectypes.ManageSttModel) *ManageSttModel {
	if in == nil {
		return nil
	}
	out := &ManageSttModel{}
	out.Architecture = derefStr(in.Architecture)
	out.Batch = derefBool(in.Batch)
	out.CanonicalName = derefStr(in.Canonical_name)
	out.FormattedOutput = derefBool(in.Formatted_output)
	out.Languages = in.Languages
	out.Name = derefStr(in.Name)
	out.Streaming = derefBool(in.Streaming)
	out.UUID = derefStr(in.Uuid)
	out.Version = derefStr(in.Version)
	return out
}

func convertManageTtsMetadata(in *spectypes.ManageTtsMetadata) *ManageTtsMetadata {
	if in == nil {
		return nil
	}
	out := &ManageTtsMetadata{}
	out.Accent = derefStr(in.Accent)
	out.Age = derefStr(in.Age)
	out.Color = derefStr(in.Color)
	out.Image = derefStr(in.Image)
	out.Sample = derefStr(in.Sample)
	out.Tags = in.Tags
	out.UseCases = in.Use_cases
	return out
}

func convertManageTtsModel(in *spectypes.ManageTtsModel) *ManageTtsModel {
	if in == nil {
		return nil
	}
	out := &ManageTtsModel{}
	out.Architecture = derefStr(in.Architecture)
	out.CanonicalName = derefStr(in.Canonical_name)
	out.Languages = in.Languages
	out.Metadata = convertManageTtsMetadata(in.Metadata)
	out.Name = derefStr(in.Name)
	out.UUID = derefStr(in.Uuid)
	out.Version = derefStr(in.Version)
	return out
}

func convertRemoveProjectMemberOutput(in *spectypes.RemoveProjectMemberOutput) *RemoveProjectMemberOutput {
	if in == nil {
		return nil
	}
	out := &RemoveProjectMemberOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertUpdateMemberScopesOutput(in *spectypes.UpdateMemberScopesOutput) *UpdateMemberScopesOutput {
	if in == nil {
		return nil
	}
	out := &UpdateMemberScopesOutput{}
	out.Message = derefStr(in.Message)
	return out
}

func convertUpdateProjectOutput(in *spectypes.UpdateProjectOutput) *UpdateProjectOutput {
	if in == nil {
		return nil
	}
	out := &UpdateProjectOutput{}
	out.Message = derefStr(in.Message)
	return out
}
