// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Compile-checked usage examples, one per operation. No `// Output:`
// line, so `go test` builds them as smoke tests without running
// them (and without making network calls).

package managev1

import "context"

func ExampleClient_CreateProjectInvite() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.CreateProjectInvite(context.Background(), "example-project-id", nil, nil)
}

func ExampleClient_CreateProjectKey() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.CreateProjectKey(context.Background(), "example-project-id", nil, nil)
}

func ExampleClient_DeleteProject() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.DeleteProject(context.Background(), "example-project-id", nil)
}

func ExampleClient_DeleteProjectInvite() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.DeleteProjectInvite(context.Background(), "example-project-id", "example-email", nil)
}

func ExampleClient_DeleteProjectKey() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.DeleteProjectKey(context.Background(), "example-project-id", "example-key-id", nil)
}

func ExampleClient_GetBillingBreakdown() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetBillingBreakdown(context.Background(), "example-project-id", nil)
}

func ExampleClient_GetModel() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetModel(context.Background(), "example-model-id", nil)
}

func ExampleClient_GetProject() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetProject(context.Background(), "example-project-id", nil)
}

func ExampleClient_GetProjectBalance() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetProjectBalance(context.Background(), "example-project-id", "example-balance-id", nil)
}

func ExampleClient_GetProjectKey() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetProjectKey(context.Background(), "example-project-id", "example-key-id", nil)
}

func ExampleClient_GetProjectModel() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetProjectModel(context.Background(), "example-project-id", "example-model-id", nil)
}

func ExampleClient_GetProjectRequest() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetProjectRequest(context.Background(), "example-project-id", "example-request-id", nil)
}

func ExampleClient_GetProjectUsage() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetProjectUsage(context.Background(), "example-project-id", nil)
}

func ExampleClient_GetUsageBreakdown() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.GetUsageBreakdown(context.Background(), "example-project-id", nil)
}

func ExampleClient_LeaveProject() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.LeaveProject(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListBillingFields() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListBillingFields(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListMemberScopes() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListMemberScopes(context.Background(), "example-project-id", "example-member-id", nil)
}

func ExampleClient_ListModels() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListModels(context.Background(), nil)
}

func ExampleClient_ListProjectBalances() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectBalances(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjectInvites() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectInvites(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjectKeys() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectKeys(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjectMembers() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectMembers(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjectModels() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectModels(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjectPurchases() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectPurchases(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjectRequests() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjectRequests(context.Background(), "example-project-id", nil)
}

func ExampleClient_ListProjects() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListProjects(context.Background(), nil)
}

func ExampleClient_ListUsageFields() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.ListUsageFields(context.Background(), "example-project-id", nil)
}

func ExampleClient_RemoveProjectMember() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.RemoveProjectMember(context.Background(), "example-project-id", "example-member-id", nil)
}

func ExampleClient_UpdateMemberScopes() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.UpdateMemberScopes(context.Background(), "example-project-id", "example-member-id", nil, nil)
}

func ExampleClient_UpdateProject() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.UpdateProject(context.Background(), "example-project-id", nil, nil)
}
