// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generated wire tests, one per operation. An in-process httptest
// server captures the request; each verifies HTTP method, path
// prefix, and Token auth. Regenerated with the client; the
// hand-authored behavioral *_test.go beside it are preserved.

package managev1

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestWireGen_CreateProjectInvite(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.CreateProjectInvite(context.Background(), "test", nil, nil)
	if gotMethod != "POST" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_CreateProjectKey(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.CreateProjectKey(context.Background(), "test", nil, nil)
	if gotMethod != "POST" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_DeleteProject(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.DeleteProject(context.Background(), "test", nil)
	if gotMethod != "DELETE" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_DeleteProjectInvite(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.DeleteProjectInvite(context.Background(), "test", "test", nil)
	if gotMethod != "DELETE" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_DeleteProjectKey(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.DeleteProjectKey(context.Background(), "test", "test", nil)
	if gotMethod != "DELETE" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetBillingBreakdown(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetBillingBreakdown(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetModel(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetModel(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/models/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetProject(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetProject(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetProjectBalance(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetProjectBalance(context.Background(), "test", "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetProjectKey(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetProjectKey(context.Background(), "test", "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetProjectModel(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetProjectModel(context.Background(), "test", "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetProjectRequest(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetProjectRequest(context.Background(), "test", "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetProjectUsage(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetProjectUsage(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_GetUsageBreakdown(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.GetUsageBreakdown(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_LeaveProject(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.LeaveProject(context.Background(), "test", nil)
	if gotMethod != "DELETE" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListBillingFields(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListBillingFields(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListMemberScopes(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListMemberScopes(context.Background(), "test", "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListModels(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListModels(context.Background(), nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/models") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectBalances(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectBalances(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectInvites(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectInvites(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectKeys(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectKeys(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectMembers(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectMembers(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectModels(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectModels(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectPurchases(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectPurchases(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjectRequests(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjectRequests(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListProjects(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListProjects(context.Background(), nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_ListUsageFields(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.ListUsageFields(context.Background(), "test", nil)
	if gotMethod != "GET" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_RemoveProjectMember(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.RemoveProjectMember(context.Background(), "test", "test", nil)
	if gotMethod != "DELETE" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_UpdateMemberScopes(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.UpdateMemberScopes(context.Background(), "test", "test", nil, nil)
	if gotMethod != "PUT" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}

func TestWireGen_UpdateProject(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.UpdateProject(context.Background(), "test", nil, nil)
	if gotMethod != "PATCH" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/projects/") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}
