// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Defines the Interface type that generated shape types reference
// for Document-typed fields (e.g. Configure.Features is typed
// map[string]document.Interface). ProtocolDocumentGenerator in
// smithy-go writes a richer document package - lazy-document
// constructors and marshaller helpers - but those ride the
// protocol layer we don't run for shape-only codegen. The
// Marshaler/Unmarshaler composition is enough for the types
// package to compile; real Document values are constructed and
// consumed by the idiomatic transport layer's JSON marshalling.

package document

import smithydocument "github.com/aws/smithy-go/document"

type Interface interface {
	smithydocument.Marshaler
	smithydocument.Unmarshaler
}
