// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion from generated wire types to the idiomatic response
// structs. Deref helpers turn optional wire pointers into plain
// values so customers never nil-check a primitive.

package speakv1

import spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}
func derefBool(p *bool) bool {
	if p == nil {
		return false
	}
	return *p
}
func derefInt32(p *int32) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefInt64(p *int64) int {
	if p == nil {
		return 0
	}
	return int(*p)
}
func derefF32(p *float32) float64 {
	if p == nil {
		return 0
	}
	return float64(*p)
}
func derefF64(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p
}

func convertSynthesizeOutput(in *spectypes.SynthesizeOutput) *SynthesizeOutput {
	if in == nil {
		return nil
	}
	out := &SynthesizeOutput{}
	out.AdditionalModelUuids = derefStr(in.AdditionalModelUuids)
	out.Audio = in.Audio
	out.BreaksApplied = derefInt32(in.BreaksApplied)
	out.CharCount = derefInt32(in.CharCount)
	out.ContentType = derefStr(in.ContentType)
	out.ModelName = derefStr(in.ModelName)
	out.ModelUuid = derefStr(in.ModelUuid)
	out.PronunciationsApplied = derefInt32(in.PronunciationsApplied)
	out.Warnings = derefStr(in.Warnings)
	return out
}
