// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion from customer options to the generated wire input
// shape. Generated from the operation's query members.

package speakv1

import spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"

func optionsToSynthesizeInput(o *SpeakOptions) *spectypes.SynthesizeInput {
	in := &spectypes.SynthesizeInput{}
	if o == nil {
		return in
	}
	if o.BitRate != 0 {
		v := int32(o.BitRate)
		in.BitRate = &v
	}
	if o.Callback != "" {
		v := o.Callback
		in.Callback = &v
	}
	if o.CallbackMethod != "" {
		in.CallbackMethod = spectypes.CallbackMethod(o.CallbackMethod)
	}
	if o.Container != "" {
		in.Container = spectypes.SpeakContainer(o.Container)
	}
	if o.Encoding != "" {
		in.Encoding = spectypes.SpeakEncoding(o.Encoding)
	}
	if o.MipOptOut {
		v := o.MipOptOut
		in.MipOptOut = &v
	}
	if o.Model != "" {
		v := o.Model
		in.Model = &v
	}
	if o.SampleRate != 0 {
		v := int32(o.SampleRate)
		in.SampleRate = &v
	}
	if o.Speed != 0 {
		v := float32(o.Speed)
		in.Speed = &v
	}
	if len(o.Tag) > 0 {
		in.Tag = o.Tag
	}
	return in
}
