// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing option struct, generated from the operation's
// query parameters. AdditionalQueryParams is a transport-mapped
// escape hatch with no wire counterpart.

package speakv1

import "net/url"

type SpeakOptions struct {
	BitRate               int        `json:"bit_rate,omitempty" schema:"bit_rate,omitempty"`
	Callback              string     `json:"callback,omitempty" schema:"callback,omitempty"`
	CallbackMethod        string     `json:"callback_method,omitempty" schema:"callback_method,omitempty"`
	Container             string     `json:"container,omitempty" schema:"container,omitempty"`
	Encoding              string     `json:"encoding,omitempty" schema:"encoding,omitempty"`
	MipOptOut             bool       `json:"mip_opt_out,omitempty" schema:"mip_opt_out,omitempty"`
	Model                 string     `json:"model,omitempty" schema:"model,omitempty"`
	SampleRate            int        `json:"sample_rate,omitempty" schema:"sample_rate,omitempty"`
	Speed                 float64    `json:"speed,omitempty" schema:"speed,omitempty"`
	Tag                   []string   `json:"tag,omitempty" schema:"tag,omitempty"`
	AdditionalQueryParams url.Values `json:"-" schema:"-"`
}
