// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing, value-typed response structs with idiomatic Go
// field names. Generated from the operations' output shapes; the
// conversion from the generated wire types lives in
// convert_output.go.

package speakv1

type SynthesizeOutput struct {
	AdditionalModelUuids  string `json:"additionalModelUuids,omitempty"`
	Audio                 []byte `json:"audio,omitempty"`
	BreaksApplied         int    `json:"breaksApplied,omitempty"`
	CharCount             int    `json:"charCount,omitempty"`
	ContentType           string `json:"contentType,omitempty"`
	ModelName             string `json:"modelName,omitempty"`
	ModelUuid             string `json:"modelUuid,omitempty"`
	PronunciationsApplied int    `json:"pronunciationsApplied,omitempty"`
	Warnings              string `json:"warnings,omitempty"`
}
