// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker batch transport binding for this REST product.
// Wraps the AWS InvokeEndpoint primitive; the customer switches
// cloud->SageMaker at construction via WithSageMakerTransport.
// Note: typed query options are not forwarded as SageMaker
// CustomAttributes in this first cut — model selection rides on
// the endpoint + target model. See SAGEMAKER-001.

package speakv1

import (
	"context"
	"fmt"
	"io"

	"github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
	sm "github.com/deepgram/spec-mock-go-sdk/api/transport/sagemaker"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

type sageMakerBinding struct {
	client       *sagemakerruntime.Client
	endpointName string
}

// WithSageMakerTransport routes batch calls to a self-hosted
// SageMaker endpoint instead of the cloud REST API.
func WithSageMakerTransport(client *sagemakerruntime.Client, endpointName string) Option {
	return func(c *Client) { c.transport = sageMakerBinding{client: client, endpointName: endpointName} }
}

func (t sageMakerBinding) invoke(ctx context.Context, c *Client, opts *SpeakOptions, contentType string, body io.Reader) (*SpeakResponse, error) {
	_ = c
	if t.client == nil {
		return nil, fmt.Errorf("speak sagemaker: nil client")
	}
	var payload []byte
	if body != nil {
		data, err := io.ReadAll(body)
		if err != nil {
			return nil, err
		}
		payload = data
	}
	respBytes, err := sm.Invoke(ctx, t.client, t.endpointName, contentType, payload, "v1/speak")
	if err != nil {
		return nil, err
	}
	out := &spectypes.SynthesizeOutput{Audio: respBytes}
	return convertSynthesizeOutput(out), nil
}
