// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing prerecorded transcription package generated from
// the Listen operation. Implementation files in this directory are
// regenerated by spec-codegen-go; safety-net tests remain
// hand-authored beside them in spec-mock-go-sdk.

package prerecordedv1

import (
	"context"
	"errors"
	"io"
	nethttp "net/http"
	"os"
	"strings"

	httptransport "github.com/deepgram/spec-mock-go-sdk/api/transport/http"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

const DefaultBaseURL = "https://api.deepgram.com"

type Client struct {
	apiKey      string
	accessToken string
	baseURL     string
	httpClient  *nethttp.Client
	transport   prerecordedTransport
}

type Option func(*Client)

type prerecordedTransport interface {
	invoke(ctx context.Context, c *Client, opts *PreRecordedTranscriptionOptions, contentType string, body io.Reader) (*PreRecordedResponse, error)
}

func New(opts ...Option) *Client {
	c := &Client{
		apiKey:      os.Getenv("DEEPGRAM_API_KEY"),
		accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"),
		baseURL:     DefaultBaseURL,
		httpClient:  nethttp.DefaultClient,
	}
	WithHTTPTransport()(c)
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}

func WithAPIKey(apiKey string) Option {
	return func(c *Client) { c.apiKey = apiKey }
}

func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}

func WithBaseURL(baseURL string) Option {
	return func(c *Client) { c.baseURL = baseURL }
}

func WithHTTPClient(client *nethttp.Client) Option {
	return func(c *Client) { c.httpClient = client }
}

func (c *Client) WithBaseURL(baseURL string) *Client {
	out := *c
	out.baseURL = baseURL
	return &out
}

func (c *Client) WithHTTPClient(client *nethttp.Client) *Client {
	out := *c
	out.httpClient = client
	return &out
}

func (c *Client) FromURL(ctx context.Context, audioURL string, opts *PreRecordedTranscriptionOptions) (*PreRecordedResponse, error) {
	body := strings.NewReader(`{"url":` + jsonQuote(audioURL) + `}`)
	return c.invoke(ctx, opts, "application/json", body)
}

func (c *Client) FromFile(ctx context.Context, path, contentType string, opts *PreRecordedTranscriptionOptions) (*PreRecordedResponse, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return c.FromStream(ctx, f, contentType, opts)
}

func (c *Client) FromStream(ctx context.Context, r io.Reader, contentType string, opts *PreRecordedTranscriptionOptions) (*PreRecordedResponse, error) {
	if contentType == "" {
		contentType = "audio/*"
	}
	return c.invoke(ctx, opts, contentType, r)
}

func (c *Client) invoke(ctx context.Context, opts *PreRecordedTranscriptionOptions, contentType string, body io.Reader) (*PreRecordedResponse, error) {
	if c.transport == nil {
		WithHTTPTransport()(c)
	}
	return c.transport.invoke(ctx, c, opts, contentType, body)
}

type listenAuthenticator struct{ apiKey, accessToken, contentType string }

func (a *listenAuthenticator) Apply(r *nethttp.Request) error {
	if a.contentType != "" {
		r.Header.Set("Content-Type", a.contentType)
	}
	switch {
	case a.accessToken != "":
		r.Header.Set("Authorization", "Bearer "+a.accessToken)
	case a.apiKey != "":
		r.Header.Set("Authorization", "Token "+a.apiKey)
	default:
		return errors.New("listen prerecorded: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return nil
}

type httpBinding struct{}

func WithHTTPTransport() Option { return func(c *Client) { c.transport = httpBinding{} } }

func (httpBinding) invoke(ctx context.Context, c *Client, opts *PreRecordedTranscriptionOptions, contentType string, body io.Reader) (*PreRecordedResponse, error) {
	input := optionsToTranscribeInput(opts)
	var additional urlValues
	if opts != nil {
		additional = opts.AdditionalQueryParams
	}
	out, err := httptransport.Invoke[spectypes.TranscribeInput, spectypes.TranscribeOutput](ctx, c.httpClient, c.baseURL, spectypes.TranscribeRoute, &listenAuthenticator{apiKey: c.apiKey, accessToken: c.accessToken, contentType: contentType}, input, body, additional)
	if err != nil {
		return nil, err
	}
	return convertTranscribeOutput(out), nil
}

func jsonQuote(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
