// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion helpers between transport-agnostic customer options
// and generated api/types wire shapes.

package prerecordedv1

import (
	"net/url"
	"reflect"
	"strconv"

	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

func optionsToTranscribeInput(o *PreRecordedTranscriptionOptions) *spectypes.TranscribeInput {
	in := &spectypes.TranscribeInput{}
	if o == nil {
		return in
	}
	if o.Callback != "" {
		v := o.Callback
		in.Callback = &v
	}
	if o.CallbackMethod != "" {
		in.CallbackMethod = spectypes.CallbackMethod(o.CallbackMethod)
	}
	if o.DetectEntities {
		v := o.DetectEntities
		in.DetectEntities = &v
	}
	if len(o.DetectLanguage) > 0 {
		in.DetectLanguage = o.DetectLanguage
	}
	if o.Diarize {
		v := o.Diarize
		in.Diarize = &v
	}
	if o.DiarizeModel != "" {
		v := o.DiarizeModel
		in.DiarizeModel = &v
	}
	if o.DiarizeVersion != "" {
		v := o.DiarizeVersion
		in.DiarizeVersion = &v
	}
	if o.Dictation {
		v := o.Dictation
		in.Dictation = &v
	}
	if o.Encoding != "" {
		v := o.Encoding
		in.Encoding = &v
	}
	if o.FillerWords {
		v := o.FillerWords
		in.FillerWords = &v
	}
	if o.Intents {
		v := o.Intents
		in.Intents = &v
	}
	if len(o.Keyterm) > 0 {
		in.Keyterm = o.Keyterm
	}
	if len(o.Keywords) > 0 {
		in.Keywords = o.Keywords
	}
	if o.Language != "" {
		v := o.Language
		in.Language = &v
	}
	if o.LogData {
		v := o.LogData
		in.LogData = &v
	}
	if o.Measurements {
		v := o.Measurements
		in.Measurements = &v
	}
	if o.MipOptOut {
		v := o.MipOptOut
		in.MipOptOut = &v
	}
	if o.Model != "" {
		v := o.Model
		in.Model = &v
	}
	if o.Multichannel {
		v := o.Multichannel
		in.Multichannel = &v
	}
	if o.Numerals {
		v := o.Numerals
		in.Numerals = &v
	}
	if o.Paragraphs {
		v := o.Paragraphs
		in.Paragraphs = &v
	}
	if o.ProfanityFilter {
		v := o.ProfanityFilter
		in.ProfanityFilter = &v
	}
	if o.Punctuate {
		v := o.Punctuate
		in.Punctuate = &v
	}
	if len(o.Redact) > 0 {
		in.Redact = o.Redact
	}
	if len(o.Replace) > 0 {
		in.Replace = o.Replace
	}
	if len(o.Search) > 0 {
		in.Search = o.Search
	}
	if o.Sentiment {
		v := o.Sentiment
		in.Sentiment = &v
	}
	if o.SmartFormat {
		v := o.SmartFormat
		in.SmartFormat = &v
	}
	if o.Summarize != "" {
		v := o.Summarize
		in.Summarize = &v
	}
	if len(o.Tag) > 0 {
		in.Tag = o.Tag
	}
	if o.Topics {
		v := o.Topics
		in.Topics = &v
	}
	if o.UttSplit != 0 {
		v := float32(o.UttSplit)
		in.UttSplit = &v
	}
	if o.Utterances {
		v := o.Utterances
		in.Utterances = &v
	}
	if o.VadTurnoff != 0 {
		v := int32(o.VadTurnoff)
		in.VadTurnoff = &v
	}
	if o.Version != "" {
		v := o.Version
		in.Version = &v
	}
	return in
}

func prerecordedOptionsToQuery(o *PreRecordedTranscriptionOptions) url.Values {
	q := optionsStructToQuery(o)
	if o != nil {
		for k, vs := range o.AdditionalQueryParams {
			q.Del(k)
			for _, v := range vs {
				q.Add(k, v)
			}
		}
	}
	return q
}

func optionsStructToQuery(opts any) url.Values {
	q := url.Values{}
	if opts == nil {
		return q
	}
	v := reflect.ValueOf(opts)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := t.Field(i)
		name := field.Tag.Get("schema")
		if name == "" || name == "-" {
			continue
		}
		if comma := stringsIndexByte(name, ','); comma >= 0 {
			name = name[:comma]
		}
		fv := v.Field(i)
		if isZeroQueryField(fv) {
			continue
		}
		addQueryField(q, name, fv)
	}
	return q
}
func stringsIndexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
func isZeroQueryField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map, reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}
func addQueryField(q url.Values, name string, v reflect.Value) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.Slice {
		for i := 0; i < v.Len(); i++ {
			addQueryField(q, name, v.Index(i))
		}
		return
	}
	switch v.Kind() {
	case reflect.String:
		q.Add(name, v.String())
	case reflect.Bool:
		q.Add(name, strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		q.Add(name, strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		q.Add(name, strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		q.Add(name, strconv.FormatFloat(v.Float(), 'g', -1, 64))
	}
}

func convertTranscribeOutput(in *spectypes.TranscribeOutput) *PreRecordedResponse {
	if in == nil {
		return nil
	}
	out := &PreRecordedResponse{}
	if in.Metadata == nil && in.Results == nil && in.RequestId != nil {
		out.RequestID = *in.RequestId
	}
	out.Metadata = convertResponseMetadata(in.Metadata)
	out.Results = convertResponseResults(in.Results)
	return out
}

func convertResponseMetadata(in *spectypes.ResponseMetadata) *Metadata {
	if in == nil {
		return nil
	}
	return &Metadata{Channels: derefInt32(in.Channels), Created: derefStr(in.Created), Duration: derefF32(in.Duration), ModelInfo: convertModelInfoMap(in.ModelInfo), RequestID: derefStr(in.RequestId), Sha256: derefStr(in.Sha256), TransactionKey: derefStr(in.TransactionKey), Extra: in.Extra, IntentsInfo: convertTokenMetadata(in.IntentsInfo), Models: in.Models, ProcessingTime: derefF32(in.ProcessingTime), SentimentInfo: convertTokenMetadata(in.SentimentInfo), SummaryInfo: convertTokenMetadata(in.SummaryInfo), Tags: in.Tags, TopicsInfo: convertTokenMetadata(in.TopicsInfo), Warnings: convertWarnings(in.Warnings)}
}

func convertResponseResults(in *spectypes.ResponseResults) *Result {
	if in == nil {
		return nil
	}
	return &Result{Channels: convertChannels(in.Channels), Intents: convertIntents(in.Intents), Sentiments: convertAverageSentiment(in.Sentiments), Summary: convertSummaries(in.Summary), Topics: convertTopics(in.Topics), Utterances: convertUtterances(in.Utterances)}
}

func convertModelInfoMap(in map[string]spectypes.ModelInfo) map[string]ModelInfo {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]ModelInfo, len(in))
	for k, v := range in {
		out[k] = convertModelInfo(v)
	}
	return out
}
func convertModelInfo(in spectypes.ModelInfo) ModelInfo {
	return ModelInfo{Arch: derefStr(in.Arch), Name: derefStr(in.Name), Version: derefStr(in.Version)}
}
func convertTokenMetadata(in *spectypes.TokenMetadata) *TokenMetadata {
	if in == nil {
		return nil
	}
	return &TokenMetadata{InputTokens: derefInt64(in.InputTokens), ModelUuid: derefStr(in.ModelUuid), OutputTokens: derefInt64(in.OutputTokens), Model: derefStr(in.Model)}
}
func convertWarnings(in []spectypes.Warning) []Warning {
	if len(in) == 0 {
		return nil
	}
	out := make([]Warning, 0, len(in))
	for _, v := range in {
		out = append(out, Warning{Message: derefStr(v.Message), Parameter: derefStr(v.Parameter), Type: string(v.Type)})
	}
	return out
}
func convertChannels(in []spectypes.Channel) []Channel {
	if len(in) == 0 {
		return nil
	}
	out := make([]Channel, 0, len(in))
	for _, v := range in {
		out = append(out, convertChannel(v))
	}
	return out
}
func convertChannel(in spectypes.Channel) Channel {
	return Channel{Alternatives: convertAlternatives(in.Alternatives), DetectedLanguage: derefStr(in.DetectedLanguage), LanguageConfidence: derefF32(in.LanguageConfidence), Search: convertSearchResults(in.Search), Utterances: int32SliceToInt(in.Utterances)}
}
func convertAlternatives(in []spectypes.Alternative) []Alternative {
	if len(in) == 0 {
		return nil
	}
	out := make([]Alternative, 0, len(in))
	for _, v := range in {
		out = append(out, convertAlternative(v))
	}
	return out
}
func convertAlternative(in spectypes.Alternative) Alternative {
	return Alternative{Confidence: derefF32(in.Confidence), Transcript: derefStr(in.Transcript), Words: convertWords(in.Words), Entities: convertEntities(in.Entities), Languages: in.Languages, Paragraphs: convertParagraphs(in.Paragraphs), Phonemes: convertPhonemeWords(in.Phonemes), SentimentSegments: convertSentimentSegments(in.SentimentSegments), Summaries: convertSummaries(in.Summaries), Topics: convertTopicSegments(in.Topics), Translations: convertTranslations(in.Translations)}
}
func convertWords(in []spectypes.Word) []Word {
	if len(in) == 0 {
		return nil
	}
	out := make([]Word, 0, len(in))
	for _, v := range in {
		out = append(out, convertWord(v))
	}
	return out
}
func convertWord(in spectypes.Word) Word {
	return Word{Confidence: derefF32(in.Confidence), End: derefF32(in.End), Start: derefF32(in.Start), Word: derefStr(in.Word), Context: in.Context, FullVec: f32MapToF64(in.FullVec), Language: derefStr(in.Language), PunctuatedWord: derefStr(in.PunctuatedWord), RedactedText: derefStr(in.RedactedText), Sentiment: sentimentToPtrStr(in.Sentiment), SentimentScore: f32ToPtrF64(in.SentimentScore), Speaker: int64ToPtrInt(in.Speaker), SpeakerConfidence: f32ToPtrF64(in.SpeakerConfidence), SpeakerID: derefStr(in.SpeakerId)}
}
func convertEntities(in []spectypes.Entity) []Entity {
	if len(in) == 0 {
		return nil
	}
	out := make([]Entity, 0, len(in))
	for _, v := range in {
		out = append(out, Entity{Confidence: derefF32(v.Confidence), EndWord: derefInt32(v.EndWord), Label: derefStr(v.Label), StartWord: derefInt32(v.StartWord), Value: derefStr(v.Value), RawValue: derefStr(v.RawValue)})
	}
	return out
}
func convertParagraphs(in *spectypes.Paragraphs) *Paragraphs {
	if in == nil {
		return nil
	}
	return &Paragraphs{Paragraphs: convertParagraphList(in.Paragraphs), Transcript: derefStr(in.Transcript)}
}
func convertParagraphList(in []spectypes.Paragraph) []Paragraph {
	if len(in) == 0 {
		return nil
	}
	out := make([]Paragraph, 0, len(in))
	for _, v := range in {
		out = append(out, Paragraph{End: derefF32(v.End), NumWords: derefInt32(v.NumWords), Sentences: convertSentences(v.Sentences), Start: derefF32(v.Start), Channel: int64ToPtrInt(v.Channel), Sentiment: sentimentToPtrStr(v.Sentiment), SentimentScore: f32ToPtrF64(v.SentimentScore), Speaker: int64ToPtrInt(v.Speaker)})
	}
	return out
}
func convertSentences(in []spectypes.Sentence) []Sentence {
	if len(in) == 0 {
		return nil
	}
	out := make([]Sentence, 0, len(in))
	for _, v := range in {
		out = append(out, Sentence{End: derefF32(v.End), Start: derefF32(v.Start), Text: derefStr(v.Text), Sentiment: sentimentToPtrStr(v.Sentiment), SentimentScore: f32ToPtrF64(v.SentimentScore)})
	}
	return out
}
func convertPhonemeWords(in []spectypes.PhonemeWord) []PhonemeWord {
	if len(in) == 0 {
		return nil
	}
	out := make([]PhonemeWord, 0, len(in))
	for _, v := range in {
		out = append(out, PhonemeWord{Confidence: derefF32(v.Confidence), End: derefF32(v.End), Phoneme: derefStr(v.Phoneme), Start: derefF32(v.Start)})
	}
	return out
}
func convertSentimentSegments(in []spectypes.SitSentimentSegment) []SentimentSegment {
	if len(in) == 0 {
		return nil
	}
	out := make([]SentimentSegment, 0, len(in))
	for _, v := range in {
		out = append(out, SentimentSegment{EndWord: derefInt32(v.EndWord), Sentiment: string(v.Sentiment), SentimentScore: derefF32(v.SentimentScore), StartWord: derefInt32(v.StartWord), Text: derefStr(v.Text)})
	}
	return out
}
func convertSummaries(in []spectypes.Summary) []Summary {
	if len(in) == 0 {
		return nil
	}
	out := make([]Summary, 0, len(in))
	for _, v := range in {
		out = append(out, Summary{EndWord: derefInt32(v.EndWord), StartWord: derefInt32(v.StartWord), Summary: derefStr(v.Summary)})
	}
	return out
}
func convertTopics(in []spectypes.Topic) []Topic {
	if len(in) == 0 {
		return nil
	}
	out := make([]Topic, 0, len(in))
	for _, v := range in {
		out = append(out, convertTopic(v))
	}
	return out
}
func convertTopic(in spectypes.Topic) Topic {
	return Topic{ConfidenceScore: derefF32(in.ConfidenceScore), Topic: derefStr(in.Topic)}
}
func convertTopicSegments(in []spectypes.TopicSegment) []TopicSegment {
	if len(in) == 0 {
		return nil
	}
	out := make([]TopicSegment, 0, len(in))
	for _, v := range in {
		out = append(out, TopicSegment{EndWord: derefInt32(v.EndWord), StartWord: derefInt32(v.StartWord), Text: derefStr(v.Text), Topics: convertTopics(v.Topics)})
	}
	return out
}
func convertTranslations(in []spectypes.Translation) []Translation {
	if len(in) == 0 {
		return nil
	}
	out := make([]Translation, 0, len(in))
	for _, v := range in {
		out = append(out, Translation{Language: derefStr(v.Language), Translation: derefStr(v.Translation)})
	}
	return out
}
func convertSearchResults(in []spectypes.SearchResult) []SearchResult {
	if len(in) == 0 {
		return nil
	}
	out := make([]SearchResult, 0, len(in))
	for _, v := range in {
		out = append(out, SearchResult{Hits: convertHits(v.Hits), Query: derefStr(v.Query)})
	}
	return out
}
func convertHits(in []spectypes.Hit) []Hit {
	if len(in) == 0 {
		return nil
	}
	out := make([]Hit, 0, len(in))
	for _, v := range in {
		out = append(out, Hit{Confidence: derefF32(v.Confidence), End: derefF32(v.End), Start: derefF32(v.Start), Snippet: derefStr(v.Snippet)})
	}
	return out
}
func convertUtterances(in []spectypes.Utterance) []Utterance {
	if len(in) == 0 {
		return nil
	}
	out := make([]Utterance, 0, len(in))
	for _, v := range in {
		out = append(out, Utterance{Channel: derefInt32(v.Channel), Confidence: derefF32(v.Confidence), End: derefF32(v.End), ID: derefStr(v.Id), Start: derefF32(v.Start), Transcript: derefStr(v.Transcript), Words: convertWords(v.Words), Languages: v.Languages, Sentiment: sentimentToPtrStr(v.Sentiment), SentimentScore: f32ToPtrF64(v.SentimentScore), Speaker: int64ToPtrInt(v.Speaker)})
	}
	return out
}
func convertIntents(in []spectypes.Intent) []Intent {
	if len(in) == 0 {
		return nil
	}
	out := make([]Intent, 0, len(in))
	for _, v := range in {
		out = append(out, Intent{ConfidenceScore: derefF32(v.ConfidenceScore), Intent: derefStr(v.Intent)})
	}
	return out
}
func convertAverageSentiment(in *spectypes.AverageSentiment) *AverageSentiment {
	if in == nil {
		return nil
	}
	return &AverageSentiment{Average: convertSentimentAggregate(in.Average)}
}
func convertSentimentAggregate(in *spectypes.SentimentAggregate) *SentimentAggregate {
	if in == nil {
		return nil
	}
	return &SentimentAggregate{Sentiment: string(in.Sentiment), SentimentScore: derefF32(in.SentimentScore)}
}
func derefStr(v *string) string {
	if v == nil {
		return ""
	}
	return *v
}
func derefF32(v *float32) float64 {
	if v == nil {
		return 0
	}
	return float64(*v)
}
func derefBool(v *bool) bool {
	if v == nil {
		return false
	}
	return *v
}
func derefInt32(v *int32) int {
	if v == nil {
		return 0
	}
	return int(*v)
}
func derefInt64(v *int64) int {
	if v == nil {
		return 0
	}
	return int(*v)
}
func int64ToPtrInt(v *int64) *int {
	if v == nil {
		return nil
	}
	out := int(*v)
	return &out
}
func f32ToPtrF64(v *float32) *float64 {
	if v == nil {
		return nil
	}
	out := float64(*v)
	return &out
}
func sentimentToPtrStr(v spectypes.Sentiment) *string {
	if v == "" {
		return nil
	}
	out := string(v)
	return &out
}
func int32SliceToInt(in []int32) []int {
	if len(in) == 0 {
		return nil
	}
	out := make([]int, 0, len(in))
	for _, v := range in {
		out = append(out, int(v))
	}
	return out
}
func f32MapToF64(in map[string]float32) map[string]float64 {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]float64, len(in))
	for k, v := range in {
		out[k] = float64(v)
	}
	return out
}
