// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Conversion helpers between transport-agnostic customer options
// and generated api/types wire shapes.

package prerecordedv1

import (
	"net/url"
	"reflect"
	"strconv"

	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

func optionsToTranscribeInput(o *PreRecordedTranscriptionOptions) *spectypes.TranscribeInput {
	in := &spectypes.TranscribeInput{}
	if o == nil {
		return in
	}
	if o.Callback != "" {
		v := o.Callback
		in.Callback = &v
	}
	if o.CallbackMethod != "" {
		in.CallbackMethod = spectypes.CallbackMethod(o.CallbackMethod)
	}
	if o.DetectEntities {
		v := o.DetectEntities
		in.DetectEntities = &v
	}
	if len(o.DetectLanguage) > 0 {
		in.DetectLanguage = o.DetectLanguage
	}
	if o.Diarize {
		v := o.Diarize
		in.Diarize = &v
	}
	if o.DiarizeModel != "" {
		v := o.DiarizeModel
		in.DiarizeModel = &v
	}
	if o.DiarizeVersion != "" {
		v := o.DiarizeVersion
		in.DiarizeVersion = &v
	}
	if o.Dictation {
		v := o.Dictation
		in.Dictation = &v
	}
	if o.Encoding != "" {
		v := o.Encoding
		in.Encoding = &v
	}
	if o.FillerWords {
		v := o.FillerWords
		in.FillerWords = &v
	}
	if o.Intents {
		v := o.Intents
		in.Intents = &v
	}
	if len(o.Keyterm) > 0 {
		in.Keyterm = o.Keyterm
	}
	if len(o.Keywords) > 0 {
		in.Keywords = o.Keywords
	}
	if o.Language != "" {
		v := o.Language
		in.Language = &v
	}
	if o.LogData {
		v := o.LogData
		in.LogData = &v
	}
	if o.Measurements {
		v := o.Measurements
		in.Measurements = &v
	}
	if o.MipOptOut {
		v := o.MipOptOut
		in.MipOptOut = &v
	}
	if o.Model != "" {
		v := o.Model
		in.Model = &v
	}
	if o.Multichannel {
		v := o.Multichannel
		in.Multichannel = &v
	}
	if o.Numerals {
		v := o.Numerals
		in.Numerals = &v
	}
	if o.Paragraphs {
		v := o.Paragraphs
		in.Paragraphs = &v
	}
	if o.ProfanityFilter {
		v := o.ProfanityFilter
		in.ProfanityFilter = &v
	}
	if o.Punctuate {
		v := o.Punctuate
		in.Punctuate = &v
	}
	if len(o.Redact) > 0 {
		in.Redact = o.Redact
	}
	if len(o.Replace) > 0 {
		in.Replace = o.Replace
	}
	if len(o.Search) > 0 {
		in.Search = o.Search
	}
	if o.Sentiment {
		v := o.Sentiment
		in.Sentiment = &v
	}
	if o.SmartFormat {
		v := o.SmartFormat
		in.SmartFormat = &v
	}
	if o.Summarize != "" {
		v := o.Summarize
		in.Summarize = &v
	}
	if len(o.Tag) > 0 {
		in.Tag = o.Tag
	}
	if o.Topics {
		v := o.Topics
		in.Topics = &v
	}
	if o.UttSplit != 0 {
		v := float32(o.UttSplit)
		in.UttSplit = &v
	}
	if o.Utterances {
		v := o.Utterances
		in.Utterances = &v
	}
	if o.VadTurnoff != 0 {
		v := int32(o.VadTurnoff)
		in.VadTurnoff = &v
	}
	if o.Version != "" {
		v := o.Version
		in.Version = &v
	}
	return in
}

func prerecordedOptionsToQuery(o *PreRecordedTranscriptionOptions) url.Values {
	q := optionsStructToQuery(o)
	if o != nil {
		for k, vs := range o.AdditionalQueryParams {
			q.Del(k)
			for _, v := range vs {
				q.Add(k, v)
			}
		}
	}
	return q
}

func optionsStructToQuery(opts any) url.Values {
	q := url.Values{}
	if opts == nil {
		return q
	}
	v := reflect.ValueOf(opts)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := t.Field(i)
		name := field.Tag.Get("schema")
		if name == "" || name == "-" {
			continue
		}
		if comma := stringsIndexByte(name, ','); comma >= 0 {
			name = name[:comma]
		}
		fv := v.Field(i)
		if isZeroQueryField(fv) {
			continue
		}
		addQueryField(q, name, fv)
	}
	return q
}
func stringsIndexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
func isZeroQueryField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map, reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}
func addQueryField(q url.Values, name string, v reflect.Value) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.Slice {
		for i := 0; i < v.Len(); i++ {
			addQueryField(q, name, v.Index(i))
		}
		return
	}
	switch v.Kind() {
	case reflect.String:
		q.Add(name, v.String())
	case reflect.Bool:
		q.Add(name, strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		q.Add(name, strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		q.Add(name, strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		q.Add(name, strconv.FormatFloat(v.Float(), 'g', -1, 64))
	}
}

func convertTranscribeOutput(in *spectypes.TranscribeOutput) *PreRecordedResponse {
	if in == nil {
		return nil
	}
	out := &PreRecordedResponse{}
	if in.RequestId != nil {
		out.RequestID = *in.RequestId
	}
	if in.Metadata != nil {
		out.Metadata = &Metadata{}
		if in.Metadata.RequestId != nil {
			out.Metadata.RequestID = *in.Metadata.RequestId
		}
	}
	if in.Results != nil {
		out.Results = &Result{}
		for _, ch := range in.Results.Channels {
			outCh := Channel{}
			for _, alt := range ch.Alternatives {
				outAlt := Alternative{}
				if alt.Transcript != nil {
					outAlt.Transcript = *alt.Transcript
				}
				outCh.Alternatives = append(outCh.Alternatives, outAlt)
			}
			out.Results.Channels = append(out.Results.Channels, outCh)
		}
		for _, utt := range in.Results.Utterances {
			outUtt := Utterance{}
			if utt.Transcript != nil {
				outUtt.Transcript = *utt.Transcript
			}
			out.Results.Utterances = append(out.Results.Utterances, outUtt)
		}
	}
	return out
}
