// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Compile-checked usage example. No `// Output:` line, so `go test`
// builds it as a smoke test without executing it.

package prerecordedv1

import "context"

func ExampleClient_FromURL() {
	client := New(WithAPIKey("YOUR_API_KEY"))
	_, _ = client.FromURL(context.Background(), "https://example.com/audio.wav", nil)
}
