// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Stable customer-facing response aliases for prerecorded
// transcription. Detailed conversion is intentionally isolated
// from transport dispatch.

package prerecordedv1

// PreRecordedResponse carries the prerecorded transcription
// result. The populated fields depend on whether the request
// set the Callback option:
//
//   - Synchronous (no Callback): Metadata and Results are
//     populated; the transcript is at
//     Results.Channels[i].Alternatives[j].Transcript. The
//     top-level RequestID is empty -- read Metadata.RequestID
//     for the request identifier.
//
//   - Callback (Callback option set): only RequestID is
//     populated. Metadata and Results are nil because the
//     transcript is delivered asynchronously to the customer's
//     callback URL.
type PreRecordedResponse struct {
	RequestID string    `json:"request_id,omitempty"`
	Metadata  *Metadata `json:"metadata,omitempty"`
	Results   *Result   `json:"results,omitempty"`
}
type Metadata struct {
	RequestID string `json:"request_id,omitempty"`
}
type Result struct {
	Channels   []Channel   `json:"channels,omitempty"`
	Utterances []Utterance `json:"utterances,omitempty"`
}
type Channel struct {
	Alternatives []Alternative `json:"alternatives,omitempty"`
}
type Alternative struct {
	Transcript string `json:"transcript,omitempty"`
}
type Utterance struct {
	Transcript string `json:"transcript,omitempty"`
}
