// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker transport binding for prerecorded transcription.
// AdditionalQueryParams.Encode() is sent as CustomAttributes
// per ADR-0004's transport-specific escape-hatch mapping.

package prerecordedv1

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

type sageMakerBinding struct {
	client             *sagemakerruntime.Client
	endpointName       string
	targetVariant      string
	targetModel        string
	inferenceID        string
	enableExplanations string
}

type SageMakerOption func(*sageMakerBinding)

func WithSageMakerTransport(client *sagemakerruntime.Client, endpointName string, opts ...SageMakerOption) Option {
	return func(c *Client) {
		b := sageMakerBinding{client: client, endpointName: endpointName}
		for _, o := range opts {
			o(&b)
		}
		c.transport = b
	}
}

func WithTargetVariant(v string) SageMakerOption {
	return func(b *sageMakerBinding) { b.targetVariant = v }
}
func WithTargetModel(v string) SageMakerOption {
	return func(b *sageMakerBinding) { b.targetModel = v }
}
func WithInferenceID(v string) SageMakerOption {
	return func(b *sageMakerBinding) { b.inferenceID = v }
}
func WithEnableExplanations(v string) SageMakerOption {
	return func(b *sageMakerBinding) { b.enableExplanations = v }
}

func (t sageMakerBinding) invoke(ctx context.Context, c *Client, opts *PreRecordedTranscriptionOptions, contentType string, body io.Reader) (*PreRecordedResponse, error) {
	_ = c
	_ = contentType
	if t.client == nil {
		return nil, fmt.Errorf("listen prerecorded sagemaker: nil client")
	}
	input := optionsToTranscribeInput(opts)
	if body != nil {
		data, err := io.ReadAll(body)
		if err != nil {
			return nil, err
		}
		input.Body = &spectypes.TranscribeRequestBodyMemberAudio{Value: data}
	}
	payload, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("listen prerecorded sagemaker: marshal input: %w", err)
	}
	ct := "application/json"
	req := &sagemakerruntime.InvokeEndpointInput{EndpointName: &t.endpointName, ContentType: &ct, Body: payload}
	if t.targetVariant != "" {
		req.TargetVariant = &t.targetVariant
	}
	if t.targetModel != "" {
		req.TargetModel = &t.targetModel
	}
	if t.inferenceID != "" {
		req.InferenceId = &t.inferenceID
	}
	if t.enableExplanations != "" {
		req.EnableExplanations = &t.enableExplanations
	}
	if opts != nil && len(opts.AdditionalQueryParams) > 0 {
		attrs := opts.AdditionalQueryParams.Encode()
		req.CustomAttributes = &attrs
	}
	resp, err := t.client.InvokeEndpoint(ctx, req)
	if err != nil {
		return nil, err
	}
	var out spectypes.TranscribeOutput
	if err := json.Unmarshal(resp.Body, &out); err != nil {
		return nil, fmt.Errorf("listen prerecorded sagemaker: unmarshal response: %w", err)
	}
	return convertTranscribeOutput(&out), nil
}
