// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generated wire test (one per single-op facade): an in-process
// httptest server captures the request; verifies method, path
// prefix, and Token auth. Hand-authored *_test.go are preserved.

package prerecordedv1

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestWireGen_FromURL(t *testing.T) {
	var gotMethod, gotPath, gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath, gotAuth = r.Method, r.URL.Path, r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()
	c := New(WithAPIKey("k"), WithBaseURL(srv.URL))
	_, _ = c.FromURL(context.Background(), "https://example.invalid/x", nil)
	if gotMethod != "POST" {
		t.Fatalf("method = %q", gotMethod)
	}
	if !strings.HasPrefix(gotPath, "/v1/listen") {
		t.Fatalf("path = %q", gotPath)
	}
	if gotAuth != "Token k" {
		t.Fatalf("auth = %q", gotAuth)
	}
}
