// Code generated by spec-codegen-go. DO NOT EDIT.
//
// WebRTC transport stub for the ListenLive service. The spec
// lists webrtc in @supportsTransports for forward compatibility but
// does not yet model the WebRTC-specific framing (signaling
// handshake, ICE candidates, data channel envelope, congestion
// control hooks). Codegen emits this stub so consuming code can
// already depend on the package shape; the body becomes real once
// the spec models WebRTC. Tracked in ADR-0004's "future deployment
// modes" section.

package webrtc

import (
	"context"
	"fmt"

	types "github.com/deepgram/spec-mock-go-sdk/api/types"
)

// OpenListenLiveStream opens a WebRTC-based session for the
// ListenLive service. Currently a stub.
func OpenListenLiveStream(ctx context.Context) (*ListenLiveStream, error) {
	_ = ctx
	return nil, fmt.Errorf(
		"webrtc transport for ListenLive: not implemented " +
			"(spec does not yet model WebRTC framing; tracked in ADR-0004)")
}

// ListenLiveStream is the WebRTC session handle. Method bodies
// are stubs - the surface matches what callers will need (Send for
// outbound, Recv for inbound, Close for shutdown).
type ListenLiveStream struct{}

func (s *ListenLiveStream) Send(msg types.ClientStream) error {
	_ = msg
	return fmt.Errorf("Send: webrtc transport not implemented")
}

func (s *ListenLiveStream) Recv() (types.ServerStream, error) {
	return nil, fmt.Errorf("Recv: webrtc transport not implemented")
}

func (s *ListenLiveStream) Close() error {
	return nil
}
