// Code generated by spec-codegen-go. DO NOT EDIT.
//
// WebRTC transport stub - generic OpenStream primitive. The spec
// lists webrtc in @supportsTransports for forward compatibility
// but does not yet model the WebRTC-specific framing (signaling
// handshake, ICE candidates, data channel envelope, congestion
// control hooks). Codegen emits this stub so consuming code can
// already depend on the package shape; the body becomes real
// once the spec models WebRTC. Tracked in ADR-0004's "future
// deployment modes" section.

package webrtc

import (
	"context"
	"fmt"
)

// Stream is the WebRTC session handle. C is the client-side stream
// union variant; S is the server-side stream union variant.
type Stream[C any, S any] interface {
	Send(msg C) error
	Recv() (S, error)
	Close() error
}

// OpenStream opens a WebRTC-based session. Currently a stub pending
// spec-level WebRTC framing modelling.
func OpenStream[C any, S any](
	ctx context.Context,
	signalingURL string,
	marshal func(C) ([]byte, bool, error),
	unmarshal func([]byte) (S, error),
) (Stream[C, S], error) {
	_ = ctx
	_ = signalingURL
	_ = marshal
	_ = unmarshal
	return nil, fmt.Errorf(
		"webrtc.OpenStream: not implemented " +
			"(spec does not yet model WebRTC framing; tracked in ADR-0004)")
}
