// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing live (WebSocket) client, generated by
// spec-codegen-go's model-driven streaming facade emitter.
// Recv returns an idiomatic Event (see events.go).

package livev1

import (
	"context"
	"errors"
	nethttp "net/http"
	"net/url"
	"os"
	"reflect"
	"strconv"

	wstransport "github.com/deepgram/spec-mock-go-sdk/api/transport/websocket"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

const DefaultBaseURL = "wss://api.deepgram.com"
const streamPath = "/v1/speak"

type SpeakLiveOptions struct {
	AutoFlush             bool       `json:"auto_flush,omitempty" schema:"auto_flush,omitempty"`
	Callback              string     `json:"callback,omitempty" schema:"callback,omitempty"`
	CallbackMethod        string     `json:"callback_method,omitempty" schema:"callback_method,omitempty"`
	Encoding              string     `json:"encoding,omitempty" schema:"encoding,omitempty"`
	MipOptOut             bool       `json:"mip_opt_out,omitempty" schema:"mip_opt_out,omitempty"`
	Model                 string     `json:"model,omitempty" schema:"model,omitempty"`
	SampleRate            int        `json:"sample_rate,omitempty" schema:"sample_rate,omitempty"`
	Speed                 float64    `json:"speed,omitempty" schema:"speed,omitempty"`
	Tag                   []string   `json:"tag,omitempty" schema:"tag,omitempty"`
	AdditionalQueryParams url.Values `json:"-" schema:"-"`
}

type Client struct {
	apiKey, accessToken, baseURL string
	transport                    liveTransport
}
type Option func(*Client)

// wireStream is the transport-agnostic session surface; both the
// WebSocket and SageMaker bindings satisfy it.
type wireStream interface {
	Send(spectypes.SpeakClientStream) error
	Recv() (spectypes.SpeakServerStream, error)
	Close() error
}
type liveTransport interface {
	connect(ctx context.Context, c *Client, opts *SpeakLiveOptions) (wireStream, error)
}

func New(opts ...Option) *Client {
	c := &Client{apiKey: os.Getenv("DEEPGRAM_API_KEY"), accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"), baseURL: DefaultBaseURL}
	WithWebSocketTransport()(c)
	for _, opt := range opts {
		opt(c)
	}
	return c
}
func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}
func WithAPIKey(apiKey string) Option { return func(c *Client) { c.apiKey = apiKey } }
func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}
func WithBaseURL(baseURL string) Option { return func(c *Client) { c.baseURL = baseURL } }

func (c *Client) Connect(ctx context.Context, opts *SpeakLiveOptions) (*Stream, error) {
	if c.transport == nil {
		WithWebSocketTransport()(c)
	}
	w, err := c.transport.connect(ctx, c, opts)
	if err != nil {
		return nil, err
	}
	return &Stream{transport: w}, nil
}

type webSocketBinding struct{}

// WithWebSocketTransport selects the default cloud WebSocket
// transport (api.deepgram.com). It is set by New; pass a
// WithSageMaker... option to override.
func WithWebSocketTransport() Option { return func(c *Client) { c.transport = webSocketBinding{} } }

func (webSocketBinding) connect(ctx context.Context, c *Client, opts *SpeakLiveOptions) (wireStream, error) {
	headers, err := c.authHeaders()
	if err != nil {
		return nil, err
	}
	query := liveOptionsToQuery(opts).Encode()
	dialURL := c.baseURL + streamPath
	if query != "" {
		dialURL += "?" + query
	}
	return wstransport.OpenStream[spectypes.SpeakClientStream, spectypes.SpeakServerStream](ctx, dialURL, headers, spectypes.MarshalSpeakClientStream, spectypes.UnmarshalSpeakServerStream)
}

func (c *Client) authHeaders() (nethttp.Header, error) {
	h := nethttp.Header{}
	switch {
	case c.accessToken != "":
		h.Set("Authorization", "Bearer "+c.accessToken)
	case c.apiKey != "":
		h.Set("Authorization", "Token "+c.apiKey)
	default:
		return nil, errors.New("speak live: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return h, nil
}

type Stream struct {
	transport wireStream
}

func (s *Stream) SendSpeak(text string) error {
	v := text
	return s.transport.Send(&spectypes.SpeakClientStreamMemberSpeak{Value: spectypes.SpeakText{Text: &v}})
}
func (s *Stream) SendFlush() error {
	return s.transport.Send(&spectypes.SpeakClientStreamMemberFlush{Value: spectypes.SpeakFlush{}})
}
func (s *Stream) SendClear() error {
	return s.transport.Send(&spectypes.SpeakClientStreamMemberClear{Value: spectypes.SpeakClear{}})
}
func (s *Stream) SendClose() error {
	return s.transport.Send(&spectypes.SpeakClientStreamMemberClose{Value: spectypes.SpeakClose{}})
}

// Recv returns the next server message as an idiomatic Event;
// type-switch on the *<Name>Event variants defined in events.go.
func (s *Stream) Recv() (Event, error) {
	msg, err := s.transport.Recv()
	if err != nil {
		return nil, err
	}
	return fromServerStream(msg), nil
}
func (s *Stream) Close() error { return s.transport.Close() }

func liveOptionsToQuery(o *SpeakLiveOptions) url.Values {
	q := optionsStructToQuery(o)
	if o != nil {
		for k, vs := range o.AdditionalQueryParams {
			q.Del(k)
			for _, v := range vs {
				q.Add(k, v)
			}
		}
	}
	return q
}
func optionsStructToQuery(opts any) url.Values {
	q := url.Values{}
	if opts == nil {
		return q
	}
	v := reflect.ValueOf(opts)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := t.Field(i)
		name := field.Tag.Get("schema")
		if name == "" || name == "-" {
			continue
		}
		if comma := stringsIndexByte(name, ','); comma >= 0 {
			name = name[:comma]
		}
		fv := v.Field(i)
		if isZeroQueryField(fv) {
			continue
		}
		addQueryField(q, name, fv)
	}
	return q
}
func stringsIndexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
func isZeroQueryField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map, reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}
func addQueryField(q url.Values, name string, v reflect.Value) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.Slice {
		for i := 0; i < v.Len(); i++ {
			addQueryField(q, name, v.Index(i))
		}
		return
	}
	switch v.Kind() {
	case reflect.String:
		q.Add(name, v.String())
	case reflect.Bool:
		q.Add(name, strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		q.Add(name, strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		q.Add(name, strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		q.Add(name, strconv.FormatFloat(v.Float(), 'g', -1, 64))
	}
}
