// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Client-side live-stream resilience: a Config-driven audio
// frame-size guard and a context-aware send, generalized from
// the hand-tuned Listen-live facade. SDK-only; not on the wire.

package livev2

import (
	"context"
	"errors"
	"fmt"
	"time"

	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

// Config tunes client-side send behavior. Zero value = no limits.
type Config struct {
	MaxFrameSizeBytes int
	SendTimeout       time.Duration
}

var ErrFrameTooLarge = errors.New("flux live: audio frame exceeds Config.MaxFrameSizeBytes")
var ErrSendTimeout = errors.New("flux live: send exceeded Config.SendTimeout")

func (s *Stream) applyConfigSendDefaults(cfg *Config) {
	if cfg == nil {
		return
	}
	s.maxFrameSize = cfg.MaxFrameSizeBytes
	s.sendTimeout = cfg.SendTimeout
}

// SendAudioContext is SendAudio with the frame-size guard plus a
// context deadline / Config.SendTimeout bound on the send.
func (s *Stream) SendAudioContext(ctx context.Context, data []byte) error {
	if s.maxFrameSize > 0 && len(data) > s.maxFrameSize {
		return fmt.Errorf("%w: %d > %d", ErrFrameTooLarge, len(data), s.maxFrameSize)
	}
	if ctx == nil && s.sendTimeout <= 0 {
		return s.SendAudio(data)
	}
	if ctx == nil {
		ctx = context.Background()
	}
	if s.sendTimeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, s.sendTimeout)
		defer cancel()
	}
	done := make(chan error, 1)
	go func() {
		done <- s.transport.Send(&spectypes.FluxClientStreamMemberAudio{Value: spectypes.FluxAudioFrame{Data: data}})
	}()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case err := <-done:
		return err
	}
}
