// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generic HTTP REST transport primitive shared by every @http-bound
// operation in the Smithy model. Invoke uses reflection over input
// struct fields named in HTTPRoute.QueryFields, HeaderFields, and
// PathParams to translate a typed *I into an *http.Request, then
// decodes the JSON response body into a typed *O. The request body
// is supplied as a separate io.Reader so the caller owns payload
// marshalling (some operations encode a union variant or stream
// raw bytes; the generic primitive stays out of that).
//
// Route values are emitted alongside the typed shapes in api/types/
// (e.g. api/types/listen_route.go for the Listen service). This file
// is the runtime primitive; the route values are the per-operation
// metadata.

package http

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"reflect"
	"strconv"
	"strings"

	nethttp "net/http"
	"net/url"
)

// HTTPRoute carries per-operation HTTP binding metadata derived from
// Smithy @http, @httpQuery, @httpHeader, @httpLabel, @httpPayload
// traits at codegen time. The QueryFields / HeaderFields / PathParams
// slices pair Go struct field names on the operation's input type
// with their wire-protocol names; the PayloadField names the single
// member (if any) that binds to the request body via @httpPayload.
type HTTPRoute struct {
	Method       string
	Path         string
	QueryFields  []FieldBinding
	HeaderFields []FieldBinding
	PathParams   []FieldBinding
	PayloadField string
}

// FieldBinding links a Go input struct field name to its wire-protocol
// name. Used by Invoke to translate typed input fields into HTTP
// query / header / path components named per Smithy @httpQuery /
// @httpHeader / @httpLabel traits.
type FieldBinding struct {
	GoField  string
	WireName string
}

// Authenticator applies credentials to an outgoing HTTP request. The
// transport layer calls Apply after request construction, immediately
// before sending; consumers supply a concrete implementation - e.g.,
// bearer token, basic auth, AWS SigV4.
type Authenticator interface {
	Apply(req *nethttp.Request) error
}

// Invoke executes one HTTP operation. It reads HTTP binding fields off
// the typed *input via reflection, builds an *http.Request with the
// supplied body io.Reader, applies auth, sends the request through
// client, and decodes a JSON response body into a newly allocated *O.
//
// body MAY be nil for operations with no request payload (e.g. GETs).
// For operations whose @httpPayload is a union or carries raw audio
// bytes, the caller pre-marshals the payload and passes it as body;
// Invoke does not introspect input.<PayloadField>. The PayloadField
// in the route metadata is documentary - it tells the caller which
// input field should be marshalled into body.
func Invoke[I any, O any](
	ctx context.Context,
	client *nethttp.Client,
	baseURL string,
	route HTTPRoute,
	auth Authenticator,
	input *I,
	body io.Reader,
) (*O, error) {
	if client == nil {
		client = nethttp.DefaultClient
	}

	u, err := url.Parse(baseURL + route.Path)
	if err != nil {
		return nil, fmt.Errorf("http.Invoke: parse URL: %w", err)
	}

	var inputVal reflect.Value
	if input != nil {
		inputVal = reflect.ValueOf(input).Elem()
	}

	if inputVal.IsValid() {
		for _, b := range route.PathParams {
			f := inputVal.FieldByName(b.GoField)
			if !f.IsValid() {
				continue
			}
			val := stringifyField(f)
			if val == "" {
				return nil, fmt.Errorf("http.Invoke: path param %s is empty", b.WireName)
			}
			u.Path = strings.ReplaceAll(u.Path, "{"+b.WireName+"}", url.PathEscape(val))
		}

		q := u.Query()
		for _, b := range route.QueryFields {
			f := inputVal.FieldByName(b.GoField)
			if !f.IsValid() || isZeroField(f) {
				continue
			}
			for _, v := range stringifyMultiField(f) {
				q.Add(b.WireName, v)
			}
		}
		u.RawQuery = q.Encode()
	}

	req, err := nethttp.NewRequestWithContext(ctx, route.Method, u.String(), body)
	if err != nil {
		return nil, fmt.Errorf("http.Invoke: build request: %w", err)
	}

	if inputVal.IsValid() {
		for _, b := range route.HeaderFields {
			f := inputVal.FieldByName(b.GoField)
			if !f.IsValid() || isZeroField(f) {
				continue
			}
			req.Header.Set(b.WireName, stringifyField(f))
		}
	}

	if auth != nil {
		if err := auth.Apply(req); err != nil {
			return nil, fmt.Errorf("http.Invoke: apply auth: %w", err)
		}
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http.Invoke: send: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf(
			"http.Invoke: %s %s: %d %s",
			route.Method, u.String(), resp.StatusCode, string(respBody))
	}

	var out O
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil && err != io.EOF {
		return nil, fmt.Errorf("http.Invoke: decode response: %w", err)
	}
	return &out, nil
}

// isZeroField reports whether v should be treated as unset for the
// purposes of HTTP query/header binding. Pointers, slices, maps and
// strings count as unset when nil/empty; other kinds fall back to
// reflect.Value.IsZero.
func isZeroField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map:
		return v.Len() == 0
	case reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}

// stringifyField renders v as a wire-protocol string. Pointers are
// dereferenced; ints/floats/bools format via strconv; strings and
// string-backed enum types return their underlying value; anything
// else falls through to fmt.Sprintf("%v").
func stringifyField(v reflect.Value) string {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return ""
		}
		v = v.Elem()
	}
	switch v.Kind() {
	case reflect.String:
		return v.String()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return strconv.FormatInt(v.Int(), 10)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return strconv.FormatUint(v.Uint(), 10)
	case reflect.Float32, reflect.Float64:
		return strconv.FormatFloat(v.Float(), 'g', -1, 64)
	case reflect.Bool:
		return strconv.FormatBool(v.Bool())
	}
	return fmt.Sprintf("%v", v.Interface())
}

// stringifyMultiField renders v as one or more wire-protocol strings.
// For slices each element becomes its own string (for repeated query
// params like ?tag=a&tag=b); for everything else the single
// stringifyField output is wrapped in a single-element slice.
func stringifyMultiField(v reflect.Value) []string {
	if v.Kind() == reflect.Slice {
		out := make([]string, 0, v.Len())
		for i := 0; i < v.Len(); i++ {
			out = append(out, stringifyField(v.Index(i)))
		}
		return out
	}
	return []string{stringifyField(v)}
}
