// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generic HTTP REST transport primitive shared by every @http-bound
// operation in the Smithy model. Invoke uses reflection over input
// struct fields named in HTTPRoute.QueryFields, HeaderFields,
// PathParams, and PayloadField to translate a typed *I into an
// *http.Request, then decodes the JSON response body into a typed *O.
//
// Route values are emitted alongside the typed shapes in api/types/
// (e.g. api/types/listen_route.go for the Listen service). This file
// is the runtime primitive; the route values are the per-operation
// metadata.
//
// Status: the Invoke body is intentionally stubbed pending the Phase 4
// wire-up of the endpoint-agnostic transport migration. The signature
// is final; consumers can already depend on the symbol. The body will
// be filled in once route metadata emission (Phase 2) lands.

package http

import (
	"context"
	"errors"

	nethttp "net/http"
)

// HTTPRoute carries per-operation HTTP binding metadata derived from
// Smithy @http, @httpQuery, @httpHeader, @httpLabel, @httpPayload
// traits at codegen time. The QueryFields / HeaderFields / PathParams
// slices name struct fields on the operation's input type; the
// PayloadField names the single member (if any) that binds to the
// request body via @httpPayload.
type HTTPRoute struct {
	Method       string
	Path         string
	QueryFields  []string
	HeaderFields []string
	PathParams   []string
	PayloadField string
}

// Authenticator applies credentials to an outgoing HTTP request. The
// transport layer calls Apply after request construction, immediately
// before sending; consumers supply a concrete implementation - e.g.,
// bearer token, basic auth, AWS SigV4.
type Authenticator interface {
	Apply(req *nethttp.Request) error
}

// Invoke executes one HTTP operation. It reads HTTP binding fields off
// the typed *input via reflection, builds an *http.Request, sends it
// through client, and decodes a JSON response body into a newly
// allocated *O.
//
// PHASE 1 STATUS: this is a stub. The body is implemented in Phase 4
// of the endpoint-agnostic transport migration once Phase 2 has
// emitted the per-operation route metadata in api/types/. The
// signature is the contract; callers can build against it.
func Invoke[I any, O any](
	ctx context.Context,
	client *nethttp.Client,
	baseURL string,
	route HTTPRoute,
	auth Authenticator,
	input *I,
) (*O, error) {
	_ = ctx
	_ = client
	_ = baseURL
	_ = route
	_ = auth
	_ = input
	return nil, errors.New(
		"http.Invoke: not yet wired (phase 4 of endpoint-agnostic transports)")
}
