// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Generated wire-test stubs that enforce the api/-to-facade wiring contract.
// Every public @httpQuery member on the generated wire input shape gets a
// TestWires_<Field>_Generated stub here that:
//
//   1. Constructs the facade options struct with the field set to a
//      non-zero sample value. If the facade is missing that field,
//      this file fails to COMPILE — `unknown field <Field> in struct
//      literal of type interfaces.<FacadeOptionsType>`.
//
//   2. Runs the facade -> wire converter and asserts the value reaches
//      the generated wire shape. If the converter is missing a wiring
//      block, the stub fails at RUNTIME via requireWired.
//
// Either failure mode signals that the facade has drifted from api/.
// Fix the facade struct and converter; do NOT edit this file. This file
// is regenerated by spec-codegen-go on every regen and is sacred from the
// perspective of the spec-idiomatic LLM regen and its post-LLM cleanup
// passes.
//
// Manual wire tests (type-specific value coverage, edge cases) live in
// wire_test.go.

package restv1

import (
	"testing"

	interfaces "github.com/deepgram/spec-mock-go-sdk/pkg/client/interfaces/v1"
)

func TestWires_Callback_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Callback: "test"})
	requireWired(t, in, "Callback")
}

func TestWires_CallbackMethod_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{CallbackMethod: "test"})
	requireWired(t, in, "CallbackMethod")
}

func TestWires_Model_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Model: "test"})
	requireWired(t, in, "Model")
}

func TestWires_Language_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Language: "test"})
	requireWired(t, in, "Language")
}

func TestWires_Version_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Version: "test"})
	requireWired(t, in, "Version")
}

func TestWires_Punctuate_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Punctuate: true})
	requireWired(t, in, "Punctuate")
}

func TestWires_Diarize_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Diarize: true})
	requireWired(t, in, "Diarize")
}

func TestWires_DiarizeVersion_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{DiarizeVersion: "test"})
	requireWired(t, in, "DiarizeVersion")
}

func TestWires_DiarizeModel_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{DiarizeModel: "test"})
	requireWired(t, in, "DiarizeModel")
}

func TestWires_VadTurnoff_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{VadTurnoff: 1})
	requireWired(t, in, "VadTurnoff")
}

func TestWires_SmartFormat_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{SmartFormat: true})
	requireWired(t, in, "SmartFormat")
}

func TestWires_Utterances_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Utterances: true})
	requireWired(t, in, "Utterances")
}

func TestWires_Paragraphs_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Paragraphs: true})
	requireWired(t, in, "Paragraphs")
}

func TestWires_Multichannel_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Multichannel: true})
	requireWired(t, in, "Multichannel")
}

func TestWires_Redact_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Redact: []string{"test"}})
	requireWired(t, in, "Redact")
}

func TestWires_Keywords_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Keywords: []string{"test"}})
	requireWired(t, in, "Keywords")
}

func TestWires_Keyterm_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Keyterm: []string{"test"}})
	requireWired(t, in, "Keyterm")
}

func TestWires_Search_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Search: []string{"test"}})
	requireWired(t, in, "Search")
}

func TestWires_Replace_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Replace: []string{"test"}})
	requireWired(t, in, "Replace")
}

func TestWires_Tag_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Tag: []string{"test"}})
	requireWired(t, in, "Tag")
}

func TestWires_Encoding_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Encoding: "test"})
	requireWired(t, in, "Encoding")
}

func TestWires_FillerWords_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{FillerWords: true})
	requireWired(t, in, "FillerWords")
}

func TestWires_ProfanityFilter_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{ProfanityFilter: true})
	requireWired(t, in, "ProfanityFilter")
}

func TestWires_Sentiment_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Sentiment: true})
	requireWired(t, in, "Sentiment")
}

func TestWires_Topics_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Topics: true})
	requireWired(t, in, "Topics")
}

func TestWires_Intents_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Intents: true})
	requireWired(t, in, "Intents")
}

func TestWires_Summarize_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Summarize: "test"})
	requireWired(t, in, "Summarize")
}

func TestWires_DetectEntities_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{DetectEntities: true})
	requireWired(t, in, "DetectEntities")
}

func TestWires_DetectLanguage_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{DetectLanguage: []string{"test"}})
	requireWired(t, in, "DetectLanguage")
}

func TestWires_MipOptOut_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{MipOptOut: true})
	requireWired(t, in, "MipOptOut")
}

func TestWires_LogData_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{LogData: true})
	requireWired(t, in, "LogData")
}

func TestWires_Numerals_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Numerals: true})
	requireWired(t, in, "Numerals")
}

func TestWires_Dictation_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Dictation: true})
	requireWired(t, in, "Dictation")
}

func TestWires_Measurements_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{Measurements: true})
	requireWired(t, in, "Measurements")
}

func TestWires_UttSplit_Generated(t *testing.T) {
	in := optionsToTranscribeInput(&interfaces.PreRecordedTranscriptionOptions{UttSplit: 1.0})
	requireWired(t, in, "UttSplit")
}

