// Code generated by spec-codegen-go. DO NOT EDIT.
//
// Customer-facing live (WebSocket) client, generated by
// spec-codegen-go's model-driven streaming facade emitter.
// Recv returns the raw server union; type-switch on its members.

package livev1

import (
	"context"
	"errors"
	nethttp "net/http"
	"net/url"
	"os"
	"reflect"
	"strconv"

	wstransport "github.com/deepgram/spec-mock-go-sdk/api/transport/websocket"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

const DefaultBaseURL = "wss://api.deepgram.com"
const streamPath = "/v1/agent/converse"

type AgentLiveOptions struct {
	AdditionalQueryParams url.Values `json:"-" schema:"-"`
}

type Client struct{ apiKey, accessToken, baseURL string }
type Option func(*Client)

func New(opts ...Option) *Client {
	c := &Client{apiKey: os.Getenv("DEEPGRAM_API_KEY"), accessToken: os.Getenv("DEEPGRAM_ACCESS_TOKEN"), baseURL: DefaultBaseURL}
	for _, opt := range opts {
		opt(c)
	}
	return c
}
func WithCredentials(apiKey, accessToken string) Option {
	return func(c *Client) { c.apiKey, c.accessToken = apiKey, accessToken }
}
func WithAPIKey(apiKey string) Option { return func(c *Client) { c.apiKey = apiKey } }
func WithAccessToken(accessToken string) Option {
	return func(c *Client) { c.accessToken = accessToken }
}
func WithBaseURL(baseURL string) Option { return func(c *Client) { c.baseURL = baseURL } }

func (c *Client) Connect(ctx context.Context, opts *AgentLiveOptions) (*Stream, error) {
	headers, err := c.authHeaders()
	if err != nil {
		return nil, err
	}
	query := liveOptionsToQuery(opts).Encode()
	dialURL := c.baseURL + streamPath
	if query != "" {
		dialURL += "?" + query
	}
	ws, err := wstransport.OpenStream[spectypes.AgentClientStream, spectypes.AgentServerStream](ctx, dialURL, headers, spectypes.MarshalAgentClientStream, spectypes.UnmarshalAgentServerStream)
	if err != nil {
		return nil, err
	}
	return &Stream{transport: ws}, nil
}

func (c *Client) authHeaders() (nethttp.Header, error) {
	h := nethttp.Header{}
	switch {
	case c.accessToken != "":
		h.Set("Authorization", "Bearer "+c.accessToken)
	case c.apiKey != "":
		h.Set("Authorization", "Token "+c.apiKey)
	default:
		return nil, errors.New("agent live: no credentials; set DEEPGRAM_API_KEY or DEEPGRAM_ACCESS_TOKEN, or pass WithCredentials(...)")
	}
	return h, nil
}

type Stream struct {
	transport wstransport.Stream[spectypes.AgentClientStream, spectypes.AgentServerStream]
}

func (s *Stream) SendAudio(data []byte) error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberAudio{Value: spectypes.AgentAudioFrame{Data: data}})
}
func (s *Stream) SendSettings(v spectypes.AgentSettings) error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberSettings{Value: v})
}
func (s *Stream) SendUpdatePrompt(prompt string) error {
	v := prompt
	return s.transport.Send(&spectypes.AgentClientStreamMemberUpdatePrompt{Value: spectypes.AgentUpdatePrompt{Prompt: &v}})
}
func (s *Stream) SendReplacePrompt(prompt string) error {
	v := prompt
	return s.transport.Send(&spectypes.AgentClientStreamMemberReplacePrompt{Value: spectypes.AgentReplacePrompt{Prompt: &v}})
}
func (s *Stream) SendUpdateSpeak(v spectypes.AgentUpdateSpeak) error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberUpdateSpeak{Value: v})
}
func (s *Stream) SendUpdateThink(v spectypes.AgentUpdateThink) error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberUpdateThink{Value: v})
}
func (s *Stream) SendKeepAlive() error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberKeepAlive{Value: spectypes.AgentKeepAlive{}})
}
func (s *Stream) SendInjectUserMessage(content string) error {
	v := content
	return s.transport.Send(&spectypes.AgentClientStreamMemberInjectUserMessage{Value: spectypes.AgentInjectUserMessage{Content: &v}})
}
func (s *Stream) SendInjectAgentMessage(v spectypes.AgentInjectAgentMessage) error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberInjectAgentMessage{Value: v})
}
func (s *Stream) SendFunctionCallResponse(v spectypes.AgentFunctionCallResponse) error {
	return s.transport.Send(&spectypes.AgentClientStreamMemberFunctionCallResponse{Value: v})
}

// Recv returns the next server message. Type-switch on the
// spectypes.AgentServerStream variants (incl. the binary audio member).
func (s *Stream) Recv() (spectypes.AgentServerStream, error) { return s.transport.Recv() }
func (s *Stream) Close() error                               { return s.transport.Close() }

func liveOptionsToQuery(o *AgentLiveOptions) url.Values {
	q := optionsStructToQuery(o)
	if o != nil {
		for k, vs := range o.AdditionalQueryParams {
			q.Del(k)
			for _, v := range vs {
				q.Add(k, v)
			}
		}
	}
	return q
}
func optionsStructToQuery(opts any) url.Values {
	q := url.Values{}
	if opts == nil {
		return q
	}
	v := reflect.ValueOf(opts)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := t.Field(i)
		name := field.Tag.Get("schema")
		if name == "" || name == "-" {
			continue
		}
		if comma := stringsIndexByte(name, ','); comma >= 0 {
			name = name[:comma]
		}
		fv := v.Field(i)
		if isZeroQueryField(fv) {
			continue
		}
		addQueryField(q, name, fv)
	}
	return q
}
func stringsIndexByte(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return -1
}
func isZeroQueryField(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return v.IsNil()
	case reflect.Slice, reflect.Map, reflect.String:
		return v.Len() == 0
	default:
		return v.IsZero()
	}
}
func addQueryField(q url.Values, name string, v reflect.Value) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.Slice {
		for i := 0; i < v.Len(); i++ {
			addQueryField(q, name, v.Index(i))
		}
		return
	}
	switch v.Kind() {
	case reflect.String:
		q.Add(name, v.String())
	case reflect.Bool:
		q.Add(name, strconv.FormatBool(v.Bool()))
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		q.Add(name, strconv.FormatInt(v.Int(), 10))
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		q.Add(name, strconv.FormatUint(v.Uint(), 10))
	case reflect.Float32, reflect.Float64:
		q.Add(name, strconv.FormatFloat(v.Float(), 'g', -1, 64))
	}
}
