// Code generated by spec-codegen-go. DO NOT EDIT.
//
// SageMaker bidirectional transport binding for this live
// product. Wraps the AWS HTTP/2 SageMaker runtime client and
// preserves the shared wireStream surface (see client.go).

package livev1

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	sm "github.com/deepgram/spec-mock-go-sdk/api/transport/sagemaker"
	spectypes "github.com/deepgram/spec-mock-go-sdk/api/types"
)

type sageMakerBidiBinding struct {
	cfg                aws.Config
	endpointName       string
	targetVariant      string
	targetModel        string
	inferenceID        string
	enableExplanations string
}
type SageMakerOption func(*sageMakerBidiBinding)

// WithSageMakerBidiTransport routes the stream to a self-hosted
// SageMaker endpoint instead of the cloud WebSocket. Pass the
// aws.Config from config.LoadDefaultConfig; a fresh, isolated
// HTTP/2 client is built per Connect so each stream gets its own
// connection (see sm.NewBidiClient / SAGEMAKER-002).
func WithSageMakerBidiTransport(cfg aws.Config, endpointName string, opts ...SageMakerOption) Option {
	return func(c *Client) {
		b := sageMakerBidiBinding{cfg: cfg, endpointName: endpointName}
		for _, o := range opts {
			o(&b)
		}
		c.transport = b
	}
}
func WithTargetVariant(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.targetVariant = v }
}
func WithTargetModel(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.targetModel = v }
}
func WithInferenceID(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.inferenceID = v }
}
func WithEnableExplanations(v string) SageMakerOption {
	return func(b *sageMakerBidiBinding) { b.enableExplanations = v }
}

func (t sageMakerBidiBinding) connect(ctx context.Context, c *Client, opts *AgentLiveOptions) (wireStream, error) {
	_ = c
	query := liveOptionsToQuery(opts).Encode()
	// DialBidi builds a fresh isolated client per attempt (conn-per-stream)
	// and retries transient connect failures with backoff + jitter.
	return sm.DialBidi(ctx, t.cfg, sm.DefaultConfig(), t.endpointName, "v1/agent/converse", query, t.targetVariant, t.targetModel, t.inferenceID, t.enableExplanations, spectypes.MarshalAgentClientStream, spectypes.UnmarshalAgentServerStream)
}
